# Generated by Django 5.2.10 on 2026-06-02 22:13

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import secretariador.functions
import secretariador.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('carga', '0001_initial'),
        ('personalizador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organigrama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organigrama_cargo', models.CharField(max_length=120, verbose_name='Cargo')),
                ('organigrama_escalafon', models.DecimalField(decimal_places=0, default=2, max_digits=1, verbose_name='Escalafón')),
            ],
            options={
                'verbose_name': 'Organigrama',
                'verbose_name_plural': 'Organigramas',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('usuario_dni', models.DecimalField(blank=True, decimal_places=0, max_digits=9, unique=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='DNI:')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentosLegalesDecretos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrumentolegaldecretos_tipo', models.CharField(choices=[('N', 'Decreto Nacional'), ('P', 'Decreto Provincial')], default='P', max_length=1, verbose_name='Tipo')),
                ('instrumentolegaldecretos_numero', models.CharField(max_length=7, verbose_name='Número')),
                ('instrumentolegaldecretos_ano', models.CharField(max_length=5, verbose_name='Año')),
                ('instrumentolegaldecretos_fecha_aprobacion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Aprobación')),
                ('instrumentolegaldecretos_descripcion', models.CharField(default='Escala de viáticos', max_length=600, verbose_name='Descripción')),
                ('instrumentolegaldecretos', models.FileField(blank=True, max_length=500, null=True, upload_to=secretariador.models.generate_name_decretos, validators=[secretariador.functions.FileValidator(content_types='application/pdf', max_size=14680064, min_size=None)])),
                ('instrumentolegaldecretos_str', models.GeneratedField(db_persist=True, expression=secretariador.models.ConcatOp('instrumentolegaldecretos_numero', models.Value(' - '), 'instrumentolegaldecretos_ano', models.Value(' - '), 'instrumentolegaldecretos_tipo'), output_field=models.TextField())),
            ],
            options={
                'verbose_name': 'Instrumento Legal(Decreto)',
                'verbose_name_plural': 'Instrumentos Legales(Decretos)',
                'ordering': ['-instrumentolegaldecretos_ano', '-instrumentolegaldecretos_numero'],
                'get_latest_by': ['instrumentolegaldecretos_ano', 'instrumentolegaldecretos_numero'],
                'constraints': [models.UniqueConstraint(fields=('instrumentolegaldecretos_tipo', 'instrumentolegaldecretos_numero', 'instrumentolegaldecretos_ano', 'instrumentolegaldecretos_fecha_aprobacion'), name='unique_decretos_1')],
            },
        ),
        migrations.CreateModel(
            name='InstrumentosLegalesMemorandum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrumentolegalmemorandum_tipo', models.CharField(choices=[('P', 'Presidencia'), ('D', 'Dirección General de Gestión Administrativa')], default='P', max_length=1, verbose_name='Tipo')),
                ('instrumentolegalmemorandum_numero', models.CharField(max_length=7, verbose_name='Número')),
                ('instrumentolegalmemorandum_ano', models.CharField(max_length=5, verbose_name='Año')),
                ('instrumentolegalmemorandum_fecha_aprobacion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Aprobación')),
                ('instrumentolegalmemorandum_descripcion', models.CharField(default='', max_length=600, verbose_name='Descripción')),
                ('instrumentolegalmemorandum', models.FileField(blank=True, max_length=500, null=True, upload_to=secretariador.models.generate_name_memorandum, validators=[secretariador.functions.FileValidator(content_types='application/pdf', max_size=14680064, min_size=None)])),
                ('instrumentolegalmemorandum_str', models.GeneratedField(db_persist=True, expression=secretariador.models.ConcatOp('instrumentolegalmemorandum_numero', models.Value(' - '), 'instrumentolegalmemorandum_ano', models.Value(' - '), 'instrumentolegalmemorandum_tipo'), output_field=models.TextField())),
                ('instrumentolegalmemorandum_autocarga', models.BooleanField(default=False, verbose_name='Memorandum importado sin intervención humana.')),
                ('instrumentolegalmemorandum_document', models.TextField(blank=True, null=True, verbose_name='Texto Extraído por OCR')),
            ],
            options={
                'verbose_name': 'Instrumento Legal(Memorandum)',
                'verbose_name_plural': 'Instrumentos Legales(Memorandums)',
                'ordering': ['-instrumentolegalmemorandum_ano', '-instrumentolegalmemorandum_numero'],
                'constraints': [models.UniqueConstraint(fields=('instrumentolegalmemorandum_tipo', 'instrumentolegalmemorandum_numero', 'instrumentolegalmemorandum_ano'), name='unique_memorandum_1')],
            },
        ),
        migrations.CreateModel(
            name='InstrumentosLegalesResoluciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrumentolegalresoluciones_tipo', models.CharField(choices=[('P', 'Resolución de Presidencia'), ('D', 'Resolución de Directorio')], default='P', max_length=1, verbose_name='Tipo')),
                ('instrumentolegalresoluciones_numero', models.CharField(max_length=7, verbose_name='Número')),
                ('instrumentolegalresoluciones_acta', models.CharField(default='', max_length=3, verbose_name='Acta')),
                ('instrumentolegalresoluciones_ano', models.CharField(max_length=5, verbose_name='Año')),
                ('instrumentolegalresoluciones_fecha_aprobacion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Aprobación')),
                ('instrumentolegalresoluciones_descripcion', models.CharField(default='', max_length=600, verbose_name='Descripción')),
                ('instrumentolegalresoluciones', models.FileField(blank=True, max_length=500, null=True, upload_to=secretariador.models.generate_name_resoluciones, validators=[secretariador.functions.FileValidator(content_types='application/pdf', max_size=14680064, min_size=None)])),
                ('instrumentolegalresoluciones_str', models.GeneratedField(db_persist=True, expression=secretariador.models.ConcatOp('instrumentolegalresoluciones_numero', models.Value(' - '), 'instrumentolegalresoluciones_ano', models.Value(' - '), 'instrumentolegalresoluciones_tipo'), output_field=models.TextField())),
                ('instrumentolegalresoluciones_autocarga', models.BooleanField(default=False, verbose_name='Resolución importada sin intervención.')),
                ('instrumentolegalresoluciones_document', models.TextField(blank=True, null=True, verbose_name='Texto Extraído por OCR')),
                ('instrumentolegalresoluciones_numero_sgt', models.GeneratedField(db_persist=True, expression=secretariador.models.ConcatOp(models.Value('RES-'), 'instrumentolegalresoluciones_ano', models.Value('-'), 'instrumentolegalresoluciones_numero', models.Value('-10-1')), output_field=models.CharField(max_length=20))),
            ],
            options={
                'verbose_name': 'Instrumento Legal(Resolución)',
                'verbose_name_plural': 'Instrumentos Legales(Resoluciones)',
                'ordering': ['-instrumentolegalresoluciones_ano', '-instrumentolegalresoluciones_numero'],
                'constraints': [models.UniqueConstraint(fields=('instrumentolegalresoluciones_tipo', 'instrumentolegalresoluciones_numero', 'instrumentolegalresoluciones_ano'), name='unique_resolucion_1')],
            },
        ),
        migrations.CreateModel(
            name='InstrumentosLegalesResolucionesDirectorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrumentolegalresolucionesdirectorio_tipo', models.CharField(choices=[('D', 'Resolución de Directorio')], default='P', max_length=1, verbose_name='Tipo')),
                ('instrumentolegalresolucionesdirectorio_numero', models.CharField(max_length=7, verbose_name='Número')),
                ('instrumentolegalresolucionesdirectorio_acta', models.CharField(default='', max_length=3, verbose_name='Acta')),
                ('instrumentolegalresolucionesdirectorio_ano', models.CharField(max_length=5, verbose_name='Año')),
                ('instrumentolegalresolucionesdirectorio_fecha_aprobacion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Aprobación')),
                ('instrumentolegalresolucionesdirectorio_descripcion', models.CharField(default='', max_length=600, verbose_name='Descripción')),
                ('instrumentolegalresolucionesdirectorio', models.FileField(blank=True, max_length=500, null=True, upload_to=secretariador.models.generate_name_resoluciones, validators=[secretariador.functions.FileValidator(content_types='application/pdf', max_size=14680064, min_size=None)])),
                ('instrumentolegalresolucionesdirectorio_str', models.GeneratedField(db_persist=True, expression=secretariador.models.ConcatOp('instrumentolegalresolucionesdirectorio_numero', models.Value(' - '), 'instrumentolegalresolucionesdirectorio_ano', models.Value(' - '), 'instrumentolegalresolucionesdirectorio_tipo'), output_field=models.TextField())),
                ('instrumentolegalresolucionesdirectorio_autocarga', models.BooleanField(default=False, verbose_name='Resolución importada sin intervención.')),
                ('instrumentolegalresolucionesdirectorio_document', models.TextField(blank=True, null=True, verbose_name='Texto Extraído por OCR')),
            ],
            options={
                'verbose_name': 'Instrumento Legal(Resolución Directorio)',
                'verbose_name_plural': 'Instrumentos Legales(Resoluciones Directorio)',
                'ordering': ['-instrumentolegalresolucionesdirectorio_ano', '-instrumentolegalresolucionesdirectorio_numero'],
                'constraints': [models.UniqueConstraint(fields=('instrumentolegalresolucionesdirectorio_tipo', 'instrumentolegalresolucionesdirectorio_numero', 'instrumentolegalresolucionesdirectorio_acta', 'instrumentolegalresolucionesdirectorio_ano'), name='unique_resolucion_directorio_1')],
            },
        ),
        migrations.CreateModel(
            name='MontoViaticoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montoviaticodiario_estrato_uno_interior', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Viatico diario Estrato I dentro de la Provincia')),
                ('montoviaticodiario_estrato_dos_interior', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Viatico diario Estrato II dentro de la Provincia')),
                ('montoviaticodiario_estrato_tres_interior', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Viatico diario Estrato III dentro de la Provincia')),
                ('montoviaticodiario_estrato_cuatro_interior', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Viatico diario Estrato IV dentro de la Provincia')),
                ('montoviaticodiario_estrato_uno_exterior', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Viatico diario Estrato I fuera de la Provincia')),
                ('montoviaticodiario_estrato_dos_exterior', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Viatico diario Estrato II fuera de la Provincia')),
                ('montoviaticodiario_estrato_tres_exterior', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Viatico diario Estrato III fuera de la Provincia')),
                ('montoviaticodiario_estrato_cuatro_exterior', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Viatico diario Estrato IV fuera de la Provincia')),
                ('montoviaticodiario_decreto_reglamentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariador.instrumentoslegalesdecretos')),
            ],
            options={
                'verbose_name': 'Monto diario de Viático',
                'verbose_name_plural': 'Monto diario de Viáticos',
                'ordering': ['montoviaticodiario_decreto_reglamentario__instrumentolegaldecretos_ano', 'montoviaticodiario_decreto_reglamentario__instrumentolegaldecretos_numero'],
                'get_latest_by': ['montoviaticodiario_decreto_reglamentario__instrumentolegaldecretos_ano', 'montoviaticodiario_decreto_reglamentario__instrumentolegaldecretos_numero'],
            },
        ),
        migrations.CreateModel(
            name='Comisionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comisionado_nombres', models.CharField(max_length=120, verbose_name='Nombres')),
                ('comisionado_apellidos', models.CharField(max_length=120, verbose_name='Apellidos')),
                ('comisionado_abreviatura', models.CharField(help_text='(Sr., Sra., Dr., Dra., Etc.)', max_length=10, verbose_name='Abreviatura')),
                ('comisionado_sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo')),
                ('comisionado_dni', models.DecimalField(decimal_places=0, max_digits=9, unique=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='DNI:')),
                ('comisionado_cuit', models.CharField(max_length=13, validators=[secretariador.functions.CuitValidator()], verbose_name='CUIT')),
                ('comisionado_nombreyapellido', models.GeneratedField(db_persist=True, expression=secretariador.models.ConcatOp('comisionado_apellidos', models.Value(', '), 'comisionado_nombres'), output_field=models.TextField())),
                ('comisionado_verificado_contra_padron', models.BooleanField(default=False, verbose_name='Chequeado')),
                ('comisionado_personal_transitorio', models.BooleanField(default=False, verbose_name='Personal Transitorio')),
                ('comisionado_personal_de_gabinete', models.BooleanField(default=False, verbose_name='Personal de Gabinete')),
                ('comisionado_cargo_decreto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargo_decreto', to='personalizador.cargos', verbose_name='Cargo Decreto')),
                ('comisionado_cargo_interno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargo_interno', to='personalizador.cargos', verbose_name='Cargo Interno')),
                ('comisionado_cargo_interno_resolucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secretariador.instrumentoslegalesresoluciones')),
                ('comisionado_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariador.organigrama')),
            ],
            options={
                'verbose_name': 'Comisionado',
                'verbose_name_plural': 'Comisionados',
                'ordering': ('comisionado_apellidos',),
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitud_actuacion', models.GeneratedField(db_persist=True, expression=secretariador.models.ConcatOp('solicitud_actuacion_jurisdiccion', models.Value('-'), 'solicitud_actuacion_ano', models.Value('-'), 'solicitud_actuacion_numero', models.Value('-AE')), output_field=models.TextField())),
                ('solicitud_actuacion_jurisdiccion', models.CharField(default='E10', max_length=3, verbose_name='Jurisdicción')),
                ('solicitud_actuacion_numero', models.DecimalField(decimal_places=0, default=0, help_text='Solo el número de la actuación. Sin prefijo, sufijo o Año.', max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='N° Actuación')),
                ('solicitud_actuacion_ano', models.DecimalField(decimal_places=0, default=2026, max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Año Actuación')),
                ('solicitud_ciudad', models.CharField(blank=True, help_text='... en la ciudad de #Texto ingresado en el formulario#', max_length=200, null=True, verbose_name='Ciudad')),
                ('solicitud_fecha_desde', models.DateField(verbose_name='Fecha Inicio')),
                ('solicitud_fecha_hasta', models.DateField(verbose_name='Fecha Regreso')),
                ('solicitud_tareas', models.TextField(help_text='... a fin de #Texto ingresado en el formulario# en la localidad de #Localidad#', verbose_name='Tareas a Realizar')),
                ('solicitud_aereo', models.BooleanField(blank=True, help_text='Tildar si es viaje aereo', null=True, verbose_name='Aereo')),
                ('solicitud_dia_inhabil', models.BooleanField(help_text='Tildar si es un diá de no laboral', verbose_name='Dia Inhábil')),
                ('solicitud_cantidad_de_dias', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('solicitud_fecha_hasta'), '-', models.F('solicitud_fecha_desde')), '+', models.Value(datetime.timedelta(days=1))), output_field=models.DurationField())),
                ('solicitud_anulada', models.BooleanField(default=False, help_text='Si la solicitud se encuentra anulada, no se registra en los reportes.', verbose_name='Anulada')),
                ('solicitud_decreto_viaticos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariador.montoviaticodiario')),
                ('solicitud_localidades', models.ManyToManyField(blank=True, to='carga.localidad')),
                ('solicitud_provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.provincia')),
                ('solicitud_resolucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secretariador.instrumentoslegalesresoluciones', verbose_name='Resolución Aprobada')),
                ('solicitud_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariador.comisionado')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
            },
        ),
        migrations.CreateModel(
            name='Incorporacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incorporacion_actuacion', models.GeneratedField(db_persist=True, expression=secretariador.models.ConcatOp('incorporacion_actuacion_jurisdiccion', models.Value('-'), 'incorporacion_actuacion_ano', models.Value('-'), 'incorporacion_actuacion_numero', models.Value('-AE')), output_field=models.TextField())),
                ('incorporacion_actuacion_jurisdiccion', models.CharField(default='E10', max_length=3, verbose_name='Jurisdicción')),
                ('incorporacion_actuacion_numero', models.DecimalField(decimal_places=0, default=0, help_text='Solo el número de la actuación. Sin prefijo, sufijo o Año.', max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='N° Actuación')),
                ('incorporacion_actuacion_ano', models.DecimalField(decimal_places=0, default=2026, max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Año Actuación')),
                ('incorporacion_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariador.comisionado')),
                ('incorporacion_resolucion', models.ForeignKey(blank=True, help_text='Resolución que aprueba la incorporación de los agentes.', null=True, on_delete=django.db.models.deletion.CASCADE, to='secretariador.instrumentoslegalesresoluciones', verbose_name='Resolución Aprobada')),
                ('incorporacion_solicitud', models.ForeignKey(help_text='Actuación a la que se incorpora los agentes.', on_delete=django.db.models.deletion.CASCADE, to='secretariador.solicitud')),
            ],
            options={
                'verbose_name': 'Incorporación',
                'verbose_name_plural': 'Incorporaciones',
            },
        ),
        migrations.CreateModel(
            name='ComisionadoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comisionadosolicitud_colaborador', models.BooleanField(verbose_name='Colab.?')),
                ('comisionadosolicitud_chofer', models.BooleanField(verbose_name='Chofer?')),
                ('comisionadosolicitud_combustible', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Combustible')),
                ('comisionadosolicitud_pasaje', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Pasajes')),
                ('comisionadosolicitud_gastos', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Gastos')),
                ('comisionadosolicitud_sin_viatico', models.BooleanField(default=False, verbose_name='$0')),
                ('comisionadosolicitud_viatico_diario', models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=12, null=True, verbose_name='Viatico Diario')),
                ('comisionadosolicitud_viatico_computado', models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=12, null=True, verbose_name='Viatico Computado')),
                ('comisionadosolicitud_viatico_total', models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=12, null=True, verbose_name='Viatico Total')),
                ('comisionadosolicitud_cantidad_de_dias', models.DurationField(blank=True, editable=False, null=True, verbose_name='Días')),
                ('comisionadosolicitud_nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariador.comisionado')),
                ('comisionadosolicitud_incorporacion_foreign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secretariador.incorporacion')),
                ('comisionadosolicitud_foreign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secretariador.solicitud')),
            ],
            options={
                'verbose_name': 'Comisionado Solicitud',
                'verbose_name_plural': 'Comisionado Solicitudes',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiculo_caracter', models.CharField(choices=[('E', 'Empresa'), ('O', 'Oficial'), ('P', 'Particular')], default='O', max_length=1, verbose_name='Vehiculo Designación')),
                ('vehiculo_modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('vehiculo_patente', models.CharField(max_length=9, verbose_name='Patente')),
                ('vehiculo_poliza', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Póliza')),
                ('vehiculo_str', models.GeneratedField(db_persist=True, expression=secretariador.models.ConcatOp('vehiculo_modelo', models.Value(' - '), 'vehiculo_patente'), output_field=models.TextField())),
                ('vehiculo_n_motor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Motor')),
                ('vehiculo_n_chasis', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Chasis')),
                ('vehiculo_modelo_ano', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Año del Modelo')),
                ('vehiculo_poliza_aseguradora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carga.aseguradora')),
                ('vehiculo_titular_agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secretariador.comisionado')),
                ('vehiculo_titular_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carga.empresa')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['vehiculo_modelo', 'vehiculo_patente'],
            },
        ),
        migrations.AddField(
            model_name='solicitud',
            name='solicitud_vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secretariador.vehiculo'),
        ),
        migrations.AddConstraint(
            model_name='comisionado',
            constraint=models.UniqueConstraint(fields=('comisionado_nombres', 'comisionado_apellidos', 'comisionado_dni'), name='unique_comisionado_1'),
        ),
        migrations.AddConstraint(
            model_name='incorporacion',
            constraint=models.UniqueConstraint(fields=('incorporacion_solicitud',), name='unique_incorporacion_1'),
        ),
        migrations.AddConstraint(
            model_name='incorporacion',
            constraint=models.UniqueConstraint(fields=('incorporacion_actuacion_jurisdiccion', 'incorporacion_actuacion_ano', 'incorporacion_actuacion_numero'), name='unique_incorporacion_2'),
        ),
        migrations.AddConstraint(
            model_name='vehiculo',
            constraint=models.UniqueConstraint(fields=('vehiculo_modelo', 'vehiculo_patente'), name='unique_vehiculo_1'),
        ),
        migrations.AddConstraint(
            model_name='solicitud',
            constraint=models.UniqueConstraint(fields=('solicitud_actuacion',), name='unique_solicitud_1'),
        ),
        migrations.AddConstraint(
            model_name='solicitud',
            constraint=models.UniqueConstraint(fields=('solicitud_actuacion_jurisdiccion', 'solicitud_actuacion_ano', 'solicitud_actuacion_numero'), name='unique_solicitud_2'),
        ),
    ]
