# Generated by Django 5.0.3 on 2024-03-19 14:46

import django.core.validators
import django.db.models.deletion
import secretariador.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carga', '0030_contratosdigitales_contratodigital_nombre_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organigrama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organigrama_cargo', models.CharField(max_length=120, verbose_name='Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiculo_modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('vehiculo_patente', models.CharField(max_length=9, verbose_name='Patente')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
            },
        ),
        migrations.CreateModel(
            name='Comisionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comisionado_nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('comisionado_abreviatura', models.CharField(max_length=10, verbose_name='Abreviatura')),
                ('comisionado_sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo')),
                ('comisionado_dni', models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='DNI:')),
                ('comisionado_cuit', models.CharField(max_length=13, validators=[secretariador.functions.validar_cuit], verbose_name='CUIT')),
                ('comisionado_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariador.organigrama')),
            ],
            options={
                'verbose_name': 'Comisionado',
                'verbose_name_plural': 'Comisionados',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitud_actuacion', models.CharField(max_length=18, verbose_name='Actuación')),
                ('solicitud_fecha_desde', models.DateField(verbose_name='Fecha Inicio')),
                ('solicitud_fecha_hasta', models.DateField(verbose_name='Fecha Regreso')),
                ('solicitud_tareas', models.TextField(verbose_name='Tareas a Realizar')),
                ('solicitud_dia_inhabil', models.BooleanField(verbose_name='Dia Inhábil')),
                ('solicitud_involucrados', models.ManyToManyField(related_name='solicitud_comisionados', to='secretariador.comisionado', verbose_name='Involucrados')),
                ('solicitud_localidades', models.ManyToManyField(to='carga.localidad')),
                ('solicitud_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariador.vehiculo')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
            },
        ),
    ]
