# Generated by Django 5.0.3 on 2024-05-23 13:13

import datetime
import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import secretariador.functions
import secretariador.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carga', '0031_provincia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comisionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comisionado_nombres', models.CharField(max_length=120, verbose_name='Nombres')),
                ('comisionado_apellidos', models.CharField(max_length=120, verbose_name='Apellidos')),
                ('comisionado_abreviatura', models.CharField(help_text='(Sr., Sra., Dr., Dra., Etc.)', max_length=10, verbose_name='Abreviatura')),
                ('comisionado_sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo')),
                ('comisionado_dni', models.DecimalField(decimal_places=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0)], verbose_name='DNI:')),
                ('comisionado_cuit', models.CharField(max_length=13, validators=[secretariador.functions.CuitValidator()], verbose_name='CUIT')),
                ('comisionado_nombreyapellido', models.GeneratedField(db_persist=True, expression=secretariador.models.ConcatOp('comisionado_apellidos', models.Value(', '), 'comisionado_nombres'), output_field=models.TextField())),
            ],
            options={
                'verbose_name': 'Comisionado',
                'verbose_name_plural': 'Comisionados',
                'ordering': ('comisionado_apellidos',),
            },
        ),
        migrations.CreateModel(
            name='InstrumentosLegalesDecretos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrumentolegaldecretos_tipo', models.CharField(choices=[('N', 'Decreto Nacional'), ('P', 'Decreto Provincial')], default='P', max_length=1, verbose_name='Tipo')),
                ('instrumentolegaldecretos_numero', models.CharField(max_length=7, verbose_name='Número')),
                ('instrumentolegaldecretos_ano', models.CharField(max_length=5, verbose_name='Año')),
                ('instrumentolegaldecretos_descripcion', models.CharField(default='Escala de viáticos', max_length=600, verbose_name='Descripción')),
                ('instrumentolegaldecretos', models.FileField(blank=True, max_length=500, null=True, upload_to=secretariador.models.generate_name_decretos, validators=[secretariador.functions.FileValidator(content_types='application/pdf', max_size=14680064, min_size=None)])),
                ('instrumentolegaldecretos_str', models.GeneratedField(db_persist=True, expression=secretariador.models.ConcatOp('instrumentolegaldecretos_numero', models.Value(' - '), 'instrumentolegaldecretos_ano', models.Value(' - '), 'instrumentolegaldecretos_tipo'), output_field=models.TextField())),
            ],
            options={
                'verbose_name': 'Instrumento Legal(Decreto)',
                'verbose_name_plural': 'Instrumentos Legales(Decretos)',
                'get_latest_by': ['instrumentolegaldecretos_ano', 'instrumentolegaldecretos_numero'],
            },
        ),
        migrations.CreateModel(
            name='InstrumentosLegalesResoluciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrumentolegalresoluciones_tipo', models.CharField(choices=[('P', 'Resolución de Presidencia'), ('D', 'Resolución de Directorio')], default='P', max_length=1, verbose_name='Tipo')),
                ('instrumentolegalresoluciones_numero', models.CharField(max_length=7, verbose_name='Número')),
                ('instrumentolegalresoluciones_ano', models.CharField(max_length=5, verbose_name='Año')),
                ('instrumentolegalresoluciones_descripcion', models.CharField(default='', max_length=600, verbose_name='Descripción')),
                ('instrumentolegalresoluciones', models.FileField(blank=True, max_length=500, null=True, upload_to=secretariador.models.generate_name_resoluciones, validators=[secretariador.functions.FileValidator(content_types='application/pdf', max_size=14680064, min_size=None)])),
                ('instrumentolegalresoluciones_str', models.GeneratedField(db_persist=True, expression=secretariador.models.ConcatOp('instrumentolegalresoluciones_numero', models.Value(' - '), 'instrumentolegalresoluciones_ano', models.Value(' - '), 'instrumentolegalresoluciones_tipo'), output_field=models.TextField())),
            ],
            options={
                'verbose_name': 'Instrumento Legal(Resolución)',
                'verbose_name_plural': 'Instrumentos Legales(Resoluciones)',
            },
        ),
        migrations.CreateModel(
            name='MontoViaticoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montoviaticodiario_estrato_uno_interior', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Viatico diario Estrato I dentro de la Provincia')),
                ('montoviaticodiario_estrato_dos_interior', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Viatico diario Estrato II dentro de la Provincia')),
                ('montoviaticodiario_estrato_tres_interior', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Viatico diario Estrato III dentro de la Provincia')),
                ('montoviaticodiario_estrato_cuatro_interior', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Viatico diario Estrato IV dentro de la Provincia')),
                ('montoviaticodiario_estrato_uno_exterior', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Viatico diario Estrato I fuera de la Provincia')),
                ('montoviaticodiario_estrato_dos_exterior', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Viatico diario Estrato II fuera de la Provincia')),
                ('montoviaticodiario_estrato_tres_exterior', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Viatico diario Estrato III fuera de la Provincia')),
                ('montoviaticodiario_estrato_cuatro_exterior', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Viatico diario Estrato IV fuera de la Provincia')),
            ],
            options={
                'verbose_name': 'Monto diario de Viático',
                'verbose_name_plural': 'Monto diario de Viáticos',
            },
        ),
        migrations.CreateModel(
            name='Organigrama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organigrama_cargo', models.CharField(max_length=120, verbose_name='Cargo')),
                ('organigrama_escalafon', models.DecimalField(decimal_places=0, default=2, max_digits=1, verbose_name='Escalafón')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitud_actuacion', models.CharField(max_length=18, verbose_name='Actuación')),
                ('solicitud_fecha_desde', models.DateField(verbose_name='Fecha Inicio')),
                ('solicitud_fecha_hasta', models.DateField(verbose_name='Fecha Regreso')),
                ('solicitud_tareas', models.TextField(help_text='... a fin de #Texto ingresado en el formulario#', verbose_name='Tareas a Realizar')),
                ('solicitud_dia_inhabil', models.BooleanField(help_text='Tildar si es un diá de no laboral', verbose_name='Dia Inhábil')),
                ('solicitud_viaticos_total', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('solicitud_fecha_hasta'), '-', models.F('solicitud_fecha_desde')), '+', models.Value(datetime.timedelta(days=1))), output_field=models.DurationField())),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiculo_caracter', models.CharField(choices=[('E', 'Empresa'), ('O', 'Oficial'), ('P', 'Particular')], default='O', max_length=1, verbose_name='Vehiculo Designación')),
                ('vehiculo_modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('vehiculo_patente', models.CharField(max_length=9, verbose_name='Patente')),
                ('vehiculo_poliza', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Póliza')),
                ('vehiculo_str', models.GeneratedField(db_persist=True, expression=secretariador.models.ConcatOp('vehiculo_modelo', models.Value(' - '), 'vehiculo_patente'), output_field=models.TextField())),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
            },
        ),
        migrations.CreateModel(
            name='ComisionadoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comisionadosolicitud_colaborador', models.BooleanField(verbose_name='Es colaborador?')),
                ('comisionadosolicitud_chofer', models.BooleanField(verbose_name='Es Chofer?')),
                ('comisionadosolicitud_combustible', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Combustible')),
                ('comisionadosolicitud_gastos', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Gastos')),
                ('comisionadosolicitud_nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariador.comisionado')),
            ],
            options={
                'verbose_name': 'Comisionado Solicitud',
                'verbose_name_plural': 'Comisionado Solicitudes',
            },
        ),
        migrations.AddConstraint(
            model_name='instrumentoslegalesdecretos',
            constraint=models.UniqueConstraint(fields=('instrumentolegaldecretos_tipo', 'instrumentolegaldecretos_numero', 'instrumentolegaldecretos_ano'), name='unique_decretos_1'),
        ),
        migrations.AddConstraint(
            model_name='instrumentoslegalesresoluciones',
            constraint=models.UniqueConstraint(fields=('instrumentolegalresoluciones_tipo', 'instrumentolegalresoluciones_numero', 'instrumentolegalresoluciones_ano'), name='unique_resolucion_1'),
        ),
        migrations.AddField(
            model_name='montoviaticodiario',
            name='montoviaticodiario_decreto_reglamentario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariador.instrumentoslegalesdecretos'),
        ),
        migrations.AddField(
            model_name='comisionado',
            name='comisionado_cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariador.organigrama'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='solicitud_decreto_viaticos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariador.montoviaticodiario'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='solicitud_localidades',
            field=models.ManyToManyField(to='carga.localidad'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='solicitud_provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.provincia'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='solicitud_resolucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secretariador.instrumentoslegalesresoluciones', verbose_name='Resolución Aprobada'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='solicitud_solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariador.comisionado'),
        ),
        migrations.AddField(
            model_name='comisionadosolicitud',
            name='comisionadosolicitud_foreign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariador.solicitud'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='vehiculo_poliza_aseguradora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carga.aseguradora'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='solicitud_vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariador.vehiculo'),
        ),
    ]
