# Generated by Django 5.2.10 on 2026-06-06 13:04

import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comisionado',
            name='comisionado_uuid',
            field=models.UUIDField(default=uuid_utils.compat.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='comisionadosolicitud',
            name='comisionadosolicitud_uuid',
            field=models.UUIDField(default=uuid_utils.compat.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='historicalcomisionado',
            name='comisionado_uuid',
            field=models.UUIDField(default=uuid_utils.compat.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='historicalcomisionadosolicitud',
            name='comisionadosolicitud_uuid',
            field=models.UUIDField(default=uuid_utils.compat.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='historicalincorporacion',
            name='incorporacion_uuid',
            field=models.UUIDField(default=uuid_utils.compat.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='historicalinstrumentoslegalesdecretos',
            name='instrumentolegaldecretos_uuid',
            field=models.UUIDField(default=uuid_utils.compat.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='historicalinstrumentoslegalesmemorandum',
            name='instrumentolegalmemorandum_uuid',
            field=models.UUIDField(default=uuid_utils.compat.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='historicalinstrumentoslegalesresoluciones',
            name='instrumentolegalresoluciones_uuid',
            field=models.UUIDField(default=uuid_utils.compat.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='historicalinstrumentoslegalesresolucionesdirectorio',
            name='instrumentolegalresolucionesdirectorio_uuid',
            field=models.UUIDField(default=uuid_utils.compat.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='historicalmontoviaticodiario',
            name='montoviaticodiario_uuid',
            field=models.UUIDField(default=uuid_utils.compat.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='historicalorganigrama',
            name='organigrama_uuid',
            field=models.UUIDField(default=uuid_utils.compat.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='historicalsolicitud',
            name='solicitud_uuid',
            field=models.UUIDField(default=uuid_utils.compat.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='historicalvehiculo',
            name='vehiculo_uuid',
            field=models.UUIDField(default=uuid_utils.compat.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='incorporacion',
            name='incorporacion_uuid',
            field=models.UUIDField(default=uuid_utils.compat.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='instrumentoslegalesdecretos',
            name='instrumentolegaldecretos_uuid',
            field=models.UUIDField(default=uuid_utils.compat.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='instrumentoslegalesmemorandum',
            name='instrumentolegalmemorandum_uuid',
            field=models.UUIDField(default=uuid_utils.compat.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='instrumentoslegalesresoluciones',
            name='instrumentolegalresoluciones_uuid',
            field=models.UUIDField(default=uuid_utils.compat.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='instrumentoslegalesresolucionesdirectorio',
            name='instrumentolegalresolucionesdirectorio_uuid',
            field=models.UUIDField(default=uuid_utils.compat.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='montoviaticodiario',
            name='montoviaticodiario_uuid',
            field=models.UUIDField(default=uuid_utils.compat.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='organigrama',
            name='organigrama_uuid',
            field=models.UUIDField(default=uuid_utils.compat.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='solicitud_uuid',
            field=models.UUIDField(default=uuid_utils.compat.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='vehiculo_uuid',
            field=models.UUIDField(default=uuid_utils.compat.uuid7, editable=False),
        ),
    ]
