# Generated by Django 5.0.3 on 2024-05-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0031_provincia'),
        ('secretariador', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='solicitud',
            constraint=models.UniqueConstraint(fields=('solicitud_actuacion',), name='unique_solicitud_1'),
        ),
    ]
