# Generated by Django 5.0.3 on 2024-05-31 12:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariador', '0002_solicitud_unique_solicitud_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentoslegalesdecretos',
            name='instrumentolegaldecretos_fecha_aprobacion',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Aprobación'),
        ),
        migrations.AddField(
            model_name='instrumentoslegalesresoluciones',
            name='instrumentolegalresoluciones_fecha_aprobacion',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Aprobación'),
        ),
        migrations.AlterField(
            model_name='comisionadosolicitud',
            name='comisionadosolicitud_foreign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secretariador.solicitud'),
        ),
        migrations.CreateModel(
            name='Incorporacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incorporacion_actuacion', models.CharField(max_length=18, verbose_name='Actuación')),
                ('incorporacion_resolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariador.instrumentoslegalesresoluciones', verbose_name='Resolución Aprobada')),
                ('incorporacion_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariador.comisionado')),
                ('incorporacion_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretariador.solicitud')),
            ],
            options={
                'verbose_name': 'Incorporación',
                'verbose_name_plural': 'Incorporaciones',
            },
        ),
        migrations.AddField(
            model_name='comisionadosolicitud',
            name='comisionadosolicitud_incorporacion_foreign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secretariador.incorporacion'),
        ),
        migrations.AddConstraint(
            model_name='incorporacion',
            constraint=models.UniqueConstraint(fields=('incorporacion_solicitud',), name='unique_incorporacion_1'),
        ),
    ]
