# Generated by Django 6.0.6 on 2026-06-17 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretariador', '0002_comisionado_comisionado_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comisionado',
            name='comisionado_cargo_decreto',
        ),
        migrations.RemoveField(
            model_name='comisionado',
            name='comisionado_cargo_interno',
        ),
        migrations.RemoveField(
            model_name='historicalcomisionado',
            name='comisionado_cargo_decreto',
        ),
        migrations.RemoveField(
            model_name='historicalcomisionado',
            name='comisionado_cargo_interno',
        ),
    ]
