# Generated by Django 5.0.3 on 2024-06-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0031_provincia'),
        ('secretariador', '0003_instrumentoslegalesdecretos_instrumentolegaldecretos_fecha_aprobacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organigrama',
            options={'verbose_name': 'Organigrama', 'verbose_name_plural': 'Organigramas'},
        ),
        migrations.AddConstraint(
            model_name='comisionado',
            constraint=models.UniqueConstraint(fields=('comisionado_nombres', 'comisionado_apellidos', 'comisionado_dni'), name='unique_comisionado_1'),
        ),
        migrations.AddConstraint(
            model_name='vehiculo',
            constraint=models.UniqueConstraint(fields=('vehiculo_modelo', 'vehiculo_patente'), name='unique_vehiculo_1'),
        ),
    ]
