# Generated by Django 5.0.3 on 2024-06-05 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0031_provincia'),
        ('secretariador', '0004_alter_organigrama_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comisionadosolicitud',
            name='comisionadosolicitud_pasaje',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Pasajes'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='solicitud_aereo',
            field=models.BooleanField(blank=True, help_text='Tildar si es viaje aereo', null=True, verbose_name='Aereo'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='solicitud_ciudad',
            field=models.CharField(blank=True, help_text='... en la ciudad de #Texto ingresado en el formulario#', max_length=200, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='solicitud_localidades',
            field=models.ManyToManyField(blank=True, to='carga.localidad'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='solicitud_vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secretariador.vehiculo'),
        ),
    ]
