# Generated by Django 5.0.3 on 2024-06-24 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariador', '0005_comisionadosolicitud_comisionadosolicitud_pasaje_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrumentoslegalesdecretos',
            options={'get_latest_by': ['instrumentolegaldecretos_ano', 'instrumentolegaldecretos_numero'], 'ordering': ['-instrumentolegaldecretos_ano', '-instrumentolegaldecretos_numero'], 'verbose_name': 'Instrumento Legal(Decreto)', 'verbose_name_plural': 'Instrumentos Legales(Decretos)'},
        ),
        migrations.AlterModelOptions(
            name='instrumentoslegalesresoluciones',
            options={'ordering': ['-instrumentolegalresoluciones_ano', '-instrumentolegalresoluciones_numero'], 'verbose_name': 'Instrumento Legal(Resolución)', 'verbose_name_plural': 'Instrumentos Legales(Resoluciones)'},
        ),
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'ordering': ['vehiculo_modelo', 'vehiculo_patente'], 'verbose_name': 'Vehículo', 'verbose_name_plural': 'Vehículos'},
        ),
        migrations.RenameField(
            model_name='solicitud',
            old_name='solicitud_viaticos_total',
            new_name='solicitud_cantidad_de_dias',
        ),
        migrations.AlterField(
            model_name='incorporacion',
            name='incorporacion_resolucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secretariador.instrumentoslegalesresoluciones', verbose_name='Resolución Aprobada'),
        ),
    ]
