# Generated by Django 5.0.3 on 2024-06-25 13:31
# Manually added split_actuacion function.

import django.core.validators
from django.db import migrations, models
import secretariador.models

def split_actuacion(apps, schema_editor):
    """
    Split actuacion into solicitud_actuacion_ano and solicitud_actuacion_numero
    """
    Solicitud = apps.get_model('secretariador', 'solicitud')
    for actuacion in Solicitud.objects.all():
        actuacion_ano = actuacion.solicitud_actuacion.split('-')[1]
        actuacion_numero = actuacion.solicitud_actuacion.split('-')[2]
        actuacion.solicitud_actuacion_numero = actuacion_numero
        actuacion.solicitud_actuacion_ano = actuacion_ano
        actuacion.save()

class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0031_provincia'),
        ('secretariador', '0006_alter_instrumentoslegalesdecretos_options_and_more'),
    ]


    operations = [
        # Solicitud Model Changes.
        migrations.AddField(
            model_name='solicitud',
            name='solicitud_actuacion_ano',
            field=models.DecimalField(decimal_places=0, default=2024, max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Año Actuación'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='solicitud_actuacion_numero',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Solo el número de la actuación. Sin prefijo, sufijo o Año.', max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='N° Actuación'),
        ),
        migrations.RunPython(split_actuacion),
        migrations.AddConstraint(
            model_name='solicitud',
            constraint=models.UniqueConstraint(fields=('solicitud_actuacion_ano', 'solicitud_actuacion_numero'), name='unique_solicitud_2'),
        ),
        migrations.RemoveField(
            model_name="solicitud",
            name="solicitud_actuacion"
        ),
        migrations.AddField(
            model_name='solicitud',
            name='solicitud_actuacion',
            field=models.GeneratedField(db_persist=True, expression=secretariador.models.ConcatOp(models.Value('E10-'), 'solicitud_actuacion_ano', models.Value('-'), 'solicitud_actuacion_numero', models.Value('-AE')), output_field=models.TextField()),
        ),
        # Incorporacion Model Changes.
        migrations.AddField(
            model_name='incorporacion',
            name='incorporacion_actuacion_ano',
            field=models.DecimalField(decimal_places=0, default=2024, max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Año Actuación'),
        ),
        migrations.AddField(
            model_name='incorporacion',
            name='incorporacion_actuacion_numero',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Solo el número de la actuación. Sin prefijo, sufijo o Año.', max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='N° Actuación'),
        ),
        migrations.AddConstraint(
            model_name='incorporacion',
            constraint=models.UniqueConstraint(fields=('incorporacion_actuacion_ano', 'incorporacion_actuacion_numero'), name='unique_incorporacion_2'),
        ),
        migrations.RemoveField(
            model_name="incorporacion",
            name="incorporacion_actuacion"
        ),
        migrations.AddField(
            model_name='incorporacion',
            name='incorporacion_actuacion',
            field=models.GeneratedField(db_persist=True, expression=secretariador.models.ConcatOp(models.Value('E10-'), 'incorporacion_actuacion_ano', models.Value('-'), 'incorporacion_actuacion_numero', models.Value('-AE')), output_field=models.TextField()),
        ),
    ]
