# Generated by Django 5.0.3 on 2024-07-02 13:23

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('secretariador', '0007_solicitud_solicitud_actuacion_ano_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comisionadosolicitud',
            name='comisionadosolicitud_cantidad_de_dias',
            field=models.DurationField(blank=True, editable=False, null=True, verbose_name='Días'),
        ),
        migrations.AddField(
            model_name='comisionadosolicitud',
            name='comisionadosolicitud_viatico_computado',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=12, null=True, verbose_name='Viatico Computado'),
        ),
        migrations.AddField(
            model_name='comisionadosolicitud',
            name='comisionadosolicitud_viatico_diario',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=12, null=True, verbose_name='Viatico Diario'),
        ),
        migrations.AddField(
            model_name='comisionadosolicitud',
            name='comisionadosolicitud_viatico_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=12, null=True, verbose_name='Viatico Total'),
        ),
    ]
