# Generated by Django 6.0.6 on 2026-07-07 14:42

from django.db import migrations, models


def copy_directorio_into_resoluciones(apps, schema_editor):
    """
    Reverse of the historical res_directorio.py management command: copies every
    InstrumentosLegalesResolucionesDirectorio row back into InstrumentosLegalesResoluciones
    (tipo="D") now that the latter's unique constraint also covers "acta". The FileField
    path is copied as-is since both models share the same generate_name_resoluciones
    upload_to convention, so no physical file needs to move.
    """
    Directorio = apps.get_model('secretariador', 'InstrumentosLegalesResolucionesDirectorio')
    Resoluciones = apps.get_model('secretariador', 'InstrumentosLegalesResoluciones')

    for d in Directorio.objects.all():
        Resoluciones.objects.create(
            instrumentolegalresoluciones_tipo=d.instrumentolegalresolucionesdirectorio_tipo,
            instrumentolegalresoluciones_numero=d.instrumentolegalresolucionesdirectorio_numero,
            instrumentolegalresoluciones_acta=d.instrumentolegalresolucionesdirectorio_acta,
            instrumentolegalresoluciones_ano=d.instrumentolegalresolucionesdirectorio_ano,
            instrumentolegalresoluciones_fecha_aprobacion=d.instrumentolegalresolucionesdirectorio_fecha_aprobacion,
            instrumentolegalresoluciones_descripcion=d.instrumentolegalresolucionesdirectorio_descripcion,
            instrumentolegalresoluciones=(d.instrumentolegalresolucionesdirectorio.name or "") if d.instrumentolegalresolucionesdirectorio else "",
            instrumentolegalresoluciones_autocarga=d.instrumentolegalresolucionesdirectorio_autocarga,
            instrumentolegalresoluciones_document=d.instrumentolegalresolucionesdirectorio_document,
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('secretariador', '0007_delete_comisionado'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='instrumentoslegalesresoluciones',
            name='unique_resolucion_1',
        ),
        migrations.AddConstraint(
            model_name='instrumentoslegalesresoluciones',
            constraint=models.UniqueConstraint(fields=('instrumentolegalresoluciones_tipo', 'instrumentolegalresoluciones_numero', 'instrumentolegalresoluciones_acta', 'instrumentolegalresoluciones_ano'), name='unique_resolucion_1'),
        ),
        migrations.RunPython(copy_directorio_into_resoluciones, noop_reverse),
        migrations.RemoveField(
            model_name='historicalinstrumentoslegalesresolucionesdirectorio',
            name='history_user',
        ),
        migrations.RemoveConstraint(
            model_name='instrumentoslegalesresolucionesdirectorio',
            name='unique_resolucion_directorio_1',
        ),
        migrations.DeleteModel(
            name='InstrumentosLegalesResolucionesDirectorio',
        ),
        migrations.DeleteModel(
            name='HistoricalInstrumentosLegalesResolucionesDirectorio',
        ),
    ]
