# Generated by Django 6.0.6 on 2026-07-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariador', '0008_merge_resoluciones_directorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinstrumentoslegalesresoluciones',
            name='instrumentolegalresoluciones_accion',
            field=models.CharField(blank=True, choices=[('ADJ', 'Adjudicatoria'), ('APR', 'Aprobatoria'), ('RAT', 'Ratificatoria'), ('AMP', 'Ampliatoria')], max_length=3, null=True, verbose_name='Acción'),
        ),
        migrations.AddField(
            model_name='historicalinstrumentoslegalesresoluciones',
            name='instrumentolegalresoluciones_ad_referendum',
            field=models.BooleanField(default=False, verbose_name='Ad referendum'),
        ),
        migrations.AddField(
            model_name='historicalinstrumentoslegalesresoluciones',
            name='instrumentolegalresoluciones_estado_escaneo',
            field=models.CharField(choices=[('N', 'Normal'), ('H', 'Horrible')], default='N', max_length=1, verbose_name='Estado del escaneo'),
        ),
        migrations.AddField(
            model_name='instrumentoslegalesresoluciones',
            name='instrumentolegalresoluciones_accion',
            field=models.CharField(blank=True, choices=[('ADJ', 'Adjudicatoria'), ('APR', 'Aprobatoria'), ('RAT', 'Ratificatoria'), ('AMP', 'Ampliatoria')], max_length=3, null=True, verbose_name='Acción'),
        ),
        migrations.AddField(
            model_name='instrumentoslegalesresoluciones',
            name='instrumentolegalresoluciones_ad_referendum',
            field=models.BooleanField(default=False, verbose_name='Ad referendum'),
        ),
        migrations.AddField(
            model_name='instrumentoslegalesresoluciones',
            name='instrumentolegalresoluciones_estado_escaneo',
            field=models.CharField(choices=[('N', 'Normal'), ('H', 'Horrible')], default='N', max_length=1, verbose_name='Estado del escaneo'),
        ),
    ]
