# Generated by Django 6.0.6 on 2026-07-14 23:06

import secretariador.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariador', '0009_historicalinstrumentoslegalesresoluciones_instrumentolegalresoluciones_accion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinstrumentoslegalesresoluciones',
            name='instrumentolegalresoluciones_str',
        ),
        migrations.AddField(
            model_name='historicalinstrumentoslegalesresoluciones',
            name='instrumentolegalresoluciones_str',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(instrumentolegalresoluciones_tipo='D', then=secretariador.models.ConcatOp('instrumentolegalresoluciones_numero', models.Value('-'), 'instrumentolegalresoluciones_acta', models.Value('-'), 'instrumentolegalresoluciones_ano')), default=secretariador.models.ConcatOp('instrumentolegalresoluciones_numero', models.Value('-'), 'instrumentolegalresoluciones_ano'), output_field=models.TextField()), output_field=models.TextField()),
        ),
        migrations.RemoveField(
            model_name='instrumentoslegalesresoluciones',
            name='instrumentolegalresoluciones_str',
        ),
        migrations.AddField(
            model_name='instrumentoslegalesresoluciones',
            name='instrumentolegalresoluciones_str',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(instrumentolegalresoluciones_tipo='D', then=secretariador.models.ConcatOp('instrumentolegalresoluciones_numero', models.Value('-'), 'instrumentolegalresoluciones_acta', models.Value('-'), 'instrumentolegalresoluciones_ano')), default=secretariador.models.ConcatOp('instrumentolegalresoluciones_numero', models.Value('-'), 'instrumentolegalresoluciones_ano'), output_field=models.TextField()), output_field=models.TextField()),
        ),
    ]
