# Generated by Django 6.0.6 on 2026-07-16 16:37

import core.validators
import django.db.models.deletion
import simple_history.models
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariador', '0010_resolucion_str_directorio_format'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EncabezadoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encabezadodocumento_archivo', models.FileField(max_length=500, upload_to='encabezados/', validators=[core.validators.FileValidator(content_types=('application/vnd.openxmlformats-officedocument.wordprocessingml.document',), max_size=14680064, min_size=None)], verbose_name='Archivo (.docx)')),
                ('encabezadodocumento_creado', models.DateTimeField(auto_now_add=True)),
                ('encabezadodocumento_uuid', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False)),
                ('encabezadodocumento_subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Encabezado de Documento',
                'verbose_name_plural': 'Encabezados de Documento',
                'ordering': ['-encabezadodocumento_creado'],
                'get_latest_by': ['encabezadodocumento_creado'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEncabezadoDocumento',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('encabezadodocumento_archivo', models.TextField(max_length=500, validators=[core.validators.FileValidator(content_types=('application/vnd.openxmlformats-officedocument.wordprocessingml.document',), max_size=14680064, min_size=None)], verbose_name='Archivo (.docx)')),
                ('encabezadodocumento_creado', models.DateTimeField(blank=True, editable=False)),
                ('encabezadodocumento_uuid', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('encabezadodocumento_subido_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Encabezado de Documento',
                'verbose_name_plural': 'historical Encabezados de Documento',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
