# Generated by Django 6.0.6 on 2026-07-27 13:44

import secretariador.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariador', '0011_encabezadodocumento_historicalencabezadodocumento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinstrumentoslegalesresoluciones',
            name='instrumentolegalresoluciones_numero_sgt',
        ),
        migrations.RemoveField(
            model_name='instrumentoslegalesresoluciones',
            name='instrumentolegalresoluciones_numero_sgt',
        ),
        migrations.AddField(
            model_name='historicalinstrumentoslegalesresoluciones',
            name='instrumentolegalresoluciones_numero_sgt',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(instrumentolegalresoluciones_tipo='D', then=secretariador.models.ConcatOp(models.Value('RES-'), 'instrumentolegalresoluciones_ano', models.Value('-'), 'instrumentolegalresoluciones_numero', models.Value('-10-'), 'instrumentolegalresoluciones_acta')), default=secretariador.models.ConcatOp(models.Value('RES-'), 'instrumentolegalresoluciones_ano', models.Value('-'), 'instrumentolegalresoluciones_numero', models.Value('-10-1')), output_field=models.CharField(max_length=25)), output_field=models.CharField(max_length=25)),
        ),
        migrations.AddField(
            model_name='instrumentoslegalesresoluciones',
            name='instrumentolegalresoluciones_numero_sgt',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(instrumentolegalresoluciones_tipo='D', then=secretariador.models.ConcatOp(models.Value('RES-'), 'instrumentolegalresoluciones_ano', models.Value('-'), 'instrumentolegalresoluciones_numero', models.Value('-10-'), 'instrumentolegalresoluciones_acta')), default=secretariador.models.ConcatOp(models.Value('RES-'), 'instrumentolegalresoluciones_ano', models.Value('-'), 'instrumentolegalresoluciones_numero', models.Value('-10-1')), output_field=models.CharField(max_length=25)), output_field=models.CharField(max_length=25)),
        ),
    ]
