# Generated by Django 6.0.6 on 2026-08-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariador', '0012_fix_numero_sgt_directorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinstrumentoslegalesresoluciones',
            name='instrumentolegalresoluciones_crc32',
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True, verbose_name='CRC-32'),
        ),
        migrations.AddField(
            model_name='instrumentoslegalesresoluciones',
            name='instrumentolegalresoluciones_crc32',
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True, verbose_name='CRC-32'),
        ),
    ]
