# Generated by Django 6.0.6 on 2026-08-03 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretariador', '0013_historicalinstrumentoslegalesresoluciones_instrumentolegalresoluciones_crc32_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinstrumentoslegalesresoluciones',
            name='instrumentolegalresoluciones_crc32',
        ),
        migrations.RemoveField(
            model_name='instrumentoslegalesresoluciones',
            name='instrumentolegalresoluciones_crc32',
        ),
    ]
