# Generated by Django 5.0.3 on 2024-10-22 14:48

import django.utils.timezone
import secretariador.functions
import secretariador.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariador', '0013_instrumentoslegalesresoluciones_instrumentolegalresoluciones_autocarga_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentosLegalesMemorandum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrumentolegalmemorandum_tipo', models.CharField(choices=[('P', 'Presidencia'), ('D', 'Dirección General de Gestión Administrativa')], default='P', max_length=1, verbose_name='Tipo')),
                ('instrumentolegalmemorandum_numero', models.CharField(max_length=7, verbose_name='Número')),
                ('instrumentolegalmemorandum_ano', models.CharField(max_length=5, verbose_name='Año')),
                ('instrumentolegalmemorandum_fecha_aprobacion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Aprobación')),
                ('instrumentolegalmemorandum_descripcion', models.CharField(default='', max_length=600, verbose_name='Descripción')),
                ('instrumentolegalmemorandum', models.FileField(blank=True, max_length=500, null=True, upload_to=secretariador.models.generate_name_memorandum, validators=[secretariador.functions.FileValidator(content_types='application/pdf', max_size=14680064, min_size=None)])),
                ('instrumentolegalmemorandum_str', models.GeneratedField(db_persist=True, expression=secretariador.models.ConcatOp('instrumentolegalmemorandum_numero', models.Value(' - '), 'instrumentolegalmemorandum_ano', models.Value(' - '), 'instrumentolegalmemorandum_tipo'), output_field=models.TextField())),
                ('instrumentolegalmemorandum_autocarga', models.BooleanField(default=False, verbose_name='Memorandum importada sin intervención.')),
                ('instrumentolegalmemorandum_document', models.TextField(blank=True, null=True, verbose_name='Texto Extraído por OCR')),
            ],
            options={
                'verbose_name': 'Instrumento Legal(Memorandum)',
                'verbose_name_plural': 'Instrumentos Legales(Memorandums)',
                'ordering': ['-instrumentolegalmemorandum_ano', '-instrumentolegalmemorandum_numero'],
            },
        ),
        migrations.AddConstraint(
            model_name='instrumentoslegalesmemorandum',
            constraint=models.UniqueConstraint(fields=('instrumentolegalmemorandum_tipo', 'instrumentolegalmemorandum_numero', 'instrumentolegalmemorandum_ano'), name='unique_memorandum_1'),
        ),
    ]
