# Generated by Django 6.0.6 on 2026-08-03 21:39
# Reordenado a mano: Postgres no permite alterar el tipo de una columna de la
# que depende una GeneratedField ("cannot alter type of a column used by a
# generated column"), así que hay que sacar esas columnas generadas, alterar
# numero, y volver a crearlas -- mismo patrón que 0010/0012.

import django.db.models.functions.comparison
import secretariador.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariador', '0014_remove_historicalinstrumentoslegalesresoluciones_instrumentolegalresoluciones_crc32_and_more'),
    ]

    operations = [
        # -- Sacar las GeneratedField que dependen de *_numero --
        migrations.RemoveField(
            model_name='historicalinstrumentoslegalesdecretos',
            name='instrumentolegaldecretos_str',
        ),
        migrations.RemoveField(
            model_name='instrumentoslegalesdecretos',
            name='instrumentolegaldecretos_str',
        ),
        migrations.RemoveField(
            model_name='historicalinstrumentoslegalesmemorandum',
            name='instrumentolegalmemorandum_str',
        ),
        migrations.RemoveField(
            model_name='instrumentoslegalesmemorandum',
            name='instrumentolegalmemorandum_str',
        ),
        migrations.RemoveField(
            model_name='historicalinstrumentoslegalesresoluciones',
            name='instrumentolegalresoluciones_str',
        ),
        migrations.RemoveField(
            model_name='historicalinstrumentoslegalesresoluciones',
            name='instrumentolegalresoluciones_numero_sgt',
        ),
        migrations.RemoveField(
            model_name='instrumentoslegalesresoluciones',
            name='instrumentolegalresoluciones_str',
        ),
        migrations.RemoveField(
            model_name='instrumentoslegalesresoluciones',
            name='instrumentolegalresoluciones_numero_sgt',
        ),

        # -- Alterar los campos numero de CharField a PositiveIntegerField --
        migrations.AlterField(
            model_name='historicalinstrumentoslegalesdecretos',
            name='instrumentolegaldecretos_numero',
            field=models.PositiveIntegerField(verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='instrumentoslegalesdecretos',
            name='instrumentolegaldecretos_numero',
            field=models.PositiveIntegerField(verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='historicalinstrumentoslegalesmemorandum',
            name='instrumentolegalmemorandum_numero',
            field=models.PositiveIntegerField(verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='instrumentoslegalesmemorandum',
            name='instrumentolegalmemorandum_numero',
            field=models.PositiveIntegerField(verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='historicalinstrumentoslegalesresoluciones',
            name='instrumentolegalresoluciones_numero',
            field=models.PositiveIntegerField(verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='instrumentoslegalesresoluciones',
            name='instrumentolegalresoluciones_numero',
            field=models.PositiveIntegerField(verbose_name='Número'),
        ),

        # -- Volver a crear las GeneratedField, ahora casteando numero a texto --
        migrations.AddField(
            model_name='historicalinstrumentoslegalesdecretos',
            name='instrumentolegaldecretos_str',
            field=models.GeneratedField(db_persist=True, expression=secretariador.models.ConcatOp(django.db.models.functions.comparison.Cast('instrumentolegaldecretos_numero', output_field=models.TextField()), models.Value(' - '), 'instrumentolegaldecretos_ano', models.Value(' - '), 'instrumentolegaldecretos_tipo'), output_field=models.TextField()),
        ),
        migrations.AddField(
            model_name='instrumentoslegalesdecretos',
            name='instrumentolegaldecretos_str',
            field=models.GeneratedField(db_persist=True, expression=secretariador.models.ConcatOp(django.db.models.functions.comparison.Cast('instrumentolegaldecretos_numero', output_field=models.TextField()), models.Value(' - '), 'instrumentolegaldecretos_ano', models.Value(' - '), 'instrumentolegaldecretos_tipo'), output_field=models.TextField()),
        ),
        migrations.AddField(
            model_name='historicalinstrumentoslegalesmemorandum',
            name='instrumentolegalmemorandum_str',
            field=models.GeneratedField(db_persist=True, expression=secretariador.models.ConcatOp(django.db.models.functions.comparison.Cast('instrumentolegalmemorandum_numero', output_field=models.TextField()), models.Value(' - '), 'instrumentolegalmemorandum_ano', models.Value(' - '), 'instrumentolegalmemorandum_tipo'), output_field=models.TextField()),
        ),
        migrations.AddField(
            model_name='instrumentoslegalesmemorandum',
            name='instrumentolegalmemorandum_str',
            field=models.GeneratedField(db_persist=True, expression=secretariador.models.ConcatOp(django.db.models.functions.comparison.Cast('instrumentolegalmemorandum_numero', output_field=models.TextField()), models.Value(' - '), 'instrumentolegalmemorandum_ano', models.Value(' - '), 'instrumentolegalmemorandum_tipo'), output_field=models.TextField()),
        ),
        migrations.AddField(
            model_name='historicalinstrumentoslegalesresoluciones',
            name='instrumentolegalresoluciones_str',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(instrumentolegalresoluciones_tipo='D', then=secretariador.models.ConcatOp(django.db.models.functions.comparison.Cast('instrumentolegalresoluciones_numero', output_field=models.TextField()), models.Value('-'), 'instrumentolegalresoluciones_acta', models.Value('-'), 'instrumentolegalresoluciones_ano')), default=secretariador.models.ConcatOp(django.db.models.functions.comparison.Cast('instrumentolegalresoluciones_numero', output_field=models.TextField()), models.Value('-'), 'instrumentolegalresoluciones_ano'), output_field=models.TextField()), output_field=models.TextField()),
        ),
        migrations.AddField(
            model_name='historicalinstrumentoslegalesresoluciones',
            name='instrumentolegalresoluciones_numero_sgt',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(instrumentolegalresoluciones_tipo='D', then=secretariador.models.ConcatOp(models.Value('RES-'), 'instrumentolegalresoluciones_ano', models.Value('-'), django.db.models.functions.comparison.Cast('instrumentolegalresoluciones_numero', output_field=models.TextField()), models.Value('-10-'), 'instrumentolegalresoluciones_acta')), default=secretariador.models.ConcatOp(models.Value('RES-'), 'instrumentolegalresoluciones_ano', models.Value('-'), django.db.models.functions.comparison.Cast('instrumentolegalresoluciones_numero', output_field=models.TextField()), models.Value('-10-1')), output_field=models.CharField(max_length=25)), output_field=models.CharField(max_length=25)),
        ),
        migrations.AddField(
            model_name='instrumentoslegalesresoluciones',
            name='instrumentolegalresoluciones_str',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(instrumentolegalresoluciones_tipo='D', then=secretariador.models.ConcatOp(django.db.models.functions.comparison.Cast('instrumentolegalresoluciones_numero', output_field=models.TextField()), models.Value('-'), 'instrumentolegalresoluciones_acta', models.Value('-'), 'instrumentolegalresoluciones_ano')), default=secretariador.models.ConcatOp(django.db.models.functions.comparison.Cast('instrumentolegalresoluciones_numero', output_field=models.TextField()), models.Value('-'), 'instrumentolegalresoluciones_ano'), output_field=models.TextField()), output_field=models.TextField()),
        ),
        migrations.AddField(
            model_name='instrumentoslegalesresoluciones',
            name='instrumentolegalresoluciones_numero_sgt',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(instrumentolegalresoluciones_tipo='D', then=secretariador.models.ConcatOp(models.Value('RES-'), 'instrumentolegalresoluciones_ano', models.Value('-'), django.db.models.functions.comparison.Cast('instrumentolegalresoluciones_numero', output_field=models.TextField()), models.Value('-10-'), 'instrumentolegalresoluciones_acta')), default=secretariador.models.ConcatOp(models.Value('RES-'), 'instrumentolegalresoluciones_ano', models.Value('-'), django.db.models.functions.comparison.Cast('instrumentolegalresoluciones_numero', output_field=models.TextField()), models.Value('-10-1')), output_field=models.CharField(max_length=25)), output_field=models.CharField(max_length=25)),
        ),
    ]
