# Generated by Django 5.0.3 on 2024-10-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariador', '0014_instrumentoslegalesmemorandum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentoslegalesmemorandum',
            name='instrumentolegalmemorandum_autocarga',
            field=models.BooleanField(default=False, verbose_name='Memorandum importado sin intervención humana.'),
        ),
    ]
