# Generated by Django 6.0.6 on 2026-08-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariador', '0015_alter_historicalinstrumentoslegalesdecretos_instrumentolegaldecretos_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinstrumentoslegalesdecretos',
            name='instrumentolegaldecretos_establece_licencia_anual',
            field=models.BooleanField(default=False, help_text="Tildado automáticamente si el decreto establece un período de Licencia Anual Ordinaria. Se usa para acotar el desplegable de decretos al cargar una Licencia/Permiso de tipo 'Anual'.", verbose_name='Establece Licencia Anual'),
        ),
        migrations.AddField(
            model_name='historicalinstrumentoslegalesdecretos',
            name='instrumentolegaldecretos_establece_licencia_invierno',
            field=models.BooleanField(default=False, help_text="Tildado automáticamente si el decreto establece un período de Licencia Anual de Invierno. Se usa para acotar el desplegable de decretos al cargar una Licencia/Permiso de tipo 'Anual de Invierno'.", verbose_name='Establece Licencia de Invierno'),
        ),
        migrations.AddField(
            model_name='instrumentoslegalesdecretos',
            name='instrumentolegaldecretos_establece_licencia_anual',
            field=models.BooleanField(default=False, help_text="Tildado automáticamente si el decreto establece un período de Licencia Anual Ordinaria. Se usa para acotar el desplegable de decretos al cargar una Licencia/Permiso de tipo 'Anual'.", verbose_name='Establece Licencia Anual'),
        ),
        migrations.AddField(
            model_name='instrumentoslegalesdecretos',
            name='instrumentolegaldecretos_establece_licencia_invierno',
            field=models.BooleanField(default=False, help_text="Tildado automáticamente si el decreto establece un período de Licencia Anual de Invierno. Se usa para acotar el desplegable de decretos al cargar una Licencia/Permiso de tipo 'Anual de Invierno'.", verbose_name='Establece Licencia de Invierno'),
        ),
    ]
