# Generated by Django 6.0.6 on 2026-08-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariador', '0016_historicalinstrumentoslegalesdecretos_instrumentolegaldecretos_establece_licencia_anual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalincorporacion',
            name='incorporacion_texto_actuacion',
            field=models.JSONField(blank=True, help_text='Texto de los considerandos y artículos editado desde la web para la generación del documento. Si está vacío, se genera automáticamente.', null=True, verbose_name='Texto de la Resolución'),
        ),
        migrations.AddField(
            model_name='historicalsolicitud',
            name='solicitud_texto_actuacion',
            field=models.JSONField(blank=True, help_text='Texto de los considerandos y artículos editado desde la web para la generación del documento. Si está vacío, se genera automáticamente.', null=True, verbose_name='Texto de la Resolución'),
        ),
        migrations.AddField(
            model_name='incorporacion',
            name='incorporacion_texto_actuacion',
            field=models.JSONField(blank=True, help_text='Texto de los considerandos y artículos editado desde la web para la generación del documento. Si está vacío, se genera automáticamente.', null=True, verbose_name='Texto de la Resolución'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='solicitud_texto_actuacion',
            field=models.JSONField(blank=True, help_text='Texto de los considerandos y artículos editado desde la web para la generación del documento. Si está vacío, se genera automáticamente.', null=True, verbose_name='Texto de la Resolución'),
        ),
    ]
