# Generated by Django 5.0.3 on 2025-05-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariador', '0016_instrumentoslegalesresoluciones_instrumentolegalresoluciones_acta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comisionado',
            name='comisionado_personal_transitorio',
            field=models.BooleanField(default=False, verbose_name='Personal Transitorio'),
        ),
    ]
