# Generated by Django 6.0.6 on 2026-08-14 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizador', '0024_comisionadoexterno_historicalcomisionadoexterno'),
        ('secretariador', '0017_historicalincorporacion_incorporacion_texto_actuacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comisionadosolicitud',
            name='comisionadosolicitud_externo',
            field=models.ForeignKey(blank=True, help_text='Persona externa al organismo. Exactamente uno de Agente/Externo debe estar cargado.', null=True, on_delete=django.db.models.deletion.CASCADE, to='personalizador.comisionadoexterno'),
        ),
        migrations.AddField(
            model_name='historicalcomisionadosolicitud',
            name='comisionadosolicitud_externo',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Persona externa al organismo. Exactamente uno de Agente/Externo debe estar cargado.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personalizador.comisionadoexterno'),
        ),
        migrations.AlterField(
            model_name='comisionadosolicitud',
            name='comisionadosolicitud_nombre',
            field=models.ForeignKey(blank=True, help_text='Agente del organismo. Exactamente uno de Agente/Externo debe estar cargado.', null=True, on_delete=django.db.models.deletion.CASCADE, to='personalizador.agente'),
        ),
        migrations.AlterField(
            model_name='historicalcomisionadosolicitud',
            name='comisionadosolicitud_nombre',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Agente del organismo. Exactamente uno de Agente/Externo debe estar cargado.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personalizador.agente'),
        ),
        migrations.AddConstraint(
            model_name='comisionadosolicitud',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('comisionadosolicitud_externo__isnull', True), ('comisionadosolicitud_nombre__isnull', False)), models.Q(('comisionadosolicitud_externo__isnull', False), ('comisionadosolicitud_nombre__isnull', True)), _connector='OR'), name='comisionadosolicitud_agente_xor_externo'),
        ),
    ]
