# Generated by Django 5.0.3 on 2025-05-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariador', '0017_comisionado_comisionado_personal_transitorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='comisionado',
            name='comisionado_personal_de_gabinete',
            field=models.BooleanField(default=False, verbose_name='Personal de Gabinete'),
        ),
    ]
