# Generated by Django 6.0.8 on 2026-08-18 16:04

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariador', '0018_comisionadosolicitud_comisionadosolicitud_externo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglasViatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reglas_gabinete_cobra_viatico', models.BooleanField(default=False, verbose_name='Personal de gabinete cobra viático')),
                ('reglas_autoridades_cobra_viatico_chaco', models.BooleanField(default=False, verbose_name='Autoridades (Directorio) cobran viático dentro de Chaco')),
                ('reglas_autoridades_escalafon', models.PositiveSmallIntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV')], default=4, verbose_name='Escalafón de autoridades (Directorio)')),
                ('reglas_escalafon_unico_habilitado', models.BooleanField(default=False, verbose_name='Forzar un único escalafón para todos')),
                ('reglas_escalafon_unico_valor', models.PositiveSmallIntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV')], default=2, verbose_name='Escalafón único')),
                ('reglas_escalafon_default_externos', models.PositiveSmallIntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV')], default=2, verbose_name='Escalafón por defecto para comisionados externos')),
            ],
            options={
                'verbose_name': 'Reglas de Cálculo de Viáticos',
                'verbose_name_plural': 'Reglas de Cálculo de Viáticos',
            },
        ),
        migrations.CreateModel(
            name='HistoricalReglasViatico',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('reglas_gabinete_cobra_viatico', models.BooleanField(default=False, verbose_name='Personal de gabinete cobra viático')),
                ('reglas_autoridades_cobra_viatico_chaco', models.BooleanField(default=False, verbose_name='Autoridades (Directorio) cobran viático dentro de Chaco')),
                ('reglas_autoridades_escalafon', models.PositiveSmallIntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV')], default=4, verbose_name='Escalafón de autoridades (Directorio)')),
                ('reglas_escalafon_unico_habilitado', models.BooleanField(default=False, verbose_name='Forzar un único escalafón para todos')),
                ('reglas_escalafon_unico_valor', models.PositiveSmallIntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV')], default=2, verbose_name='Escalafón único')),
                ('reglas_escalafon_default_externos', models.PositiveSmallIntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV')], default=2, verbose_name='Escalafón por defecto para comisionados externos')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Reglas de Cálculo de Viáticos',
                'verbose_name_plural': 'historical Reglas de Cálculo de Viáticos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
