# Generated by Django 5.0.3 on 2025-05-27 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0032_alter_aseguradora_options_alter_empresa_options'),
        ('secretariador', '0019_alter_montoviaticodiario_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='vechiculo_modelo',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='vehiculo_n_chasis',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Chasis'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='vehiculo_n_motor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Motor'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='vehiculo_titular_agente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secretariador.comisionado'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='vehiculo_titular_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carga.empresa'),
        ),
    ]
