# Generated by Django 6.0.8 on 2026-08-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariador', '0019_reglasviatico_historicalreglasviatico'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreglasviatico',
            name='reglas_externos_cobra_viatico',
            field=models.BooleanField(default=True, verbose_name='Comisionados externos cobran viático'),
        ),
        migrations.AddField(
            model_name='reglasviatico',
            name='reglas_externos_cobra_viatico',
            field=models.BooleanField(default=True, verbose_name='Comisionados externos cobran viático'),
        ),
    ]
