# Generated by Django 5.0.3 on 2025-05-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariador', '0020_vehiculo_vechiculo_modelo_vehiculo_vehiculo_n_chasis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='vechiculo_modelo',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='vechiculo_modelo_ano',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Año del Modelo'),
        ),
    ]
