# Generated by Django 6.0.8 on 2026-08-21 13:43

import core.validators
import secretariador.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariador', '0020_historicalreglasviatico_reglas_externos_cobra_viatico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinstrumentoslegalesdecretos',
            name='instrumentolegaldecretos',
            field=models.TextField(blank=True, max_length=500, null=True, validators=[core.validators.FileValidator(content_types=('application/pdf',), max_size=14680064, min_size=None)]),
        ),
        migrations.AlterField(
            model_name='historicalinstrumentoslegalesmemorandum',
            name='instrumentolegalmemorandum',
            field=models.TextField(blank=True, max_length=500, null=True, validators=[core.validators.FileValidator(content_types=('application/pdf',), max_size=14680064, min_size=None)]),
        ),
        migrations.AlterField(
            model_name='historicalinstrumentoslegalesresoluciones',
            name='instrumentolegalresoluciones',
            field=models.TextField(blank=True, max_length=500, null=True, validators=[core.validators.FileValidator(content_types=('application/pdf',), max_size=14680064, min_size=None)]),
        ),
        migrations.AlterField(
            model_name='instrumentoslegalesdecretos',
            name='instrumentolegaldecretos',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=secretariador.models.generate_name_decretos, validators=[core.validators.FileValidator(content_types=('application/pdf',), max_size=14680064, min_size=None)]),
        ),
        migrations.AlterField(
            model_name='instrumentoslegalesmemorandum',
            name='instrumentolegalmemorandum',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=secretariador.models.generate_name_memorandum, validators=[core.validators.FileValidator(content_types=('application/pdf',), max_size=14680064, min_size=None)]),
        ),
        migrations.AlterField(
            model_name='instrumentoslegalesresoluciones',
            name='instrumentolegalresoluciones',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=secretariador.models.generate_name_resoluciones, validators=[core.validators.FileValidator(content_types=('application/pdf',), max_size=14680064, min_size=None)]),
        ),
    ]
