# Generated by Django 6.0.8 on 2026-08-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariador', '0021_alter_historicalinstrumentoslegalesdecretos_instrumentolegaldecretos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinstrumentoslegalesdecretos',
            name='instrumentolegaldecretos_document',
            field=models.TextField(blank=True, null=True, verbose_name='Texto Extraído por OCR'),
        ),
        migrations.AddField(
            model_name='instrumentoslegalesdecretos',
            name='instrumentolegaldecretos_document',
            field=models.TextField(blank=True, null=True, verbose_name='Texto Extraído por OCR'),
        ),
    ]
