# Generated by Django 5.0.3 on 2025-05-27 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretariador', '0021_remove_vehiculo_vechiculo_modelo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='vechiculo_modelo_ano',
            new_name='vehiculo_modelo_ano',
        ),
    ]
