# Generated by Django 6.0.8 on 2026-09-24 16:51

import django.db.models.deletion
import simple_history.models
from django.db import migrations, models

from core.history import m2m_baseline


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0056_historicalfojademedicion_foja_inspector_and_more'),
        ('secretariador', '0022_historicalinstrumentoslegalesdecretos_instrumentolegaldecretos_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSolicitud_solicitud_localidades',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='secretariador.historicalsolicitud')),
                ('localidad', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.localidad')),
                ('solicitud', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='secretariador.solicitud')),
            ],
            options={
                'verbose_name': 'HistoricalSolicitud_solicitud_localidades',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RunPython(*m2m_baseline('secretariador', 'solicitud', 'HistoricalSolicitud', ['solicitud_localidades'])),
    ]
