# Generated by Django 5.1.5 on 2025-06-26 11:11

import secretariador.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariador', '0022_rename_vechiculo_modelo_ano_vehiculo_vehiculo_modelo_ano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='solicitud_actuacion',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='solicitud_actuacion',
            field=models.GeneratedField(db_persist=True, expression=secretariador.models.ConcatOp("solicitud_actuacion_jurisdiccion", models.Value("-"), 'solicitud_actuacion_ano', models.Value('-'), 'solicitud_actuacion_numero', models.Value('-AE')), output_field=models.TextField()),
        ),
    ]
