# Generated by Django 5.1.5 on 2025-06-26 13:45

import secretariador.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariador', '0023_alter_solicitud_solicitud_actuacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incorporacion',
            name='incorporacion_actuacion',
        ),
        migrations.AddField(
            model_name='incorporacion',
            name='incorporacion_actuacion_jurisdiccion',
            field=models.CharField(default='E10', max_length=3, verbose_name='Jurisdicción'),
        ),
        migrations.AddField(
            model_name='incorporacion',
            name='incorporacion_actuacion',
            field=models.GeneratedField(db_persist=True, expression=secretariador.models.ConcatOp('incorporacion_actuacion_jurisdiccion', models.Value('-'), 'incorporacion_actuacion_ano', models.Value('-'), 'incorporacion_actuacion_numero', models.Value('-AE')), output_field=models.TextField()),
        ),
    ]
