# Generated by Django 5.1.5 on 2025-07-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariador', '0024_incorporacion_incorporacion_actuacion_jurisdiccion_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='instrumentoslegalesdecretos',
            name='unique_decretos_1',
        ),
        migrations.AddConstraint(
            model_name='instrumentoslegalesdecretos',
            constraint=models.UniqueConstraint(fields=('instrumentolegaldecretos_tipo', 'instrumentolegaldecretos_numero', 'instrumentolegaldecretos_ano', 'instrumentolegaldecretos_fecha_aprobacion'), name='unique_decretos_1'),
        ),
    ]
