# Generated by Django 5.2.4 on 2025-07-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0032_alter_aseguradora_options_alter_empresa_options'),
        ('secretariador', '0025_remove_instrumentoslegalesdecretos_unique_decretos_1_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='incorporacion',
            name='unique_incorporacion_2',
        ),
        migrations.RemoveConstraint(
            model_name='solicitud',
            name='unique_solicitud_2',
        ),
        migrations.AlterField(
            model_name='comisionadosolicitud',
            name='comisionadosolicitud_chofer',
            field=models.BooleanField(verbose_name='Chofer?'),
        ),
        migrations.AlterField(
            model_name='comisionadosolicitud',
            name='comisionadosolicitud_colaborador',
            field=models.BooleanField(verbose_name='Colab.?'),
        ),
        migrations.AlterField(
            model_name='comisionadosolicitud',
            name='comisionadosolicitud_sin_viatico',
            field=models.BooleanField(default=False, verbose_name='$0'),
        ),
        migrations.AddConstraint(
            model_name='incorporacion',
            constraint=models.UniqueConstraint(fields=('incorporacion_actuacion_jurisdiccion', 'incorporacion_actuacion_ano', 'incorporacion_actuacion_numero'), name='unique_incorporacion_2'),
        ),
        migrations.AddConstraint(
            model_name='solicitud',
            constraint=models.UniqueConstraint(fields=('solicitud_actuacion_jurisdiccion', 'solicitud_actuacion_ano', 'solicitud_actuacion_numero'), name='unique_solicitud_2'),
        ),
    ]
