# Generated by Django 5.2.4 on 2025-08-22 12:12

import django.utils.timezone
import secretariador.functions
import secretariador.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariador', '0026_remove_incorporacion_unique_incorporacion_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentoslegalesresoluciones',
            name='instrumentolegalresoluciones_numero_sgt',
            field=models.GeneratedField(db_persist=True, expression=secretariador.models.ConcatOp(models.Value('RES-'), 'instrumentolegalresoluciones_ano', models.Value('-'), 'instrumentolegalresoluciones_numero', models.Value('-10-1')), output_field=models.CharField(max_length=20)),
        ),
        migrations.CreateModel(
            name='InstrumentosLegalesResolucionesDirectorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrumentolegalresolucionesdirectorio_tipo', models.CharField(choices=[('D', 'Resolución de Directorio')], default='P', max_length=1, verbose_name='Tipo')),
                ('instrumentolegalresolucionesdirectorio_numero', models.CharField(max_length=7, verbose_name='Número')),
                ('instrumentolegalresolucionesdirectorio_acta', models.CharField(default='', max_length=3, verbose_name='Acta')),
                ('instrumentolegalresolucionesdirectorio_ano', models.CharField(max_length=5, verbose_name='Año')),
                ('instrumentolegalresolucionesdirectorio_fecha_aprobacion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Aprobación')),
                ('instrumentolegalresolucionesdirectorio_descripcion', models.CharField(default='', max_length=600, verbose_name='Descripción')),
                ('instrumentolegalresolucionesdirectorio', models.FileField(blank=True, max_length=500, null=True, upload_to=secretariador.models.generate_name_resoluciones, validators=[secretariador.functions.FileValidator(content_types='application/pdf', max_size=14680064, min_size=None)])),
                ('instrumentolegalresolucionesdirectorio_str', models.GeneratedField(db_persist=True, expression=secretariador.models.ConcatOp('instrumentolegalresolucionesdirectorio_numero', models.Value(' - '), 'instrumentolegalresolucionesdirectorio_ano', models.Value(' - '), 'instrumentolegalresolucionesdirectorio_tipo'), output_field=models.TextField())),
                ('instrumentolegalresolucionesdirectorio_autocarga', models.BooleanField(default=False, verbose_name='Resolución importada sin intervención.')),
                ('instrumentolegalresolucionesdirectorio_document', models.TextField(blank=True, null=True, verbose_name='Texto Extraído por OCR')),
            ],
            options={
                'verbose_name': 'Instrumento Legal(Resolución Directorio)',
                'verbose_name_plural': 'Instrumentos Legales(Resoluciones Directorio)',
                'ordering': ['-instrumentolegalresolucionesdirectorio_ano', '-instrumentolegalresolucionesdirectorio_numero'],
                'constraints': [models.UniqueConstraint(fields=('instrumentolegalresolucionesdirectorio_tipo', 'instrumentolegalresolucionesdirectorio_numero', 'instrumentolegalresolucionesdirectorio_acta', 'instrumentolegalresolucionesdirectorio_ano'), name='unique_resolucion_directorio_1')],
            },
        ),
    ]
