# Generated by Django 5.2.10 on 2026-06-02 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretariador', '0027_instrumentoslegalesresoluciones_instrumentolegalresoluciones_numero_sgt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incorporacion',
            name='incorporacion_actuacion_ano',
            field=models.DecimalField(decimal_places=0, default=2026, max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Año Actuación'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='solicitud_actuacion_ano',
            field=models.DecimalField(decimal_places=0, default=2026, max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Año Actuación'),
        ),
    ]
