# Generated by Django 5.0.3 on 2024-10-18 12:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fallout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charfallout',
            name='AgiStat',
        ),
        migrations.RemoveField(
            model_name='charfallout',
            name='CarStat',
        ),
        migrations.RemoveField(
            model_name='charfallout',
            name='IntStat',
        ),
        migrations.RemoveField(
            model_name='charfallout',
            name='PerStat',
        ),
        migrations.RemoveField(
            model_name='charfallout',
            name='ResStat',
        ),
        migrations.RemoveField(
            model_name='charfallout',
            name='StrStat',
        ),
        migrations.RemoveField(
            model_name='charfallout',
            name='SueStat',
        ),
        migrations.RemoveField(
            model_name='charfallout',
            name='armasEnergiaSkill',
        ),
        migrations.RemoveField(
            model_name='charfallout',
            name='armasGrandesSkill',
        ),
        migrations.RemoveField(
            model_name='charfallout',
            name='armasMeleeSkill',
        ),
        migrations.RemoveField(
            model_name='charfallout',
            name='armasPequenasSkill',
        ),
        migrations.RemoveField(
            model_name='charfallout',
            name='atletismoSkill',
        ),
        migrations.RemoveField(
            model_name='charfallout',
            name='cienciaSkill',
        ),
        migrations.RemoveField(
            model_name='charfallout',
            name='conversacionSkill',
        ),
        migrations.RemoveField(
            model_name='charfallout',
            name='desarmadoSkill',
        ),
        migrations.RemoveField(
            model_name='charfallout',
            name='ganzuasSkill',
        ),
        migrations.RemoveField(
            model_name='charfallout',
            name='juegoSkill',
        ),
        migrations.RemoveField(
            model_name='charfallout',
            name='lanzarSkill',
        ),
        migrations.RemoveField(
            model_name='charfallout',
            name='medicinaSkill',
        ),
        migrations.RemoveField(
            model_name='charfallout',
            name='pilotarSkill',
        ),
        migrations.RemoveField(
            model_name='charfallout',
            name='primerosAuxiliosSkill',
        ),
        migrations.RemoveField(
            model_name='charfallout',
            name='repararSkill',
        ),
        migrations.RemoveField(
            model_name='charfallout',
            name='robarSkill',
        ),
        migrations.RemoveField(
            model_name='charfallout',
            name='sigiloSkill',
        ),
        migrations.RemoveField(
            model_name='charfallout',
            name='trampasSkill',
        ),
        migrations.RemoveField(
            model_name='charfallout',
            name='truequeSkill',
        ),
        migrations.RemoveField(
            model_name='charfallout',
            name='vidaAlAireLibreSkill',
        ),
        migrations.AddField(
            model_name='charfallout',
            name='AgiBase',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='AG-'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='AgiMod',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Agilidad Mod'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='AgiTotal',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Agilidad Total'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='CarBase',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='CA-'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='CarMod',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Carisma Mod'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='CarTotal',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Carisma Total'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='IntBase',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='IN-'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='IntMod',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Inteligencia Mod'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='IntTotal',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Inteligencia Total'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='PerBase',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='PE-'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='PerMod',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Percepción Mod'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='PerTotal',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Percepción Total'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='ResBase',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='RE-'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='ResMod',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Resistencia Mod'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='ResTotal',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Resistencia Total'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='StrBase',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='FU-'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='StrMod',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fuerza Mod'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='StrTotal',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fuerza Total'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='SueBase',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='SU-'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='SueMod',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Suerte Mod'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='SueTotal',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Suerte Total'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='apBase',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='PUNTOS DE ACCION » (5+AG/2)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='apTotal',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Puntos de Acción Total'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='armasEnergiaBaseSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Armas de Energía(Base)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='armasEnergiaPointsSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Armas de Energía(Puntos invertidos)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='armasEnergiaTotalSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Armas de Energía(Total)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='armasGrandesBaseSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Armas Grandes(Base)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='armasGrandesPointsSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Armas Grandes(Puntos invertidos)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='armasGrandesTotalSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Armas Grandes(Total)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='armasMeleeBaseSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Armas Melee(Base)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='armasMeleePointsSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Armas Melee(Puntos invertidos)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='armasMeleeTotalSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Armas Melee(Total)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='armasPequenasBaseSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Armas Pequeñas Base Skill'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='armasPequenasPointsSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Armas Pequeñas(Puntos invertidos)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='armasPequenasTotalSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Armas Pequeñas(Total)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='atletismoBaseSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Atletismo(Base)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='atletismoPointsSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Atletismo(Puntos invertidos)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='atletismoTotalSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Atletismo(Total)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='capCargaBase',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='CAPACIDAD DE CARGA » (11.35 + 11.35xFU) Kg'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='capCargaTotal',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Capacidad de Carga Total'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='cienciaBaseSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ciencia(Base)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='cienciaPointsSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ciencia(Puntos invertidos)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='cienciaTotalSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ciencia(Total)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='conversacionBaseSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Conversación(Base)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='conversacionPointsSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Conversación(Puntos invertidos)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='conversacionTotalSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Conversación(Total)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='danoMeleeBase',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1)], verbose_name='DAÑO MELEE » (FU - 5) Minimo 1'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='danoMeleeTotal',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Daño Melee Total'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='desarmadoBaseSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Desarmado(Base)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='desarmadoPointsSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Desarmado(Puntos invertidos)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='desarmadoTotalSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Desarmado(Total)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='ganzuasBaseSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ganzuas(Base)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='ganzuasPointsSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ganzuas(Puntos invertidos)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='ganzuasTotalSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ganzuas(Total)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='implanteBase',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='IMPLANTE » (10 x (IN + RE))'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='implanteTotal',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Implante Total'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='juegoBaseSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Juego(Base)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='juegoPointsSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Juego(Puntos invertidos)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='juegoTotalSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Juego(Total)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='lanzarBaseSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Lanzar(Base)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='lanzarPointsSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Lanzar(Puntos invertidos)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='lanzarTotalSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Lanzar(Total)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='medicinaBaseSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Medicina(Base)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='medicinaPointsSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Medicina(Puntos invertidos)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='medicinaTotalSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Medicina(Total)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='perksPorNivelBase',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Perks/Nivel »'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='perksPorNivelMod',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Perks Mod »'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='perksPorNivelTotal',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Perks Total »'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='pilotarBaseSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Pilotar(Base)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='pilotarPointsSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Pilotar(Puntos invertidos)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='pilotarTotalSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Pilotar(Total)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='primerosAuxiliosBaseSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Primeros Auxilios(Base)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='primerosAuxiliosPointsSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Primeros Auxilios(Puntos invertidos)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='primerosAuxiliosTotalSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Primeros Auxilios(Total)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='probCriticoBase',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='POSIBILIDAD DE CRITICO » (SU)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='probCriticoTotal',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Probabilidad de Crítico Total'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='puntosGolpePorNivelBase',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(1)], verbose_name='PG/Nivel (3+(RE/2)) »'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='puntosGolpePorNivelMod',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='PG/Nivel Mod »'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='puntosGolpePorNivelTotal',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='PG/Nivel Total »'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='puntosHabilidadPorNivelBase',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(1)], verbose_name='PH/Nivel (5+(2*IN)) »'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='puntosHabilidadPorNivelMod',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='PH Mod »'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='puntosHabilidadPorNivelTotal',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='PH Total »'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='ratioCuracionBase',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='RATIO CURACION » (RE / 3)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='ratioCuracionTotal',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Ratio de Curación Total'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='repararBaseSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Reparar(Base)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='repararPointsSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Reparar(Puntos invertidos)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='repararTotalSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Reparar(Total)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='resElectricidadBase',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='RESISTENCIA ELECTRICIDAD »'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='resElectricidadTotal',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Resistencia a Electricidad Total'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='resGasBase',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Resistencia Gas Base'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='resGasTotal',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Resistencia Gas Total'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='resRadiacionBase',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='RESISTENCIA RADIACION » (2 x RE)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='resRadiacionTotal',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Resistencia Radiación Total'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='resVenenoBase',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='RESISTENCIA VENENO » (5 x RE)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='resVenenoTotal',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Resistencia Veneno Total'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='robarBaseSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Robar(Base)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='robarPointsSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Robar(Puntos invertidos)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='robarTotalSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Robar(Total)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='secBase',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='SECUENCIA » (2xPE)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='secTotal',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Secuencia Total'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='sigiloBaseSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sigilo(Base)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='sigiloPointsSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sigilo(Puntos invertidos)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='sigiloTotalSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sigilo(Total)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='trampasBaseSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Trampas(Base)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='trampasPointsSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Trampas(Puntos invertidos)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='trampasTotalSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Trampas(Total)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='truequeBaseSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Trueque(Base)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='truequePointsSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Trueque(Puntos invertidos)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='truequeTotalSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Trueque(Total)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='vidaAlAireLibreBaseSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Vida al Aire Libre(Base)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='vidaAlAireLibrePointsSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Vida al Aire Libre(Puntos invertidos)'),
        ),
        migrations.AddField(
            model_name='charfallout',
            name='vidaAlAireLibreTotalSkill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Vida al Aire Libre(Total)'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='apMod',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Puntos de Acción Mod'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='armasEnergiaMod',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Armas de Energía Mod'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='armasEnergiaTag',
            field=models.BooleanField(default=False, verbose_name='ARMAS ENERGIA » (0%+2xAG)'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='armasGrandesMod',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Armas Grandes Mod'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='armasGrandesTag',
            field=models.BooleanField(default=False, verbose_name='ARMAS GRANDES » (0%+2xAG))'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='armasMeleeMod',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Armas Melee Mod'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='armasMeleeTag',
            field=models.BooleanField(default=False, verbose_name='ARMAS MELEE » (20%+2x(AG+FU))'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='armasPequenasMod',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Armas Pequeñas Mod'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='armasPequenasTag',
            field=models.BooleanField(default=False, verbose_name='ARMAS PEQUEÑAS » (5%+4xAG))'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='atletismoMod',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Atletismo Mod'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='atletismoTag',
            field=models.BooleanField(default=False, verbose_name='ATLETISMO » (5%+2x(FU+AG))'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='capCargaMod',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Capacidad de Carga Mod'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='cienciaMod',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Ciencia Mod'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='cienciaTag',
            field=models.BooleanField(default=False, verbose_name='CIENCIA » (0%+4xIN)'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='conversacionMod',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Conversación Mod'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='conversacionTag',
            field=models.BooleanField(default=False, verbose_name='CONVERSACION » (0%+(5xCA))'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='danoMeleeMod',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Daño Melee Mod'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='desarmadoMod',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Desarmado Mod'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='desarmadoTag',
            field=models.BooleanField(default=False, verbose_name='DESARMADO » (30%+2x(AG+FU))'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='experienciaPersonaje',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Experiencia'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='ganzuasMod',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Ganzuas Mod'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='ganzuasTag',
            field=models.BooleanField(default=False, verbose_name='GANZUAS » (0%+(10%+PE+AG))'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='implanteMod',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Implante Mod'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='juegoMod',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Juego Mod'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='juegoTag',
            field=models.BooleanField(default=False, verbose_name='JUEGO » (0%+(5xSU))'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='karmaPersonaje',
            field=models.IntegerField(default=0, verbose_name='Karma'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='lanzarMod',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Lanzar Mod'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='lanzarTag',
            field=models.BooleanField(default=False, verbose_name='LANZAR » (0%+4x(AG))'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='medicinaMod',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Medicina Mod'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='medicinaTag',
            field=models.BooleanField(default=False, verbose_name='MEDICINA » (0%+5+(PE+IN))'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='nivelPersonaje',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='pilotarMod',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Pilotar Mod'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='pilotarTag',
            field=models.BooleanField(default=False, verbose_name='PILOTAR » (0%+2x(AG+PE))'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='primerosAuxiliosMod',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Primeros Auxilios Mod'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='primerosAuxiliosTag',
            field=models.BooleanField(default=False, verbose_name='PRIMEROS AUXILIOS » (0%+2x(PE+IN))'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='probCriticoMod',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Probabilidad de Crítico Mod'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='ratioCuracionMod',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Ratio de Curación Mod'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='repararMod',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Reparar Mod'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='repararTag',
            field=models.BooleanField(default=False, verbose_name='REPARAR » (0%+3xIN)'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='resElectricidadMod',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Resistencia a Electricidad Mod'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='resGasMod',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Resistencia Gas Mod'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='resRadiacionMod',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Resistencia Radiación Mod'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='resVenenoMod',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Resistencia Veneno Mod'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='robarMod',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Robar Mod'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='robarTag',
            field=models.BooleanField(default=False, verbose_name='ROBAR » (0%+(3xAG))'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='secMod',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Secuencia Mod'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='sigiloMod',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Sigilo Mod'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='sigiloTag',
            field=models.BooleanField(default=False, verbose_name='SIGILO » (5%+(3xAG))'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='trampasMod',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Trampas Mod'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='trampasTag',
            field=models.BooleanField(default=False, verbose_name='TRAMPAS/EXPLOSIVOS » (0%+PE+AG)'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='truequeMod',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Trueque Mod'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='truequeTag',
            field=models.BooleanField(default=False, verbose_name='TRUEQUE » (0%+(4xCA))'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='vidaAlAireLibreMod',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Vida al Aire Libre Mod'),
        ),
        migrations.AlterField(
            model_name='charfallout',
            name='vidaAlAireLibreTag',
            field=models.BooleanField(default=False, verbose_name='VIDA AL AIRE LIBRE » (0%+2x(RE+IN))'),
        ),
    ]
