# Generated by Django 5.0.3 on 2024-10-22 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fallout', '0002_remove_charfallout_agistat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charfallout',
            name='razaPersonaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fallout.raza', verbose_name='Raza'),
        ),
    ]
