"""
Django settings for polizador project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import environ
import ldap
import os
from pathlib import Path
from django_auth_ldap.config import LDAPSearch
from google.oauth2 import service_account
import sentry_sdk

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# "Secret" Variables.
DEBUG = env("DEBUG")
ALLOWED_HOSTS= env.list("ALLOWED_HOSTS")
CSRF_TRUSTED_ORIGINS= env.list("CSRF_TRUSTED_ORIGINS")
SECRET_KEY = env('SECRET_KEY')
DBHOST=env("DBHOST")
DBUSER=env("DBUSER")
DBNAME=env("DBNAME")
DBSECRET=env("DBPASSWORD")
SENTRY_DSN=env("SENTRY_DSN")
MAILGUN_API_KEY=env("MAILGUN_API_KEY")
MAILGUN_SENDER_DOMAIN=env("MAILGUN_SENDER_DOMAIN")

GDU_LDAP_SERVER_URL = env("GDU_LDAP_SERVER_URL")
GDU_LDAP_BIND_DN = env("GDU_LDAP_BIND_DN")
GDU_LDAP_BIND_CREDENTIALS = env("GDU_LDAP_BIND_CREDENTIALS")
GDU_LDAP_SEARCH_BASE = env("GDU_LDAP_SEARCH_BASE")
GDU_LDAP_SEARCH_FILTER = env("GDU_LDAP_SEARCH_FILTER")

# django-auth-ldap: mismo servidor/credenciales que usaba hasura/config/passport.js
# (passport-ldapauth) para el login real de GDU contra Active Directory. El login
# local por contraseña (visualizador.user.password) nunca se usó de verdad en el
# sistema original — solo LDAP — así que esto reemplaza esa autenticación real.
AUTH_LDAP_SERVER_URI = GDU_LDAP_SERVER_URL
AUTH_LDAP_BIND_DN = GDU_LDAP_BIND_DN
AUTH_LDAP_BIND_PASSWORD = GDU_LDAP_BIND_CREDENTIALS
AUTH_LDAP_USER_SEARCH = LDAPSearch(
    GDU_LDAP_SEARCH_BASE,
    ldap.SCOPE_SUBTREE,
    # GDU_LDAP_SEARCH_FILTER trae el placeholder al estilo del ldapauth-fork de Node
    # ("{{username}}"); django-auth-ldap espera "%(user)s" — se convierte acá para
    # no duplicar el filtro en dos formatos distintos.
    GDU_LDAP_SEARCH_FILTER.replace("{{username}}", "%(user)s"),
)
# Sin esto, una conexión a un LDAP inalcanzable/caído puede colgarse mucho más
# de un minuto (problema conocido de python-ldap contra Active Directory) en vez
# de fallar rápido. OPT_REFERRALS=0 evita otro problema típico de AD (referrals
# que python-ldap no sigue bien por defecto).
AUTH_LDAP_CONNECTION_OPTIONS = {
    ldap.OPT_REFERRALS: 0,
    ldap.OPT_NETWORK_TIMEOUT: 10,
    ldap.OPT_TIMEOUT: 10,
}

# No crea cuentas nuevas: solo puede loguearse por LDAP quien ya tenga un
# CustomUser existente en polizador (los migrados de GDU + los que ya había).
# El LDAP es de toda la institución, no solo de GDU, así que esto evita que
# cualquier empleado del IPDUV consiga acceso automático a polizador.
AUTH_LDAP_NO_NEW_USERS = True
AUTH_LDAP_ALWAYS_UPDATE_USER = True
AUTH_LDAP_USER_ATTR_MAP = {
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail",
}

GDU_SMB_SHARE = env("GDU_SMB_SHARE")
GDU_SMB_DOMAIN = env("GDU_SMB_DOMAIN")
GDU_SMB_USERNAME = env("GDU_SMB_USERNAME")
GDU_SMB_PASSWORD = env("GDU_SMB_PASSWORD")

GDU_3450_API_BASE_URL = env("GDU_3450_API_BASE_URL")
GDU_3450_API_USERNAME = env("GDU_3450_API_USERNAME")
GDU_3450_API_PASSWORD = env("GDU_3450_API_PASSWORD")
GDU_3450_API_CLIENT_ID = env("GDU_3450_API_CLIENT_ID")

GDU_3450_IMPORT_API_BASE_URL = env("GDU_3450_IMPORT_API_BASE_URL")
GDU_3450_IMPORT_API_USERNAME = env("GDU_3450_IMPORT_API_USERNAME")
GDU_3450_IMPORT_API_PASSWORD = env("GDU_3450_IMPORT_API_PASSWORD")
GDU_3450_IMPORT_API_CLIENT_ID = env("GDU_3450_IMPORT_API_CLIENT_ID")

if DEBUG == False:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        # Set traces_sample_rate to 1.0 to capture 100%
        # of transactions for tracing.
        traces_sample_rate=1.0,
        _experiments={
            # Set continuous_profiling_auto_start to True
            # to automatically start the profiler on when
            # possible.
            "continuous_profiling_auto_start": True,
        },
    )
    
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    "django.contrib.sites",
    "django.contrib.gis",

    "django_select2",
	"import_export",
	"django.forms",
    "debug_toolbar",
    "allauth",
    "allauth.account",
    "simple_history",
    "anymail",

    "core",
    "carga",
	"secretariador",
    "personalizador",
    "api",
    "gdu",
]
SITE_ID = 1
# Widget template override. Place "widgetX.html" into "templates/django/forms/widgets/"
FORM_RENDERER = 'django.forms.renderers.TemplatesSetting'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
	"whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
	'simple_history.middleware.HistoryRequestMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = 'polizador.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
			BASE_DIR / "templates",
			BASE_DIR / "polizador/carga/templates",
            BASE_DIR / "polizador/secretariador/templates",
            ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
TEMPLATES[0]['OPTIONS']['context_processors'].append("polizador.context_processors.imglinks")
TEMPLATES[0]['OPTIONS']['context_processors'].append("polizador.context_processors.user_groups_processor")

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'django_auth_ldap.backend.LDAPBackend',
    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',

]
CACHES = {
    'default': env.cache(),
    "select2": env.cache_url("REDIS_URL"),
}
SELECT2_CACHE_BACKEND = "select2"
SELECT2_CACHE_TIMEOUT = 60 * 60 * 24 * 1 # 1 day
SELECT2_THEME = "bootstrap-5"
WSGI_APPLICATION = 'polizador.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "HOST": DBHOST,
        "USER": DBUSER,
	    "PASSWORD":DBSECRET,
        "NAME":DBNAME,
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_USER_MODEL = 'personalizador.CustomUser'  # Format: 'app_label.ModelName'
ACCOUNT_FORMS = {'signup': 'personalizador.forms.customuserform.CustomUserForm'}
ACCOUNT_SIGNUP_FIELDS = ['username*', 'first_name', 'last_name', 'email', 'password1*', 'password2*']
# ACCOUNT_ADAPTER = 'secretariador.adapters.InactiveSignupAdapter'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/
LANGUAGE_CODE = 'es-AR'

DATETIME_FORMAT="%d-%B-%Y" # "Dia en Numeros" - "Nombre Completo del Mes" - "Número Completo del Año"

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_L10N = True

USE_TZ = True
USE_THOUSAND_SEPARATOR = True

# Cloud Storage

try:
    GS_CREDENTIALS = service_account.Credentials.from_service_account_file(BASE_DIR / "polizador-production.json")
except (FileNotFoundError, ValueError):
    GS_CREDENTIALS = None
# DEFAULT_FILE_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'
# GS_BUCKET_NAME = 'polizador-production-pdf'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Redirects after Authentication

LOGOUT_REDIRECT_URL = '/home/'
LOGIN_REDIRECT_URL = "/home/"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "static_files/static"
# STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

MEDIA_URL  = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

STORAGES = {
    "default": {
        "BACKEND": "polizador.storages.GCloudAndLocalStorage",
        "OPTIONS": {
        #  https://storage.cloud.google.com/polizador-production-pdf/instrumentoslegales/resoluciones/1400-2024-P.pdf
            "bucket_name": "polizador-production-pdf",
            "credentials": GS_CREDENTIALS,
        },
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

DJANGO_EASY_AUDIT_UNREGISTERED_CLASSES_EXTRA = [
        "secretariador.instrumentoslegalesresoluciones",
        "secretariador.instrumentoslegalesdecretos",
        "secretariador.instrumentoslegalesmemorandum"
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,  # Keep Django's default loggers active
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/django.log'),
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        # Catch-all root logger
        '': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
        },
        # Dedicated logger for database queries (only outputs during local debug)
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
            'filters': ['require_debug_true'],
        },
    },
}

if DEBUG == True:
    INTERNAL_IPS = ["localhost", "127.0.0.1"]
    DEBUG_TOOLBAR_ENABLE = True
    EMAIL_BACKEND = "anymail.backends.console.EmailBackend"

    if DEBUG_TOOLBAR_ENABLE:
        MIDDLEWARE = ["debug_toolbar.middleware.DebugToolbarMiddleware"] + MIDDLEWARE
        DEBUG_TOOLBAR_PATCH_SETTINGS = False
        DEBUG_TOOLBAR_CONFIG = {
            "JQUERY_URL": "",
        }
elif DEBUG == False:
    INSTALLED_APPS = INSTALLED_APPS
    # Email backend configuration parameters
    EMAIL_BACKEND = "anymail.backends.mailgun.EmailBackend"
    ANYMAIL = {
        "MAILGUN_API_KEY": MAILGUN_API_KEY,
        "MAILGUN_SENDER_DOMAIN": MAILGUN_SENDER_DOMAIN,
    }
    DEFAULT_FROM_EMAIL = "noreply@mail.willylobo.net"
    SERVER_EMAIL = "admin@mail.willylobo.net"

