"""
Django settings for polizador project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import environ
import ldap
import os
import subprocess
import sys
from pathlib import Path
from django_auth_ldap.config import LDAPSearch
from google.oauth2 import service_account
import sentry_sdk

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Los tests leen el mismo .env que el servidor de desarrollo, asi que hay cosas
# que tienen que apagarse explicitamente cuando corre la suite -- ver LDAP y
# AD_VINCULACION_OBLIGATORIA mas abajo.
TESTING = "test" in sys.argv

# "Secret" Variables.
DEBUG = env("DEBUG")
ALLOWED_HOSTS= env.list("ALLOWED_HOSTS")
CSRF_TRUSTED_ORIGINS= env.list("CSRF_TRUSTED_ORIGINS")
# En producción, nginx termina el SSL y reenvía a Gunicorn por HTTP plano
# (via unix socket). Sin esto, Django cree que la request es insecure y el
# chequeo de Origin del CSRF en el login (que sí llega en https) falla con
# 403 al comparar contra "http://..." en vez de "https://...".
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECRET_KEY = env('SECRET_KEY')
DBHOST=env("DBHOST")
DBUSER=env("DBUSER")
DBNAME=env("DBNAME")
DBSECRET=env("DBPASSWORD")
SENTRY_DSN=env("SENTRY_DSN")
# Optional: only needed for the dashboard's "system health" tile, which reads
# recent issues back from the Sentry Web API (separate from the DSN above,
# which only lets the SDK *send* events). Left unset locally.
SENTRY_AUTH_TOKEN=env("SENTRY_AUTH_TOKEN", default=None)
SENTRY_ORG=env("SENTRY_ORG", default=None)
SENTRY_PROJECT=env("SENTRY_PROJECT", default=None)
MAILGUN_API_KEY=env("MAILGUN_API_KEY")
MAILGUN_SENDER_DOMAIN=env("MAILGUN_SENDER_DOMAIN")
# Credenciales del usuario institucional en gobiernodigital.chaco.gob.ar, usadas por
# secretariador/management/commands/sync_resoluciones_sgt.py para descargar
# Instrumentos Legales desde el SGT. Sin valor por defecto: el comando falla explícitamente
# si no están configuradas.
SGT_USERNAME = env("SGT_USERNAME", default=None)
SGT_PASSWORD = env("SGT_PASSWORD", default=None)
GS_BUCKET_NAME = env("GS_BUCKET_NAME", default="polizador-production-pdf")

if DEBUG == False:
    try:
        # El deploy es manual (git pull + reinicio de gunicorn), así que el
        # SHA del checkout en el momento del arranque *es* la versión
        # desplegada. Etiquetar los eventos con este release es lo que le
        # permite a Sentry mostrar "Suspect Commits" y sugerencias al
        # resolver un issue (ver scripts/sentry_release.sh para el paso que
        # asocia los commits a este mismo release en Sentry).
        SENTRY_RELEASE = subprocess.check_output(
            ["git", "rev-parse", "HEAD"], cwd=BASE_DIR
        ).decode().strip()
    except Exception:
        SENTRY_RELEASE = None

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        release=SENTRY_RELEASE,
        # Set traces_sample_rate to 1.0 to capture 100%
        # of transactions for tracing.
        traces_sample_rate=1.0,
        _experiments={
            # Set continuous_profiling_auto_start to True
            # to automatically start the profiler on when
            # possible.
            "continuous_profiling_auto_start": True,
        },
    )
    
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    "django.contrib.sites",
    "django.contrib.gis",

    "django_select2",
	"import_export",
	"django.forms",
    "debug_toolbar",
    "allauth",
    "allauth.account",
    "simple_history",
    "anymail",

    "core",
    "carga",
	"secretariador",
    "personalizador",
    "api",
]
SITE_ID = 1
# Widget template override. Place "widgetX.html" into "templates/django/forms/widgets/"
FORM_RENDERER = 'django.forms.renderers.TemplatesSetting'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
	"whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
	'simple_history.middleware.HistoryRequestMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware",
    "core.middleware_vincular_ad.VincularADMiddleware",
]

ROOT_URLCONF = 'polizador.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
			BASE_DIR / "templates",
			BASE_DIR / "polizador/carga/templates",
            BASE_DIR / "polizador/secretariador/templates",
            ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
TEMPLATES[0]['OPTIONS']['context_processors'].append("polizador.context_processors.imglinks")
TEMPLATES[0]['OPTIONS']['context_processors'].append("polizador.context_processors.user_groups_processor")
TEMPLATES[0]['OPTIONS']['context_processors'].append("polizador.context_processors.debug_mode")

# Static HTML site generated by SchemaSpy, served read-only to superusers
# via core.views.SchemaDocsView / schema_docs_asset.
SCHEMA_DOCS_ROOT = BASE_DIR / "templates" / "schema_docs"

# Documentación navegable del código (una página por clase/función), generada por
# `manage.py kb_extract` + autoría manual y servida read-only a superusers via
# core.views.KnowledgeBaseIndexView / KnowledgeBasePageView. Ver knowledge_base/README.md.
KNOWLEDGE_BASE_ROOT = BASE_DIR / "knowledge_base"

# --- Active Directory del IPDUV (django-auth-ldap) ---
# Todo opcional: sin estas variables la app arranca igual y el backend de LDAP
# simplemente no se agrega. Eso permite desplegar este cambio antes de tocar el
# .env del servidor, y que corran los tests y los entornos de desarrollo que no
# tienen alcance al AD.
GDU_LDAP_SERVER_URL = env("GDU_LDAP_SERVER_URL", default=None)
GDU_LDAP_BIND_DN = env("GDU_LDAP_BIND_DN", default=None)
GDU_LDAP_BIND_CREDENTIALS = env("GDU_LDAP_BIND_CREDENTIALS", default=None)
GDU_LDAP_SEARCH_BASE = env("GDU_LDAP_SEARCH_BASE", default=None)
GDU_LDAP_SEARCH_FILTER = env("GDU_LDAP_SEARCH_FILTER", default="(sAMAccountName={{username}})")

LDAP_CONFIGURADO = all([
    GDU_LDAP_SERVER_URL, GDU_LDAP_BIND_DN, GDU_LDAP_BIND_CREDENTIALS, GDU_LDAP_SEARCH_BASE,
])

AUTHENTICATION_BACKENDS = [
    # Primero el backend local, siempre: quien todavia no vinculo su cuenta de
    # red (o no tiene) sigue entrando con su usuario y contrasena de polizador.
    # LDAP se consulta despues, y solo para quien ya tiene ad_username.
    'django.contrib.auth.backends.ModelBackend',
    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',

]

if LDAP_CONFIGURADO:
    # Durante los tests se definen los AUTH_LDAP_* (para poder verificar la
    # configuracion) pero NO se registra el backend. Con el backend puesto, cada
    # authenticate() que ModelBackend rechaza -- una contrasena incorrecta a
    # proposito, pan de todos los dias en los tests -- cae en LDAPBackend y sale
    # a la red contra el AD real. Medido desde esta maquina, dentro de la red y
    # con el AD respondiendo, eso cuesta ~0,4s por intento fallido: molesto pero
    # tolerable. El problema es afuera de esa condicion ideal: sin alcance al AD
    # (CI, una portatil fuera de la red) cada intento fallido se come el timeout
    # de 10 segundos de AUTH_LDAP_CONNECTION_OPTIONS. Los tests no pueden
    # depender de que el AD este a mano.
    # Se nombra aparte para que los tests puedan verificar CUAL backend se usa
    # sin depender de que este registrado (durante los tests no lo esta).
    LDAP_BACKEND = 'core.ldap_backend.PolizadorLDAPBackend'
    if not TESTING:
        AUTHENTICATION_BACKENDS.append(LDAP_BACKEND)

    AUTH_LDAP_SERVER_URI = GDU_LDAP_SERVER_URL
    AUTH_LDAP_BIND_DN = GDU_LDAP_BIND_DN
    AUTH_LDAP_BIND_PASSWORD = GDU_LDAP_BIND_CREDENTIALS
    AUTH_LDAP_USER_SEARCH = LDAPSearch(
        GDU_LDAP_SEARCH_BASE,
        ldap.SCOPE_SUBTREE,
        # El .env trae el placeholder al estilo del ldapauth de Node
        # ("{{username}}"); django-auth-ldap espera "%(user)s". Se convierte aca
        # para no tener el mismo filtro escrito en dos formatos.
        GDU_LDAP_SEARCH_FILTER.replace("{{username}}", "%(user)s"),
    )

    # LA linea que hace que esto funcione con los usernames que hay. Sin esto,
    # django-auth-ldap busca al CustomUser por "username__iexact = lo tipeado",
    # y de 29 usuarios activos solo 16 tienen el username igual a su cuenta de
    # red -- el resto son apodos ("Fali", "Rocco26") o direcciones de correo.
    # Con USER_QUERY_FIELD busca por CustomUser.ad_username, que es el
    # sAMAccountName que cada usuario confirmo el mismo desde
    # /cuenta/vincular-red/. El username de polizador deja de importar para
    # autenticar, asi que nadie tiene que ser renombrado.
    #
    # OJO: este lookup es EXACTO, no __iexact (ver _get_or_create_user en
    # django_auth_ldap/backend.py), pero eso no es problema porque ad_username
    # no lo tipea nadie: lo escribe la vista de vinculacion con lo que devolvio
    # el AD.
    AUTH_LDAP_USER_QUERY_FIELD = "ad_username"
    # USER_QUERY_FIELD se resuelve contra este mapa, asi que el campo tiene que
    # estar si o si aca.
    #
    # A proposito NO se mapean first_name/last_name/email: en polizador esos
    # nombres estan curados y no siempre coinciden con los del AD ("Guillermo
    # Eduardo Lobo Cecchini" vs "Guillermo Lobo Cechini"), y mapearlos haria que
    # el primer login por LDAP los pise sin aviso. Si alguna vez se decide que
    # el AD es la fuente de verdad para los nombres, se agregan aca.
    AUTH_LDAP_USER_ATTR_MAP = {"ad_username": "sAMAccountName"}

    # Cualquiera con cuenta en el AD del IPDUV puede entrar, aunque no tenga
    # CustomUser todavia: se le crea uno al vuelo, SIN grupos y por lo tanto sin
    # ningun permiso. Asignarselos es trabajo de un superusuario desde el panel.
    #
    # El alta la hace core/ldap_backend.PolizadorLDAPBackend, no django-auth-ldap
    # por su cuenta: hay dos cosas que resolver antes de guardar (el username
    # quedaria vacio, y las 16 cuentas cuyo username ya coincide con el de red
    # se duplicarian). El porque completo esta en ese modulo.
    #
    # OJO con lo que ve una cuenta asi: los ~57 widgets de select2 de
    # carga/views/ajaxviews.py y personalizador/views/ajaxviews.py estan detras
    # de LoginRequiredMixin y nada mas, asi que cualquiera que pueda entrar puede
    # consultar esos autocompletados (obras, agentes, empresas, localidades...).
    # Antes eso alcanzaba a 29 personas revisadas; ahora alcanza a toda la
    # institucion. Si eso no es aceptable, hay que ponerles un permiso.
    AUTH_LDAP_NO_NEW_USERS = False
    AUTH_LDAP_ALWAYS_UPDATE_USER = True

    # Sin timeouts, una conexion a un AD caido puede colgar el login mucho mas
    # de un minuto (problema conocido de python-ldap contra Active Directory).
    # OPT_REFERRALS=0 evita el otro problema tipico de AD: referrals que
    # python-ldap no sigue bien.
    AUTH_LDAP_CONNECTION_OPTIONS = {
        ldap.OPT_REFERRALS: 0,
        ldap.OPT_NETWORK_TIMEOUT: 10,
        ldap.OPT_TIMEOUT: 10,
    }
CACHES = {
    'default': env.cache(),
    "select2": env.cache_url("REDIS_URL"),
}
# django-select2 no tiene setting de timeout: guarda cada widget con el TIMEOUT
# del backend. Si no se fija aca queda en 300s (el `default_timeout` del
# REDIS_URL va a OPTIONS y se ignora) y los widgets mueren a los 5 minutos.
CACHES["select2"]["TIMEOUT"] = 60 * 60 * 24 * 1 # 1 day
SELECT2_CACHE_BACKEND = "select2"
SELECT2_THEME = "bootstrap-5"
WSGI_APPLICATION = 'polizador.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "HOST": DBHOST,
        "USER": DBUSER,
	    "PASSWORD":DBSECRET,
        "NAME":DBNAME,
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_USER_MODEL = 'personalizador.CustomUser'  # Format: 'app_label.ModelName'
# Inertes mientras ACCOUNT_ADAPTER mantenga cerrado el alta: describen el
# formulario de signup, que ya no se sirve. Se dejan para no tener que
# reconstruirlos si alguna vez se reabre.
ACCOUNT_FORMS = {'signup': 'personalizador.forms.customuserform.CustomUserForm'}
ACCOUNT_SIGNUP_FIELDS = ['username*', 'first_name', 'last_name', 'email', 'password1*', 'password2*']
# Cierra /accounts/signup/: las cuentas las da de alta un administrador desde
# el panel de Django, que es donde ademas se asignan los grupos. Ver
# core/adapters.py para el porque completo.
ACCOUNT_ADAPTER = 'core.adapters.PolizadorAccountAdapter'

# Si esta en True, un usuario sin ad_username y que no haya declarado no tener
# cuenta de red es redirigido a /cuenta/vincular-red/ al navegar. Arranca
# apagado: se prende cuando se anuncia el cambio, y se puede volver a apagar
# si el AD queda fuera de servicio. Ver core/middleware_vincular_ad.py.
#
# Se ignora mientras corren los tests (ver TESTING mas arriba): prender el flag
# en el .env para probar la vinculacion a mano hacia fallar 36 tests de vistas
# de otras apps, que crean usuarios sin ad_username y recibian el redirect en
# vez de la pagina. Los tests del propio middleware la prenden con
# @override_settings.
AD_VINCULACION_OBLIGATORIA = env.bool("AD_VINCULACION_OBLIGATORIA", default=False) and not TESTING

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/
LANGUAGE_CODE = 'es-AR'

DATETIME_FORMAT="%d-%B-%Y" # "Dia en Numeros" - "Nombre Completo del Mes" - "Número Completo del Año"

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_L10N = True

USE_TZ = True
USE_THOUSAND_SEPARATOR = True

# Cloud Storage

try:
    GS_CREDENTIALS = service_account.Credentials.from_service_account_file(BASE_DIR / "polizador-production.json")
except (FileNotFoundError, ValueError):
    GS_CREDENTIALS = None
# DEFAULT_FILE_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'
# GS_BUCKET_NAME = 'polizador-production-pdf'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Redirects after Authentication

LOGOUT_REDIRECT_URL = '/home/'
LOGIN_REDIRECT_URL = "/home/"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "static_files/static"
# STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

MEDIA_URL  = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

STORAGES = {
    "default": {
        "BACKEND": "polizador.storages.GCloudAndLocalStorage",
        "OPTIONS": {
        #  https://storage.cloud.google.com/polizador-production-pdf/instrumentoslegales/resoluciones/1400-2024-P.pdf
            "bucket_name": GS_BUCKET_NAME,
            "credentials": GS_CREDENTIALS,
        },
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

DJANGO_EASY_AUDIT_UNREGISTERED_CLASSES_EXTRA = [
        "secretariador.instrumentoslegalesresoluciones",
        "secretariador.instrumentoslegalesdecretos",
        "secretariador.instrumentoslegalesmemorandum"
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,  # Keep Django's default loggers active
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/django.log'),
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'validation_errors_file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/validation_errors.log'),
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        # Catch-all root logger
        '': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
        },
        # Dedicated logger for database queries (only outputs during local debug)
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
            'filters': ['require_debug_true'],
        },
        # POST crudo de forms que no validaron, para debug de sesiones de usuario
        # (ver LogInvalidFormMixin en core/mixins.py). propagate=False para que no
        # duplique también en django.log via el logger root.
        'core.form_debug': {
            'handlers': ['validation_errors_file'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

if DEBUG == True:
    INTERNAL_IPS = ["localhost", "127.0.0.1"]
    DEBUG_TOOLBAR_ENABLE = True
    EMAIL_BACKEND = "anymail.backends.console.EmailBackend"

    if DEBUG_TOOLBAR_ENABLE:
        MIDDLEWARE = ["debug_toolbar.middleware.DebugToolbarMiddleware"] + MIDDLEWARE
        DEBUG_TOOLBAR_PATCH_SETTINGS = False
        DEBUG_TOOLBAR_CONFIG = {
            "JQUERY_URL": "",
        }
elif DEBUG == False:
    INSTALLED_APPS = INSTALLED_APPS
    # Email backend configuration parameters
    EMAIL_BACKEND = "anymail.backends.mailgun.EmailBackend"
    ANYMAIL = {
        "MAILGUN_API_KEY": MAILGUN_API_KEY,
        "MAILGUN_SENDER_DOMAIN": MAILGUN_SENDER_DOMAIN,
    }
    DEFAULT_FROM_EMAIL = "noreply@mail.willylobo.net"
    SERVER_EMAIL = "admin@mail.willylobo.net"

