editlinkimg     = "<img src='/static/images/pencil-square.svg' title='Editar' />"
detallelinkimg  = "<img src='/static/images/search.svg' title='Detalles' />"
eliminarlinkimg = "<img src='/static/images/trash3.svg' title='Eliminar' />"
generarlinkimg  = "<img src='/static/images/file-earmark-word.svg' title='Generar Documento' />"
pdflinkimg      = "<img src='/static/images/filetype-pdf.svg' title='Descargar PDF' />"