editlinkimg     = "<i class='bi bi-pencil-square' title='Editar'></i>"
detallelinkimg  = "<i class='bi bi-search' title='Detalles'></i>"
eliminarlinkimg = "<i class='bi bi-trash3' title='Eliminar'></i>"
generarlinkimg  = "<i class='bi bi-file-earmark-word' title='Generar Documento'></i>"
pdflinkimg      = "<i class='bi bi-filetype-pdf' title='Descargar PDF'></i>"