# Generated by Django 5.2.10 on 2026-06-02 22:13

import carga.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agente_nombre', models.CharField(max_length=60, verbose_name='Nombre/s')),
                ('agente_apellido', models.CharField(max_length=60, verbose_name='Apellido/s')),
                ('agente_dni', models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='DNI')),
                ('agente_telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono')),
                ('agente_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('agente_profesion', models.CharField(blank=True, choices=[('A', 'Arquitecto'), ('IC', 'Ingeniero Civil'), ('IE', 'Ingeniero Electromecánico'), ('MO', 'Maestro Mayor de Obras')], default=None, max_length=2, null=True, verbose_name='Profesion')),
                ('agente_matricula', models.CharField(blank=True, max_length=10, null=True, verbose_name='Matricula Profesional')),
                ('agente_nombre_completo', models.CharField(blank=True, editable=False, max_length=200, null=True, verbose_name='Nombre Completo')),
            ],
            options={
                'verbose_name_plural': 'Agentes',
                'ordering': ['agente_nombre', 'agente_apellido'],
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_nombre', models.CharField(max_length=50, verbose_name='Area')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'ordering': ['area_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Aseguradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aseguradora_nombre', models.CharField(max_length=255, verbose_name='Nombre Compañía Aseguradora')),
            ],
            options={
                'verbose_name': 'Aseguradora',
                'verbose_name_plural': 'Aseguradoras',
                'ordering': ['aseguradora_nombre'],
            },
        ),
        migrations.CreateModel(
            name='CertificadoFinanciamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificadofinanciamiento_nombre', models.CharField(max_length=100, verbose_name='Financiamiento')),
                ('certificadofinanciamiento_nombre_corto', models.CharField(max_length=1, verbose_name='Financiamiento Corto')),
            ],
            options={
                'verbose_name_plural': 'Financiamiento',
                'ordering': ['certificadofinanciamiento_nombre'],
            },
        ),
        migrations.CreateModel(
            name='CertificadoRubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificadorubro_nombre', models.CharField(max_length=100, verbose_name='Rubro')),
                ('certificadorubro_nombre_corto', models.CharField(max_length=1, verbose_name='Rubro Corto')),
            ],
            options={
                'verbose_name_plural': 'Rubros',
                'ordering': ['certificadorubro_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato_fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('contrato_descripcion', models.CharField(default='', max_length=600, verbose_name='Descripción')),
                ('contrato_resolucion', models.CharField(blank=True, max_length=15, null=True, verbose_name='Resolución Aprobatoria')),
                ('contrato_autocarga', models.BooleanField(default=False, editable=False, verbose_name='Contrato importado de formato anterior')),
                ('contrato_decreto', models.CharField(blank=True, max_length=15, null=True, verbose_name='Decreto Aprobatorio(Si Tuviera)')),
            ],
            options={
                'verbose_name_plural': 'Contratos',
                'ordering': ['contrato_fecha'],
            },
        ),
        migrations.CreateModel(
            name='ContratoRubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contratorubro_tipo', models.CharField(max_length=100, verbose_name='Rubro:')),
            ],
            options={
                'verbose_name_plural': 'Rubros de Contrato',
                'ordering': ['contratorubro_tipo'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('departamento_nombre', models.TextField(verbose_name='Nombre Departamento')),
            ],
            options={
                'verbose_name_plural': 'Departamentos',
                'ordering': ['departamento_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_nombre', models.CharField(max_length=255, verbose_name='Nombre Empresa')),
                ('empresa_cuit', models.CharField(blank=True, max_length=11, null=True, verbose_name='CUIT')),
                ('empresa_titular_titulo', models.CharField(blank=True, max_length=40, null=True, verbose_name='Titulo Representante')),
                ('empresa_titular_nombre', models.CharField(blank=True, max_length=140, null=True, verbose_name='Titular de la Empresa')),
                ('empresa_titular_dni', models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, verbose_name='DNI')),
                ('empresa_direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección de la Empresa')),
                ('empresa_inscripcion', models.CharField(blank=True, max_length=500, null=True, verbose_name='Inscripción')),
                ('empresa_correo_p', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Dirección de Correo Primaria')),
                ('empresa_correo_s', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Dirección de Correo Alternativa')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['empresa_nombre'],
            },
        ),
        migrations.CreateModel(
            name='INDEC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(verbose_name='Fecha de Medición')),
                ('indec_manodeobra', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Mano de Obra')),
                ('indec_albanileria', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Albañilería')),
                ('indec_carpinterías', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Carpinterías')),
                ('indec_andamios', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Andamios')),
                ('indec_iluminación', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Artefactos de iluminación y cableado')),
                ('indec_pvc', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Caños de PVC para instalaciones varias')),
                ('indec_gastos', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Gastos Generales')),
                ('indec_artefactos', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Artefactos para baño y grifería')),
                ('indec_hormigon', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Hormigón')),
                ('indec_valvulas', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Válvulas de bronce')),
                ('indec_electrobombas', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Electrobombas')),
                ('indec_quimicos', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Productos Químicos')),
                ('indec_motores', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Motores eléctricos y equipos de aire acondicionado')),
                ('indec_asfaltos', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Asfaltos, combustibles y lubricantes')),
                ('indec_medidores', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Medidores de caudal')),
                ('indec_membrana', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Membrana impermeabilizante')),
                ('indec_equipo', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Equipo - Amortización de equipo')),
                ('indec_pisos', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Pisos y revestimientos')),
                ('indec_aceros', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Aceros - Hierro aletado')),
                ('indec_cemento', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Cemento')),
                ('indec_arena', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Arena')),
                ('indec_costo_financiero', models.DecimalField(decimal_places=10, default=18.85, max_digits=20, verbose_name='Costo Financiero')),
                ('indec_transporte', models.DecimalField(decimal_places=10, default=134.98, max_digits=20, verbose_name='Transporte')),
            ],
            options={
                'verbose_name_plural': 'INDEC',
                'ordering': ['mes'],
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa_nombre', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
                'ordering': ['programa_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('provincia_nombre', models.CharField(max_length=33, verbose_name='Nombre Provincia')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'ordering': ['provincia_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Receptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receptor_nombre', models.CharField(max_length=100, verbose_name='Receptor')),
            ],
            options={
                'verbose_name': 'Receptor',
                'verbose_name_plural': 'Receptores',
                'ordering': ['receptor_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_numero', models.CharField(max_length=10, verbose_name='Número Región')),
            ],
            options={
                'verbose_name_plural': 'Region',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Uvi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uvi_fecha', models.DateField(verbose_name='Fecha UVI:')),
                ('uvi_valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
            ],
            options={
                'verbose_name_plural': 'UVI',
                'ordering': ['uvi_fecha'],
            },
        ),
        migrations.CreateModel(
            name='ConjuntoLicitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conjunto_nombre', models.TextField(verbose_name='Nombre')),
                ('conjunto_soluciones', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5, null=True, verbose_name='Cantidad de Soluciones')),
                ('conjunto_resolucion', models.CharField(blank=True, max_length=15, null=True, verbose_name='Resolucion')),
                ('conjunto_subconjunto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carga.conjuntolicitado', verbose_name='Conjunto Licitado')),
            ],
            options={
                'verbose_name_plural': 'Conjuntos Licitados',
                'ordering': ['id', 'conjunto_nombre'],
            },
        ),
        migrations.CreateModel(
            name='ContratoMonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contratomonto_pesos', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Monto Pesos')),
                ('contratomonto_uvi', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Monto UVI')),
                ('contratomonto_uvi_fecha', models.DateField(blank=True, null=True, verbose_name='Fecha UVI:')),
                ('contratomonto_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.contrato', verbose_name='Contrato')),
                ('contratomonto_financiamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.certificadofinanciamiento', verbose_name='Financiamiento')),
                ('contratomonto_rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.certificadorubro', verbose_name='Rubro Certificado')),
            ],
            options={
                'verbose_name_plural': 'Montos de Contrato',
                'ordering': ['contratomonto_contrato'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('municipio_nombre', models.CharField(max_length=40, verbose_name='Nombre')),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Id')),
                ('municipio_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.departamento', verbose_name='Departamento')),
                ('municipio_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carga.region', verbose_name='Región')),
            ],
            options={
                'verbose_name_plural': 'Municipios',
                'ordering': ['municipio_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('localidad_nombre', models.TextField(verbose_name='Nombre Localidad')),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Id')),
                ('localidad_centroide_lat', models.DecimalField(blank=True, decimal_places=13, max_digits=15, null=True, verbose_name='Latitud Centroide')),
                ('localidad_centroide_lon', models.DecimalField(blank=True, decimal_places=13, max_digits=15, null=True, verbose_name='Longitud Centroide')),
                ('localidad_funcion', models.CharField(blank=True, max_length=40, null=True, verbose_name='Función')),
                ('localidad_departamento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='carga.departamento', verbose_name='Departamento')),
                ('localidad_municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.municipio', verbose_name='Municipio')),
            ],
            options={
                'verbose_name_plural': 'Localidades',
                'ordering': ['localidad_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obra_nombre', models.TextField(help_text='Nombre de la Obra tal como figura en el contrato', verbose_name='Nombre')),
                ('obra_soluciones', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Cantidad de soluciones')),
                ('obra_grupo', models.CharField(blank=True, max_length=4, null=True, verbose_name='Grupo')),
                ('obra_plazo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Plazo de Ejecución')),
                ('obra_convenio', models.CharField(blank=True, max_length=60, null=True, verbose_name='Convenio/ACU')),
                ('obra_expediente', models.CharField(max_length=18, verbose_name='Expediente')),
                ('obra_resolucion', models.CharField(blank=True, max_length=15, null=True, verbose_name='Resolución de Adjudicación')),
                ('obra_licitacion_tipo', models.CharField(blank=True, choices=[('L', 'Licitación Pública'), ('P', 'Licitación Privada'), ('C', 'Concurso de Precios'), ('D', 'Contratación Directa')], max_length=1, null=True, verbose_name='Compulsa')),
                ('obra_licitacion_numero', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Número de Licitación')),
                ('obra_licitacion_ano', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Año de Licitación')),
                ('obra_nomenclatura', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Nomenclatura Catastral')),
                ('obra_nomenclatura_plano', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número de Plano')),
                ('obra_fecha_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega de la Obra')),
                ('obra_fecha_contrato', models.DateField(blank=True, null=True, verbose_name='Fecha de Firma de Contrato')),
                ('obra_expediente_costo', models.CharField(blank=True, max_length=18, null=True, verbose_name='Expediente de Costos')),
                ('obra_observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('obra_contrato_nacion_pesos', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Nación en Pesos')),
                ('obra_contrato_nacion_uvi', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Nación en UVI')),
                ('obra_contrato_nacion_uvi_fecha', models.DateField(blank=True, null=True, verbose_name='Fecha UVI Nación')),
                ('obra_contrato_provincia_pesos', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Provincia en Pesos')),
                ('obra_contrato_provincia_uvi', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Provincia en UVI')),
                ('obra_contrato_provincia_uvi_fecha', models.DateField(blank=True, null=True, verbose_name='Fecha UVI Provicia')),
                ('obra_contrato_terceros_pesos', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Terceros en Pesos')),
                ('obra_contrato_terceros_uvi', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Terceros en UVI')),
                ('obra_contrato_terceros_uvi_fecha', models.DateField(blank=True, null=True, verbose_name='Fecha UVI Terceros')),
                ('obra_contrato_total_pesos', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Monto Total Pesos')),
                ('obra_contrato_total_uvi', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Monto Total UVI')),
                ('obra_conjunto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carga.conjuntolicitado', verbose_name='Conjunto Licitado')),
                ('obra_departamento_m', models.ManyToManyField(blank=True, related_name='obra_departamento', to='carga.departamento', verbose_name='Departamento')),
                ('obra_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.empresa', verbose_name='Empresa')),
                ('obra_inspector', models.ManyToManyField(related_name='obra_inspector', to='carga.agente', verbose_name='Inspector')),
                ('obra_localidad_m', models.ManyToManyField(blank=True, related_name='obra_localidad', to='carga.localidad', verbose_name='Localidad')),
                ('obra_municipio_m', models.ManyToManyField(blank=True, related_name='obra_municipio', to='carga.municipio', verbose_name='Municipio')),
                ('obra_principal', models.ManyToManyField(blank=True, related_name='obra_madre', to='carga.obra', verbose_name='Obra Madre')),
                ('obra_programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.programa', verbose_name='Programa')),
                ('obra_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carga.region', verbose_name='Región')),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'ordering': ['obra_programa', 'obra_convenio', 'obra_nombre'],
            },
        ),
        migrations.CreateModel(
            name='ContratosDigitales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contratodigital_nombre_archivo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Archivo')),
                ('contratodigital_descripcion', models.TextField(verbose_name='Descripción')),
                ('contratodigital_archivo', models.FileField(max_length=500, upload_to=carga.models.generate_name_contratos)),
                ('contratodigital_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.contratorubro', verbose_name='Rubro Contrato')),
                ('contratodigital_obra', models.ManyToManyField(blank=True, related_name='obra_contratos', to='carga.obra', verbose_name='Obras')),
            ],
            options={
                'verbose_name_plural': 'Contratos Digitales',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='contrato_obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.obra', verbose_name='Obra'),
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificado_financiamiento', models.CharField(choices=[('N', 'Nación'), ('P', 'Provincia'), ('T', 'Terceros')], default='N', max_length=1, verbose_name='Financiamiento')),
                ('certificado_rubro', models.CharField(choices=[('V', 'Vivienda'), ('F', 'Infraestructura Frentista'), ('T', 'Terreno'), ('R', 'Redeterminación'), ('I', 'Nexos y Redes'), ('C', 'Complementario'), ('M', 'Deductivo')], default='V', max_length=1, verbose_name='Rubro')),
                ('certificado_rubro_anticipo', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Anticipo N°')),
                ('certificado_rubro_obra', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Obra N°')),
                ('certificado_rubro_devanticipo', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Devolución de Anticipo N°')),
                ('certificado_expediente', models.CharField(max_length=18, verbose_name='Número de Expediente')),
                ('certificado_periodo', models.CharField(blank=True, max_length=13, null=True, verbose_name='Periodo')),
                ('certificado_monto_pesos', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Monto en Pesos')),
                ('certificado_mes_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Mes %')),
                ('certificado_ante_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Anterior %')),
                ('certificado_acum_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Acumulado %')),
                ('certificado_devolucion_expte', models.CharField(blank=True, max_length=18, null=True, verbose_name='Número de Expediente Devolución')),
                ('certificado_devolucion_monto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Monto Devolución en Pesos')),
                ('certificado_devolucion_monto_uvi', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Monto Devolución en UVI')),
                ('certificado_monto_uvi', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Monto en UVI')),
                ('certificado_fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('certificado_monto_cobrar', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Monto a Cobrar Pesos')),
                ('certificado_monto_cobrar_uvi', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Monto a Cobrar UVI')),
                ('certificado_digital', models.FileField(blank=True, max_length=500, null=True, upload_to=carga.models.generate_name)),
                ('certificado_fecha_carga', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de carga')),
                ('certificado_fecha_carga_legacy', models.BooleanField(default=False, verbose_name='Es Certificado Viejo')),
                ('certificado_rubro_db', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='carga.certificadorubro', verbose_name='Rubro')),
                ('certificado_obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.obra', verbose_name='Obra')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['certificado_fecha', 'certificado_expediente'],
                'get_latest_by': 'certificado_fecha',
            },
        ),
        migrations.CreateModel(
            name='PlanDeTrabajos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabajos_obra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carga.obra')),
            ],
            options={
                'verbose_name_plural': 'Plan de Trabajos',
            },
        ),
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poliza_fecha', models.DateField(verbose_name='Fecha')),
                ('poliza_expediente', models.CharField(max_length=18, verbose_name='Expediente')),
                ('poliza_numero', models.IntegerField(verbose_name='Número de Póliza')),
                ('poliza_concepto', models.CharField(choices=[('C', 'Garantía de Ejecución de Contrato'), ('F', 'Garantía de Sustitución de Fondo de Reparo'), ('A', 'Garantía de Anticipo Financiero')], max_length=1, verbose_name='Concepto')),
                ('poliza_anexo', models.CharField(blank=True, max_length=40, null=True, verbose_name='Anexo de Póliza')),
                ('poliza_recibo', models.CharField(max_length=100, verbose_name='Número de Recibo')),
                ('poliza_monto_pesos', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Sustituido en Pesos')),
                ('poliza_monto_uvi', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Sustituido en UVI')),
                ('poliza_digital', models.FileField(blank=True, max_length=500, null=True, upload_to=carga.models.generate_name_poliza, verbose_name='Póliza Digital')),
                ('poliza_aseguradora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.aseguradora', verbose_name='Aseguradora')),
                ('poliza_obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.obra', verbose_name='Obra')),
                ('poliza_tomador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.empresa', verbose_name='Tomador')),
            ],
            options={
                'verbose_name': 'Póliza',
                'verbose_name_plural': 'Pólizas',
                'ordering': ['poliza_fecha'],
            },
        ),
        migrations.CreateModel(
            name='Prototipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prototipo_tipo', models.CharField(choices=[('1', '1 Dormitorio'), ('2', '2 Dormitorios'), ('3', '3 Dormitorios'), ('4', '4 Dormitorios'), ('o', 'Otro')], max_length=1, verbose_name='Tipo de Prototipo')),
                ('prototipo_cantidad', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Cantidad del Prototipo')),
                ('prototipo_superficie', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Superficie del Prototipo')),
                ('prototipo_uvi', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='UVIs x M2')),
                ('prototipo_incremento', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Incremento Porcentual por Infraestructura')),
                ('prototipo_discapacitado', models.BooleanField(default=False, verbose_name='Es Prototipo para Discapacitado')),
                ('prototipo_obra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carga.obra', verbose_name='Obra')),
            ],
        ),
        migrations.CreateModel(
            name='Poliza_Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poliza_movimiento_fecha', models.DateField(verbose_name='Fecha')),
                ('poliza_movimiento_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.area', verbose_name='Area')),
                ('poliza_movimiento_numero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.poliza', verbose_name='Póliza')),
                ('poliza_movimiento_receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.receptor', verbose_name='Receptor')),
            ],
            options={
                'verbose_name': 'Poliza_Movimiento',
                'verbose_name_plural': 'Polizas_Movimiento',
                'ordering': ['poliza_movimiento_fecha'],
            },
        ),
        migrations.CreateModel(
            name='ResolucionesDigitales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resoluciondigital_descripcion', models.TextField(verbose_name='Descripción')),
                ('resoluciondigital_numero', models.CharField(max_length=15, verbose_name='Resolución')),
                ('resoluciondigital_archivo', models.FileField(max_length=500, upload_to=carga.models.generate_name_resoluciones)),
                ('resoluciondigital_obra', models.ManyToManyField(blank=True, related_name='obra_resoluciones', to='carga.obra', verbose_name='Obras')),
            ],
            options={
                'verbose_name_plural': 'Resoluciones Digitales',
                'ordering': ['resoluciondigital_numero'],
            },
        ),
        migrations.AddConstraint(
            model_name='poliza',
            constraint=models.UniqueConstraint(fields=('poliza_fecha', 'poliza_numero', 'poliza_aseguradora', 'poliza_tomador'), name='poliza-constraint'),
        ),
    ]
