# Generated by Django 3.2.4 on 2022-02-22 13:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    # replaces = [('carga', '0001_initial'), ('carga', '0004_auto_20210903_1122'), ('carga', '0005_prototipohabitacional'), ('carga', '0007_auto_20210909_0940'), ('carga', '0008_auto_20210909_1144'), ('carga', '0009_auto_20210910_1240'), ('carga', '0010_auto_20211006_1515'), ('carga', '0011_auto_20211009_1203'), ('carga', '0012_merge_0003_auto_20210901_1105_0011_auto_20211009_1203'), ('carga', '0013_alter_obra_obra_nomenclatura'), ('carga', '0014_auto_20220201_1108'), ('carga', '0015_remove_certificado_certificado_fecha'), ('carga', '0016_auto_20220203_0913'), ('carga', '0017_alter_certificado_certificado_periodo'), ('carga', '0018_auto_20220207_1104'), ('carga', '0019_auto_20220222_0905')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agente_nombre', models.CharField(max_length=60, verbose_name='Nombre/s:')),
                ('agente_apellido', models.CharField(max_length=60, verbose_name='Apellido/s:')),
                ('agente_dni', models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='DNI:')),
                ('agente_telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono:')),
                ('agente_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email:')),
                ('agente_profesion', models.CharField(blank=True, choices=[('A', 'Arquitecto'), ('IC', 'Ingeniero Civil'), ('IE', 'Ingeniero Electromecánico'), ('MO', 'Maestro Mayor de Obras')], default=None, max_length=2, null=True, verbose_name='Profesion')),
                ('agente_matricula', models.CharField(blank=True, max_length=10, null=True, verbose_name='Matricula Profesional')),
            ],
            options={
                'verbose_name_plural': 'Agentes',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_nombre', models.CharField(max_length=50, verbose_name='Area')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='Aseguradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aseguradora_nombre', models.CharField(max_length=255, verbose_name='Nombre Empresa Aeguradora')),
            ],
            options={
                'verbose_name': 'Aseguradora',
                'verbose_name_plural': 'Aseguradoras',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('departamento_nombre', models.TextField(verbose_name='Nombre Departamento')),
            ],
            options={
                'verbose_name_plural': 'Departamentos',
                'ordering': ['departamento_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_nombre', models.CharField(max_length=255, verbose_name='Nombre Empresa Tomadora:')),
                ('empresa_cuit', models.CharField(blank=True, max_length=11, null=True, verbose_name='CUIT:')),
                ('empresa_titular', models.CharField(blank=True, max_length=140, null=True, verbose_name='Titular de la Empresa')),
                ('empresa_direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección de la Empresa')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('localidad_nombre', models.TextField(verbose_name='Nombre Localidad')),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('localidad_centroide_lat', models.DecimalField(blank=True, decimal_places=13, max_digits=15, null=True)),
                ('localidad_centroide_lon', models.DecimalField(blank=True, decimal_places=13, max_digits=15, null=True)),
                ('localidad_funcion', models.CharField(blank=True, max_length=40, null=True)),
                ('localidad_departamento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='carga.departamento')),
            ],
            options={
                'verbose_name_plural': 'Localidades',
                'ordering': ['localidad_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa_nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Progrma',
                'verbose_name_plural': 'Programas',
            },
        ),
        migrations.CreateModel(
            name='Receptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receptor_nombre', models.CharField(max_length=100, verbose_name='Receptor')),
            ],
            options={
                'verbose_name': 'Receptor',
                'verbose_name_plural': 'Receptores',
            },
        ),
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poliza_fecha', models.DateField(verbose_name='Fecha')),
                ('poliza_expediente', models.CharField(max_length=17, verbose_name='Número de Expediente')),
                ('poliza_numero', models.IntegerField(verbose_name='Número de Póliza')),
                ('poliza_concepto', models.CharField(choices=[('C', 'Garantía de Ejecución de Contrato'), ('F', 'Garantía de Sustitución de Fondo de Reparo'), ('A', 'Garantía de Anticipo Financiero')], max_length=1, verbose_name='Concepto')),
                ('poliza_anexo', models.CharField(blank=True, max_length=40, null=True, verbose_name='Anexo de póliza')),
                ('poliza_recibo', models.CharField(max_length=100, verbose_name='Número de Recibo')),
                ('poliza_obra_nombre', models.TextField(verbose_name='Obra')),
                ('poliza_obra_convenio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Convenio')),
                ('poliza_obra_expediente', models.CharField(blank=True, max_length=17, null=True, verbose_name='Número de Expediente de la Obra')),
                ('poliza_monto_pesos', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto Sustituido Pesos')),
                ('poliza_monto_uvi', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto Sustituido UVI')),
                ('poliza_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.area')),
                ('poliza_aseguradora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.aseguradora')),
                ('poliza_creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('poliza_editor', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poliza_editor', to=settings.AUTH_USER_MODEL)),
                ('poliza_receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.receptor')),
                ('poliza_tomador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.empresa')),
            ],
            options={
                'verbose_name': 'Póliza',
                'verbose_name_plural': 'Pólizas',
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obra_nombre', models.TextField(verbose_name='Nombre de la Obra tal como figura en el contrato')),
                ('obra_soluciones', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Cantidad de soluciones')),
                ('obra_grupo', models.CharField(blank=True, max_length=4, null=True, verbose_name='Grupo')),
                ('obra_plazo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Plazo de Ejecución')),
                ('obra_convenio', models.CharField(blank=True, max_length=60, null=True, verbose_name='Convenio/ACU')),
                ('obra_expediente', models.CharField(max_length=17, verbose_name='Expediente')),
                ('obra_resolucion', models.CharField(blank=True, max_length=15, null=True, verbose_name='Resolución de Adjudicación')),
                ('obra_licitacion_tipo', models.CharField(blank=True, choices=[('L', 'Licitación Pública'), ('P', 'Licitación Privada'), ('C', 'Concurso de Precios'), ('D', 'Contratación Directa')], max_length=1, null=True, verbose_name='Compulsa')),
                ('obra_licitacion_numero', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Número de Licitación')),
                ('obra_licitacion_ano', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Año de Licitación')),
                ('obra_nomenclatura', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nomenclatura Catastral')),
                ('obra_nomenclatura_plano', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número de Plano')),
                ('obra_fecha_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega de la Obra')),
                ('obra_fecha_contrato', models.DateField(blank=True, null=True, verbose_name='Fecha de Firma de Contrato')),
                ('obra_expediente_costo', models.CharField(blank=True, max_length=17, null=True, verbose_name='Expediente de Costos')),
                ('obra_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.empresa', verbose_name='Empresa')),
                ('obra_inspector', models.ManyToManyField(related_name='obra_inspector', to='carga.Agente')),
                ('obra_localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.localidad')),
                ('obra_programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.programa')),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('municipio_nombre', models.CharField(max_length=40)),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('municipio_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.departamento')),
            ],
            options={
                'verbose_name_plural': 'Municipios',
                'ordering': ['municipio_nombre'],
            },
        ),
        migrations.AddField(
            model_name='localidad',
            name='localidad_municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.municipio'),
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificado_rubro_obra', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Certificado de Obra N°')),
                ('certificado_rubro_anticipo', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Certificado de Anticipo N°')),
                ('certificado_rubro_devanticipo', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Certificado de Devolución de Anticipo N°')),
                ('certificado_rubro_691', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Certificado de Redeterminación Decreto N°691/16 N°')),
                ('certificado_rubro_Terreno', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Certificado de Terreno | Cuota N°')),
                ('certificado_rubro_recomposicion', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Certificado de Recomposición Período Anterior N°')),
                ('certificado_expediente', models.CharField(max_length=17, verbose_name='Número de Expediente')),
                ('certificado_fecha', models.DateField(verbose_name='Fecha de Salida')),
                ('certificado_monto_pesos', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto en UVI')),
                ('certificado_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.empresa')),
                ('certificado_localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.localidad')),
                ('certificado_obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.obra')),
                ('certificado_programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.programa')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
            },
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='empresa_titular',
            new_name='empresa_titular_nombre',
        ),
        migrations.AddField(
            model_name='empresa',
            name='empresa_correo_p',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Dirección de Correo Primaria:'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='empresa_correo_s',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Dirección de Correo Alternativa:'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='empresa_inscripcion',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Inscripción:'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='empresa_titular_dni',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, verbose_name='DNI:'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='empresa_titular_titulo',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Titulo Representante:'),
        ),
        migrations.AddField(
            model_name='obra',
            name='obra_conjunto',
            field=models.TextField(blank=True, null=True, verbose_name='Conjunto Licitado:'),
        ),
        migrations.AddField(
            model_name='obra',
            name='obra_observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones:'),
        ),
        migrations.CreateModel(
            name='Prototipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prototipo_tipo', models.CharField(choices=[('1', '1 Dormitorio'), ('2', '2 Dormitorios'), ('3', '3 Dormitorios'), ('4', '4 Dormitorios'), ('o', 'Otro')], max_length=1, verbose_name='Tipo de Prototipo:')),
                ('prototipo_cantidad', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Cantidad del Prototipo:')),
                ('prototipo_superficie', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Superficie del Prototipo: ')),
                ('prototipo_uvi', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='UVIs x M2:')),
                ('prototipo_incremento', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Incremento Porcentual por Infraestructura:')),
                ('prototipo_discapacitado', models.BooleanField(default=False, verbose_name='Es Prototipo para Discapacitado: ')),
                ('prototipo_obra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carga.obra')),
            ],
        ),
        migrations.RenameField(
            model_name='certificado',
            old_name='certificado_rubro_Terreno',
            new_name='certificado_rubro_terreno',
        ),
        migrations.AddField(
            model_name='certificado',
            name='certificado_monto_uvi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto en UVI'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='certificado_monto_pesos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto en Pesos'),
        ),
        migrations.AddField(
            model_name='obra',
            name='obra_contrato_nacion_pesos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Nación en Pesos: '),
        ),
        migrations.AddField(
            model_name='obra',
            name='obra_contrato_nacion_uvi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Nación en UVI: '),
        ),
        migrations.AddField(
            model_name='obra',
            name='obra_contrato_nacion_uvi_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha UVI Nación: '),
        ),
        migrations.AddField(
            model_name='obra',
            name='obra_contrato_provincia_pesos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Provincia en Pesos: '),
        ),
        migrations.AddField(
            model_name='obra',
            name='obra_contrato_provincia_uvi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Provincia en UVI: '),
        ),
        migrations.AddField(
            model_name='obra',
            name='obra_contrato_provincia_uvi_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha UVI Provicia: '),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='certificado_rubro_anticipo',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Anticipo N°'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='certificado_rubro_devanticipo',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Devolución de Anticipo N°'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='certificado_rubro_obra',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Obra N°'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='certificado_monto_pesos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto en Pesos'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='certificado_rubro_anticipo',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Anticipo N°'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='certificado_rubro_devanticipo',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Devolución de Anticipo N°'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='certificado_rubro_obra',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Obra N°'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='poliza_monto_pesos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Sustituido Pesos'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='poliza_monto_uvi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Sustituido UVI'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='obra_nomenclatura',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nomenclatura Catastral'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='certificado_acum_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Acumulado %'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='certificado_ante_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Anterior %'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='certificado_mes_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Mes %'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='obra_nomenclatura',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nomenclatura Catastral'),
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='certificado_fecha',
        ),
        migrations.AddField(
            model_name='certificado',
            name='certificado_devolucion_expte',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Número de Expediente Devolución'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='certificado_periodo',
            field=models.CharField(max_length=13, verbose_name='Periodo'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='certificado_devolucion_monto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Monto Devolución en Pesos'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='certificado_monto_cobrar',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Monto a Cobrar'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='certificado_monto_pesos',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Monto en Pesos'),
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='certificado_empresa',
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='certificado_localidad',
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='certificado_programa',
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='certificado_rubro_691',
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='certificado_rubro_recomposicion',
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='certificado_rubro_terreno',
        ),
        migrations.AlterField(
            model_name='obra',
            name='obra_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.empresa', verbose_name='Obra_Empresa'),
        ),
    ]
