# Generated by Django 3.2.4 on 2022-07-01 14:19

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('carga', '0002_auto_20220224_1155'), ('carga', '0003_auto_20220302_1144'), ('carga', '0004_auto_20220621_1007'), ('carga', '0005_auto_20220621_1157'), ('carga', '0006_auto_20220621_1225'), ('carga', '0007_auto_20220623_1122'), ('carga', '0008_auto_20220628_0854'), ('carga', '0009_auto_20220630_0801'), ('carga', '0010_auto_20220701_1109')]

    dependencies = [
        ('carga', '0001_squashed_0019_auto_20220222_0905'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poliza',
            new_name='LegacyPoliza',
        ),
        migrations.AlterModelOptions(
            name='legacypoliza',
            options={'verbose_name': 'Legacy_Póliza', 'verbose_name_plural': 'Legacy_Pólizas'},
        ),
        migrations.RenameField(
            model_name='legacypoliza',
            old_name='poliza_anexo',
            new_name='legacy_poliza_anexo',
        ),
        migrations.RenameField(
            model_name='legacypoliza',
            old_name='poliza_area',
            new_name='legacy_poliza_area',
        ),
        migrations.RenameField(
            model_name='legacypoliza',
            old_name='poliza_aseguradora',
            new_name='legacy_poliza_aseguradora',
        ),
        migrations.RenameField(
            model_name='legacypoliza',
            old_name='poliza_concepto',
            new_name='legacy_poliza_concepto',
        ),
        migrations.RenameField(
            model_name='legacypoliza',
            old_name='poliza_creador',
            new_name='legacy_poliza_creador',
        ),
        migrations.RenameField(
            model_name='legacypoliza',
            old_name='poliza_editor',
            new_name='legacy_poliza_editor',
        ),
        migrations.RenameField(
            model_name='legacypoliza',
            old_name='poliza_expediente',
            new_name='legacy_poliza_expediente',
        ),
        migrations.RenameField(
            model_name='legacypoliza',
            old_name='poliza_fecha',
            new_name='legacy_poliza_fecha',
        ),
        migrations.RenameField(
            model_name='legacypoliza',
            old_name='poliza_monto_pesos',
            new_name='legacy_poliza_monto_pesos',
        ),
        migrations.RenameField(
            model_name='legacypoliza',
            old_name='poliza_monto_uvi',
            new_name='legacy_poliza_monto_uvi',
        ),
        migrations.RenameField(
            model_name='legacypoliza',
            old_name='poliza_numero',
            new_name='legacy_poliza_numero',
        ),
        migrations.RenameField(
            model_name='legacypoliza',
            old_name='poliza_obra_convenio',
            new_name='legacy_poliza_obra_convenio',
        ),
        migrations.RenameField(
            model_name='legacypoliza',
            old_name='poliza_obra_expediente',
            new_name='legacy_poliza_obra_expediente',
        ),
        migrations.RenameField(
            model_name='legacypoliza',
            old_name='poliza_obra_nombre',
            new_name='legacy_poliza_obra_nombre',
        ),
        migrations.RenameField(
            model_name='legacypoliza',
            old_name='poliza_receptor',
            new_name='legacy_poliza_receptor',
        ),
        migrations.RenameField(
            model_name='legacypoliza',
            old_name='poliza_recibo',
            new_name='legacy_poliza_recibo',
        ),
        migrations.RenameField(
            model_name='legacypoliza',
            old_name='poliza_tomador',
            new_name='legacy_poliza_tomador',
        ),
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poliza_fecha', models.DateField(verbose_name='Fecha')),
                ('poliza_expediente', models.CharField(max_length=17, verbose_name='Expediente')),
                ('poliza_numero', models.IntegerField(verbose_name='Número de Póliza')),
                ('poliza_concepto', models.CharField(choices=[('C', 'Garantía de Ejecución de Contrato'), ('F', 'Garantía de Sustitución de Fondo de Reparo'), ('A', 'Garantía de Anticipo Financiero')], max_length=1, verbose_name='Concepto')),
                ('poliza_anexo', models.CharField(blank=True, max_length=40, null=True, verbose_name='Anexo de Póliza')),
                ('poliza_recibo', models.CharField(max_length=100, verbose_name='Número de Recibo')),
                ('poliza_monto_pesos', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Sustituido en Pesos')),
                ('poliza_monto_uvi', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Sustituido en UVI')),
                ('poliza_aseguradora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.aseguradora')),
                ('poliza_creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('poliza_editor', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poliza_editor', to=settings.AUTH_USER_MODEL)),
                ('poliza_obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.obra')),
                ('poliza_tomador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.empresa')),
            ],
            options={
                'verbose_name': 'Póliza',
                'verbose_name_plural': 'Pólizas',
            },
        ),
        migrations.AlterField(
            model_name='legacypoliza',
            name='legacy_poliza_editor',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_poliza_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Poliza_Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poliza_movimiento_fecha', models.DateField(verbose_name='Fecha')),
                ('poliza_movimiento_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.area')),
                ('poliza_movimiento_editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('poliza_movimiento_numero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.poliza')),
                ('poliza_movimiento_receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.receptor')),
            ],
            options={
                'verbose_name': 'Poliza_Movimiento',
                'verbose_name_plural': 'Polizas_Movimiento',
            },
        ),
        migrations.AddConstraint(
            model_name='poliza',
            constraint=models.UniqueConstraint(fields=('poliza_fecha', 'poliza_numero', 'poliza_aseguradora', 'poliza_tomador'), name='poliza-constraint'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='certificado_acum_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Acumulado %'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='certificado_ante_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Anterior %'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='certificado_devolucion_expte',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='Número de Expediente Devolución'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='certificado_expediente',
            field=models.CharField(max_length=18, verbose_name='Número de Expediente'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='certificado_mes_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Mes %'),
        ),
        migrations.AlterField(
            model_name='legacypoliza',
            name='legacy_poliza_creador',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='obra',
            name='obra_expediente',
            field=models.CharField(max_length=18, verbose_name='Expediente'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='obra_expediente_costo',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='Expediente de Costos'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='poliza_creador',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='poliza_expediente',
            field=models.CharField(max_length=18, verbose_name='Expediente'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='certificado_financiamiento',
            field=models.CharField(choices=[('N', 'Nación'), ('P', 'Provincia'), ('T', 'Terceros')], default='N', max_length=1, verbose_name='Financiamiento'),
        ),
        migrations.AddField(
            model_name='obra',
            name='obra_contrato_total_pesos',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Monto Total Pesos'),
        ),
        migrations.AddField(
            model_name='obra',
            name='obra_contrato_total_uvi',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Monto Total UVI'),
        ),
        migrations.AddField(
            model_name='obra',
            name='obra_obra_madre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carga.obra'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='certificado_periodo',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Periodo'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='certificado_fecha',
            field=models.DateField(default=datetime.datetime(2022, 6, 30, 8, 1, 2, 1767), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='certificado_monto_uvi',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Monto en UVI'),
        ),
    ]
