# Generated by Django 5.2.10 on 2026-06-06 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carga', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalagente',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalarea',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalaseguradora',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcertificado',
            name='certificado_rubro_db',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.certificadorubro', verbose_name='Rubro'),
        ),
        migrations.AddField(
            model_name='historicalcertificado',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcertificadofinanciamiento',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcertificadorubro',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalconjuntolicitado',
            name='conjunto_subconjunto',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.conjuntolicitado', verbose_name='Conjunto Licitado'),
        ),
        migrations.AddField(
            model_name='historicalconjuntolicitado',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcontrato',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcontratomonto',
            name='contratomonto_contrato',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.contrato', verbose_name='Contrato'),
        ),
        migrations.AddField(
            model_name='historicalcontratomonto',
            name='contratomonto_financiamiento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.certificadofinanciamiento', verbose_name='Financiamiento'),
        ),
        migrations.AddField(
            model_name='historicalcontratomonto',
            name='contratomonto_rubro',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.certificadorubro', verbose_name='Rubro Certificado'),
        ),
        migrations.AddField(
            model_name='historicalcontratomonto',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcontratorubro',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcontratosdigitales',
            name='contratodigital_tipo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.contratorubro', verbose_name='Rubro Contrato'),
        ),
        migrations.AddField(
            model_name='historicalcontratosdigitales',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldepartamento',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalempresa',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalindec',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicallocalidad',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicallocalidad',
            name='localidad_departamento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.departamento', verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='historicalmunicipio',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmunicipio',
            name='municipio_departamento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.departamento', verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='historicalobra',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalobra',
            name='obra_conjunto',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.conjuntolicitado', verbose_name='Conjunto Licitado'),
        ),
        migrations.AddField(
            model_name='historicalobra',
            name='obra_empresa',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='historicalplandetrabajos',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpoliza',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpoliza',
            name='poliza_aseguradora',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.aseguradora', verbose_name='Aseguradora'),
        ),
        migrations.AddField(
            model_name='historicalpoliza',
            name='poliza_tomador',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.empresa', verbose_name='Tomador'),
        ),
        migrations.AddField(
            model_name='historicalpoliza_movimiento',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpoliza_movimiento',
            name='poliza_movimiento_area',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.area', verbose_name='Area'),
        ),
        migrations.AddField(
            model_name='historicalprograma',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalprototipo',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalprovincia',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalreceptor',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalregion',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalresolucionesdigitales',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaluvi',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='localidad',
            name='localidad_departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='carga.departamento', verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='municipio_departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.departamento', verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='localidad',
            name='localidad_municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.municipio', verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='historicallocalidad',
            name='localidad_municipio',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.municipio', verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='obra',
            name='obra_conjunto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carga.conjuntolicitado', verbose_name='Conjunto Licitado'),
        ),
        migrations.AddField(
            model_name='obra',
            name='obra_departamento_m',
            field=models.ManyToManyField(blank=True, related_name='obra_departamento', to='carga.departamento', verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='obra',
            name='obra_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='obra',
            name='obra_inspector',
            field=models.ManyToManyField(related_name='obra_inspector', to='carga.agente', verbose_name='Inspector'),
        ),
        migrations.AddField(
            model_name='obra',
            name='obra_localidad_m',
            field=models.ManyToManyField(blank=True, related_name='obra_localidad', to='carga.localidad', verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='obra',
            name='obra_municipio_m',
            field=models.ManyToManyField(blank=True, related_name='obra_municipio', to='carga.municipio', verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='obra',
            name='obra_principal',
            field=models.ManyToManyField(blank=True, related_name='obra_madre', to='carga.obra', verbose_name='Obra Madre'),
        ),
        migrations.AddField(
            model_name='historicalprototipo',
            name='prototipo_obra',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.obra', verbose_name='Obra'),
        ),
        migrations.AddField(
            model_name='historicalpoliza',
            name='poliza_obra',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.obra', verbose_name='Obra'),
        ),
        migrations.AddField(
            model_name='historicalplandetrabajos',
            name='trabajos_obra',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.obra'),
        ),
        migrations.AddField(
            model_name='historicalcontrato',
            name='contrato_obra',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.obra', verbose_name='Obra'),
        ),
        migrations.AddField(
            model_name='historicalcertificado',
            name='certificado_obra',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.obra', verbose_name='Obra'),
        ),
        migrations.AddField(
            model_name='contratosdigitales',
            name='contratodigital_obra',
            field=models.ManyToManyField(blank=True, related_name='obra_contratos', to='carga.obra', verbose_name='Obras'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='contrato_obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.obra', verbose_name='Obra'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='certificado_obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.obra', verbose_name='Obra'),
        ),
        migrations.AddField(
            model_name='plandetrabajos',
            name='trabajos_obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carga.obra'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='poliza_aseguradora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.aseguradora', verbose_name='Aseguradora'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='poliza_obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.obra', verbose_name='Obra'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='poliza_tomador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.empresa', verbose_name='Tomador'),
        ),
        migrations.AddField(
            model_name='historicalpoliza_movimiento',
            name='poliza_movimiento_numero',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.poliza', verbose_name='Póliza'),
        ),
        migrations.AddField(
            model_name='poliza_movimiento',
            name='poliza_movimiento_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.area', verbose_name='Area'),
        ),
        migrations.AddField(
            model_name='poliza_movimiento',
            name='poliza_movimiento_numero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.poliza', verbose_name='Póliza'),
        ),
        migrations.AddField(
            model_name='obra',
            name='obra_programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.programa', verbose_name='Programa'),
        ),
        migrations.AddField(
            model_name='historicalobra',
            name='obra_programa',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.programa', verbose_name='Programa'),
        ),
        migrations.AddField(
            model_name='prototipo',
            name='prototipo_obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carga.obra', verbose_name='Obra'),
        ),
        migrations.AddField(
            model_name='poliza_movimiento',
            name='poliza_movimiento_receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.receptor', verbose_name='Receptor'),
        ),
        migrations.AddField(
            model_name='historicalpoliza_movimiento',
            name='poliza_movimiento_receptor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.receptor', verbose_name='Receptor'),
        ),
        migrations.AddField(
            model_name='obra',
            name='obra_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carga.region', verbose_name='Región'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='municipio_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carga.region', verbose_name='Región'),
        ),
        migrations.AddField(
            model_name='historicalobra',
            name='obra_region',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.region', verbose_name='Región'),
        ),
        migrations.AddField(
            model_name='historicalmunicipio',
            name='municipio_region',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.region', verbose_name='Región'),
        ),
        migrations.AddField(
            model_name='resolucionesdigitales',
            name='resoluciondigital_obra',
            field=models.ManyToManyField(blank=True, related_name='obra_resoluciones', to='carga.obra', verbose_name='Obras'),
        ),
        migrations.AddConstraint(
            model_name='poliza',
            constraint=models.UniqueConstraint(fields=('poliza_fecha', 'poliza_numero', 'poliza_aseguradora', 'poliza_tomador'), name='poliza-constraint'),
        ),
    ]
