# Generated by Django 6.0.6 on 2026-06-08 15:58

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalobra',
            name='obra_contrato_total_pesos',
        ),
        migrations.RemoveField(
            model_name='historicalobra',
            name='obra_contrato_total_uvi',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='obra_contrato_total_pesos',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='obra_contrato_total_uvi',
        ),
        migrations.AddField(
            model_name='obra',
            name='obra_contrato_total_pesos',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('obra_contrato_nacion_pesos'), '+', models.F('obra_contrato_terceros_pesos')), '+', models.F('obra_contrato_provincia_pesos')), output_field=models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
        ),
        migrations.AddField(
            model_name='obra',
            name='obra_contrato_total_uvi',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('obra_contrato_nacion_uvi'), '+', models.F('obra_contrato_terceros_uvi')), '+', models.F('obra_contrato_provincia_uvi')), output_field=models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
        ),
    ]
