# Generated by Django 3.2.4 on 2022-07-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0002_auto_20220224_1155_squashed_0010_auto_20220701_1109'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='legacypoliza',
            constraint=models.UniqueConstraint(fields=('legacy_poliza_expediente', 'legacy_poliza_fecha', 'legacy_poliza_numero', 'legacy_poliza_aseguradora', 'legacy_poliza_receptor'), name='legacy-poliza-constraint'),
        ),
    ]
