# Generated by Django 6.0.6 on 2026-06-09 13:26

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0003_remove_historicalobra_obra_contrato_total_pesos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcertificado',
            name='certificado_monto_cobrar',
        ),
        migrations.RemoveField(
            model_name='historicalcertificado',
            name='certificado_monto_cobrar_uvi',
        ),
        migrations.RemoveField(
            model_name="certificado",
            name="certificado_monto_cobrar"
        ),
        migrations.RemoveField(
            model_name="certificado",
            name="certificado_monto_cobrar_uvi"
        ),
        migrations.AddField(
            model_name='certificado',
            name='certificado_monto_cobrar',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('certificado_monto_pesos'), '-', models.F('certificado_devolucion_monto')), output_field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Monto a Cobrar Pesos')),
        ),
        migrations.AddField(
            model_name='certificado',
            name='certificado_monto_cobrar_uvi',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('certificado_monto_uvi'), '-', models.F('certificado_devolucion_monto_uvi')), output_field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Monto a Cobrar UVI')),
        ),
    ]
