# Generated by Django 6.0.6 on 2026-06-09 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0004_remove_historicalcertificado_certificado_monto_cobrar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uvi',
            options={'get_latest_by': '-uvi_fecha', 'ordering': ['-uvi_fecha'], 'verbose_name_plural': 'UVI'},
        ),
    ]
