# Generated by Django 3.2.4 on 2022-07-01 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0004_auto_20220701_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='obra_contrato_terceros_pesos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Terceros en Pesos: '),
        ),
        migrations.AddField(
            model_name='obra',
            name='obra_contrato_terceros_uvi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Terceros en UVI: '),
        ),
        migrations.AddField(
            model_name='obra',
            name='obra_contrato_terceros_uvi_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha UVI Terceros: '),
        ),
    ]
