# Generated by Django 6.0.6 on 2026-06-10 14:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0005_alter_uvi_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='certificado_rubro_anticipo',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Anticipo N°'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='certificado_rubro_devanticipo',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Devolución de Anticipo N°'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='certificado_rubro_obra',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Obra N°'),
        ),
        migrations.AlterField(
            model_name='historicalcertificado',
            name='certificado_rubro_anticipo',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Anticipo N°'),
        ),
        migrations.AlterField(
            model_name='historicalcertificado',
            name='certificado_rubro_devanticipo',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Devolución de Anticipo N°'),
        ),
        migrations.AlterField(
            model_name='historicalcertificado',
            name='certificado_rubro_obra',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Obra N°'),
        ),
    ]
