# Generated by Django 3.2.4 on 2022-07-05 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carga', '0006_alter_poliza_movimiento_poliza_movimiento_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poliza_movimiento',
            name='poliza_movimiento_editor',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
