# Generated by Django 6.0.6 on 2026-06-11 21:37

import carga.models
import secretariador.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0006_alter_certificado_certificado_rubro_anticipo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalprototipo',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Prototipo Habitacional', 'verbose_name_plural': 'historical Prototipos Habitacionales'},
        ),
        migrations.AlterModelOptions(
            name='prototipo',
            options={'verbose_name': 'Prototipo Habitacional', 'verbose_name_plural': 'Prototipos Habitacionales'},
        ),
        migrations.AlterField(
            model_name='certificado',
            name='certificado_digital',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=carga.models.generate_name_certificados, validators=[secretariador.functions.FileValidator(content_types='application/pdf', max_size=14680064, min_size=None)]),
        ),
        migrations.AlterField(
            model_name='historicalcertificado',
            name='certificado_digital',
            field=models.TextField(blank=True, max_length=500, null=True, validators=[secretariador.functions.FileValidator(content_types='application/pdf', max_size=14680064, min_size=None)]),
        ),
        migrations.AlterField(
            model_name='historicalpoliza',
            name='poliza_digital',
            field=models.TextField(blank=True, max_length=500, null=True, validators=[secretariador.functions.FileValidator(content_types='application/pdf', max_size=14680064, min_size=None)], verbose_name='Póliza Digital'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='poliza_digital',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=carga.models.generate_name_polizas, validators=[secretariador.functions.FileValidator(content_types='application/pdf', max_size=14680064, min_size=None)], verbose_name='Póliza Digital'),
        ),
    ]
