# Generated by Django 3.2.4 on 2022-07-06 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0007_alter_poliza_movimiento_poliza_movimiento_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='obra_contrato_nacion_pesos',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Nación en Pesos: '),
        ),
        migrations.AlterField(
            model_name='obra',
            name='obra_contrato_nacion_uvi',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Nación en UVI: '),
        ),
        migrations.AlterField(
            model_name='obra',
            name='obra_contrato_provincia_pesos',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Provincia en Pesos: '),
        ),
        migrations.AlterField(
            model_name='obra',
            name='obra_contrato_provincia_uvi',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Provincia en UVI: '),
        ),
        migrations.AlterField(
            model_name='obra',
            name='obra_contrato_terceros_pesos',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Terceros en Pesos: '),
        ),
        migrations.AlterField(
            model_name='obra',
            name='obra_contrato_terceros_uvi',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Terceros en UVI: '),
        ),
    ]
