# Generated by Django 6.0.6 on 2026-06-12 15:30

import carga.models
import secretariador.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0007_alter_historicalprototipo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratosdigitales',
            name='contratodigital_archivo',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=carga.models.generate_name_contratos, validators=[secretariador.functions.FileValidator(content_types='application/pdf', max_size=14680064, min_size=None)]),
        ),
        migrations.AlterField(
            model_name='historicalcontratosdigitales',
            name='contratodigital_archivo',
            field=models.TextField(blank=True, max_length=500, null=True, validators=[secretariador.functions.FileValidator(content_types='application/pdf', max_size=14680064, min_size=None)]),
        ),
        migrations.AlterField(
            model_name='historicalresolucionesdigitales',
            name='resoluciondigital_archivo',
            field=models.TextField(blank=True, max_length=500, null=True, validators=[secretariador.functions.FileValidator(content_types='application/pdf', max_size=14680064, min_size=None)]),
        ),
        migrations.AlterField(
            model_name='resolucionesdigitales',
            name='resoluciondigital_archivo',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=carga.models.generate_name_resoluciones, validators=[secretariador.functions.FileValidator(content_types='application/pdf', max_size=14680064, min_size=None)]),
        ),
    ]
