# Generated by Django 3.2.4 on 2022-07-06 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0008_auto_20220706_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubConjuntoLicitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subconjunto_nombre', models.TextField(verbose_name='Nombre')),
                ('subconjunto_soluciones', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5, null=True, verbose_name='Cantidad de Soluciones')),
                ('subconjunto_resolucion', models.CharField(blank=True, max_length=15, null=True, verbose_name='Resolucion')),
                ('subconjunto_conjunto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carga.conjuntolicitado')),
            ],
        ),
    ]
