# Generated by Django 3.2.4 on 2022-08-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0011_auto_20220810_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='obra_departamento',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='obra_localidad',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='obra_municipio',
        ),
        migrations.AlterField(
            model_name='obra',
            name='obra_departamento_m',
            field=models.ManyToManyField(blank=True, related_name='obra_departamento', to='carga.Departamento', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='obra_localidad_m',
            field=models.ManyToManyField(blank=True, related_name='obra_localidad', to='carga.Localidad', verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='obra_municipio_m',
            field=models.ManyToManyField(blank=True, related_name='obra_municipio', to='carga.Municipio', verbose_name='Municipio'),
        ),
    ]
