# Generated by Django 6.0.6 on 2026-06-22 14:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0012_delete_agente'),
        ('personalizador', '0013_departamento_departamento_autoridad_a_cargo_fk_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FojaDeMedicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foja_uuid', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False)),
                ('foja_periodo', models.DateField(verbose_name='Período (Mes)')),
                ('foja_fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Medición')),
                ('foja_observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('foja_inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='personalizador.agente', verbose_name='Inspector')),
                ('foja_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fojas', to='carga.plandetrabajos', verbose_name='Plan de Trabajos')),
            ],
            options={
                'verbose_name': 'Foja de Medición',
                'verbose_name_plural': 'Fojas de Medición',
                'ordering': ['foja_periodo'],
            },
        ),
        migrations.AddField(
            model_name='certificado',
            name='certificado_foja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carga.fojademedicion', verbose_name='Foja de Medición de Origen'),
        ),
        migrations.AddField(
            model_name='historicalcertificado',
            name='certificado_foja',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.fojademedicion', verbose_name='Foja de Medición de Origen'),
        ),
        migrations.CreateModel(
            name='HistoricalFojaDeMedicion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('foja_uuid', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False)),
                ('foja_periodo', models.DateField(verbose_name='Período (Mes)')),
                ('foja_fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Medición')),
                ('foja_observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('foja_inspector', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personalizador.agente', verbose_name='Inspector')),
                ('foja_plan', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.plandetrabajos', verbose_name='Plan de Trabajos')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Foja de Medición',
                'verbose_name_plural': 'historical Fojas de Medición',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPlanDeTrabajosItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('planitem_uuid', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False)),
                ('planitem_nombre', models.CharField(max_length=200, verbose_name='Item')),
                ('planitem_orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('planitem_incidencia_pct', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Incidencia %')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('planitem_plan', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.plandetrabajos', verbose_name='Plan de Trabajos')),
            ],
            options={
                'verbose_name': 'historical Item de Plan de Trabajos',
                'verbose_name_plural': 'historical Items de Plan de Trabajos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PlanDeTrabajosItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planitem_uuid', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False)),
                ('planitem_nombre', models.CharField(max_length=200, verbose_name='Item')),
                ('planitem_orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('planitem_incidencia_pct', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Incidencia %')),
                ('planitem_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='carga.plandetrabajos', verbose_name='Plan de Trabajos')),
            ],
            options={
                'verbose_name': 'Item de Plan de Trabajos',
                'verbose_name_plural': 'Items de Plan de Trabajos',
                'ordering': ['planitem_plan', 'planitem_orden'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalFojaDeMedicionItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fojaitem_uuid', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False)),
                ('fojaitem_pct_avance_mes', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Avance del Mes %')),
                ('fojaitem_pct_acumulado', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Acumulado %')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('fojaitem_foja', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.fojademedicion', verbose_name='Foja de Medición')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fojaitem_planitem', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.plandetrabajositem', verbose_name='Item del Plan')),
            ],
            options={
                'verbose_name': 'historical Item de Foja de Medición',
                'verbose_name_plural': 'historical Items de Foja de Medición',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='FojaDeMedicionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fojaitem_uuid', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False)),
                ('fojaitem_pct_avance_mes', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Avance del Mes %')),
                ('fojaitem_pct_acumulado', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Acumulado %')),
                ('fojaitem_foja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='carga.fojademedicion', verbose_name='Foja de Medición')),
                ('fojaitem_planitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.plandetrabajositem', verbose_name='Item del Plan')),
            ],
            options={
                'verbose_name': 'Item de Foja de Medición',
                'verbose_name_plural': 'Items de Foja de Medición',
                'ordering': ['fojaitem_planitem__planitem_orden'],
            },
        ),
        migrations.AddConstraint(
            model_name='fojademedicion',
            constraint=models.UniqueConstraint(fields=('foja_plan', 'foja_periodo'), name='foja-periodo-unico'),
        ),
        migrations.AddConstraint(
            model_name='fojademedicionitem',
            constraint=models.UniqueConstraint(fields=('fojaitem_foja', 'fojaitem_planitem'), name='fojaitem-planitem-unico'),
        ),
    ]
