# Generated by Django 3.2.4 on 2022-08-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0012_auto_20220822_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='certificado_devolucion_monto_uvi',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Monto Devolución en UVI'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='certificado_digital',
            field=models.FileField(blank=True, max_length=253, null=True, upload_to='certificados/%m-%Y'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='certificado_rubro',
            field=models.CharField(choices=[('V', 'Vivienda'), ('F', 'Infraestructura Frentista'), ('T', 'Terreno'), ('R', 'Redeterminación'), ('I', 'Nexos y Redes'), ('C', 'Complementario')], default='V', max_length=1, verbose_name='Rubro'),
        ),
    ]
