# Generated by Django 6.0.6 on 2026-06-24 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0013_fojademedicion_certificado_certificado_foja_and_more'),
        ('personalizador', '0014_alter_agente_agente_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fojademedicion',
            options={'ordering': ['foja_plan', 'foja_numero'], 'verbose_name': 'Foja de Medición', 'verbose_name_plural': 'Fojas de Medición'},
        ),
        migrations.AddField(
            model_name='fojademedicion',
            name='foja_numero',
            field=models.PositiveIntegerField(default=1, editable=False, verbose_name='Número de Foja'),
        ),
        migrations.AddField(
            model_name='historicalfojademedicion',
            name='foja_numero',
            field=models.PositiveIntegerField(default=1, editable=False, verbose_name='Número de Foja'),
        ),
        migrations.AlterField(
            model_name='fojademedicionitem',
            name='fojaitem_pct_acumulado',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Acumulado %'),
        ),
        migrations.AlterField(
            model_name='fojademedicionitem',
            name='fojaitem_pct_avance_mes',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Avance del Mes %'),
        ),
        migrations.AlterField(
            model_name='historicalfojademedicionitem',
            name='fojaitem_pct_acumulado',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Acumulado %'),
        ),
        migrations.AlterField(
            model_name='historicalfojademedicionitem',
            name='fojaitem_pct_avance_mes',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Avance del Mes %'),
        ),
        migrations.AlterField(
            model_name='historicalplandetrabajositem',
            name='planitem_incidencia_pct',
            field=models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Incidencia %'),
        ),
        migrations.AlterField(
            model_name='plandetrabajositem',
            name='planitem_incidencia_pct',
            field=models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Incidencia %'),
        ),
        migrations.AddConstraint(
            model_name='fojademedicion',
            constraint=models.UniqueConstraint(fields=('foja_plan', 'foja_numero'), name='foja-numero-unico'),
        ),
    ]
