# Generated by Django 3.2.4 on 2022-08-26 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0013_auto_20220824_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='obra_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='obra_inspector',
            field=models.ManyToManyField(related_name='obra_inspector', to='carga.Agente', verbose_name='Inspector'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='obra_obra_madre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carga.obra', verbose_name='Obra Madre'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='obra_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carga.region', verbose_name='Región'),
        ),
    ]
