# Generated by Django 3.2.4 on 2022-09-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0014_auto_20220826_0711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='obra_obra_madre',
        ),
        migrations.AddField(
            model_name='certificado',
            name='certificado_monto_cobrar_uvi',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Monto a Cobrar UVI'),
        ),
        migrations.AddField(
            model_name='obra',
            name='obra_principal',
            field=models.ManyToManyField(blank=True, related_name='obra_madre', to='carga.Obra', verbose_name='Obra Madre'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='certificado_monto_cobrar',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Monto a Cobrar Pesos'),
        ),
    ]
