# Generated by Django 6.0.6 on 2026-06-24

import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0014_alter_fojademedicion_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanDeTrabajosRubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubro_uuid', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False)),
                ('rubro_nombre', models.CharField(max_length=200, verbose_name='Rubro')),
                ('rubro_orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('rubro_presupuesto', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Presupuesto')),
                ('rubro_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubros', to='carga.plandetrabajos', verbose_name='Plan de Trabajos')),
            ],
            options={
                'verbose_name': 'Rubro de Plan de Trabajos',
                'verbose_name_plural': 'Rubros de Plan de Trabajos',
                'ordering': ['rubro_plan', 'rubro_orden'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPlanDeTrabajosRubro',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('rubro_uuid', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False)),
                ('rubro_nombre', models.CharField(max_length=200, verbose_name='Rubro')),
                ('rubro_orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('rubro_presupuesto', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Presupuesto')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rubro_plan', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.plandetrabajos', verbose_name='Plan de Trabajos')),
            ],
            options={
                'verbose_name': 'historical Rubro de Plan de Trabajos',
                'verbose_name_plural': 'historical Rubros de Plan de Trabajos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveConstraint(
            model_name='fojademedicion',
            name='foja-periodo-unico',
        ),
        migrations.RemoveConstraint(
            model_name='fojademedicion',
            name='foja-numero-unico',
        ),
        migrations.AlterModelOptions(
            name='plandetrabajositem',
            options={'ordering': ['planitem_rubro', 'planitem_orden'], 'verbose_name': 'Item de Plan de Trabajos', 'verbose_name_plural': 'Items de Plan de Trabajos'},
        ),
        migrations.AlterModelOptions(
            name='fojademedicion',
            options={'ordering': ['foja_rubro', 'foja_numero'], 'verbose_name': 'Foja de Medición', 'verbose_name_plural': 'Fojas de Medición'},
        ),
        migrations.RemoveField(
            model_name='plandetrabajositem',
            name='planitem_plan',
        ),
        migrations.RemoveField(
            model_name='historicalplandetrabajositem',
            name='planitem_plan',
        ),
        migrations.RemoveField(
            model_name='fojademedicion',
            name='foja_plan',
        ),
        migrations.RemoveField(
            model_name='historicalfojademedicion',
            name='foja_plan',
        ),
        migrations.AddField(
            model_name='plandetrabajositem',
            name='planitem_rubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='carga.plandetrabajosrubro', verbose_name='Rubro de Plan de Trabajos'),
        ),
        migrations.AddField(
            model_name='historicalplandetrabajositem',
            name='planitem_rubro',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.plandetrabajosrubro', verbose_name='Rubro de Plan de Trabajos'),
        ),
        migrations.AddField(
            model_name='fojademedicion',
            name='foja_rubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fojas', to='carga.plandetrabajosrubro', verbose_name='Rubro de Plan de Trabajos'),
        ),
        migrations.AddField(
            model_name='historicalfojademedicion',
            name='foja_rubro',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.plandetrabajosrubro', verbose_name='Rubro de Plan de Trabajos'),
        ),
        migrations.AddConstraint(
            model_name='fojademedicion',
            constraint=models.UniqueConstraint(fields=('foja_rubro', 'foja_periodo'), name='foja-periodo-unico'),
        ),
        migrations.AddConstraint(
            model_name='fojademedicion',
            constraint=models.UniqueConstraint(fields=('foja_rubro', 'foja_numero'), name='foja-numero-unico'),
        ),
    ]
