# Generated by Django 6.0.6 on 2026-06-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0015_plandetrabajosrubro'),
        ('personalizador', '0014_alter_agente_agente_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalfojademedicion',
            name='foja_inspector',
        ),
        migrations.RemoveField(
            model_name='fojademedicion',
            name='foja_inspector',
        ),
        migrations.AddField(
            model_name='fojademedicion',
            name='foja_inspector',
            field=models.ManyToManyField(blank=True, related_name='foja_inspector', to='personalizador.agente', verbose_name='Inspector'),
        ),
    ]
