# Generated by Django 3.2.4 on 2022-09-08 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0015_auto_20220901_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='obra_conjunto_licitado',
        ),
        migrations.AddField(
            model_name='conjuntolicitado',
            name='conjunto_subconjunto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carga.conjuntolicitado'),
        ),
        migrations.AddField(
            model_name='obra',
            name='obra_conjunto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carga.conjuntolicitado'),
        ),
        migrations.DeleteModel(
            name='SubConjuntoLicitado',
        ),
    ]
