# Generated by Django 3.2.4 on 2022-09-13 13:07

import carga.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0016_auto_20220908_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='certificado_digital',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=carga.models.generate_name),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='certificado_rubro',
            field=models.CharField(choices=[('V', 'Vivienda'), ('F', 'Infraestructura Frentista'), ('T', 'Terreno'), ('R', 'Redeterminación'), ('I', 'Nexos y Redes'), ('C', 'Complementario'), ('M', 'Deductivo')], default='V', max_length=1, verbose_name='Rubro'),
        ),
    ]
