# Generated by Django 6.0.6 on 2026-06-24 15:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0016_alter_fojademedicion_foja_inspector'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplandetrabajos',
            name='trabajos_fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Vigencia'),
        ),
        migrations.AddField(
            model_name='historicalplandetrabajositem',
            name='item_anterior',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.plandetrabajositem', verbose_name='Item Anterior (Plan Previo)'),
        ),
        migrations.AddField(
            model_name='historicalplandetrabajosrubro',
            name='rubro_anterior',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.plandetrabajosrubro', verbose_name='Rubro Anterior (Plan Previo)'),
        ),
        migrations.AddField(
            model_name='plandetrabajos',
            name='trabajos_fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Vigencia'),
        ),
        migrations.AddField(
            model_name='plandetrabajositem',
            name='item_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_siguiente', to='carga.plandetrabajositem', verbose_name='Item Anterior (Plan Previo)'),
        ),
        migrations.AddField(
            model_name='plandetrabajosrubro',
            name='rubro_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rubro_siguiente', to='carga.plandetrabajosrubro', verbose_name='Rubro Anterior (Plan Previo)'),
        ),
    ]
