# Generated by Django 3.2.4 on 2022-09-13 14:02

import carga.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0017_auto_20220913_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='poliza_digital',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=carga.models.generate_name_poliza),
        ),
    ]
