# Generated by Django 6.0.6 on 2026-06-25 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0017_historicalplandetrabajos_trabajos_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fojademedicionitem',
            name='fojaitem_pct_acumulado',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Acumulado %'),
        ),
        migrations.AlterField(
            model_name='historicalfojademedicionitem',
            name='fojaitem_pct_acumulado',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Acumulado %'),
        ),
    ]
