# Generated by Django 6.0.6 on 2026-06-25 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0018_alter_fojademedicionitem_fojaitem_pct_acumulado_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fojademedicion',
            name='foja-periodo-unico',
        ),
    ]
