# Generated by Django 3.2.4 on 2022-09-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0018_poliza_poliza_digital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='obra_nomenclatura',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Nomenclatura Catastral'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='programa_nombre',
            field=models.CharField(max_length=255),
        ),
    ]
