# Generated by Django 4.1.2 on 2022-11-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0019_auto_20220919_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programa',
            options={'verbose_name': 'Programa', 'verbose_name_plural': 'Programas'},
        ),
        migrations.AddField(
            model_name='agente',
            name='agente_nombre_completo',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True, verbose_name='Nombre Completo'),
        ),
    ]
