# Generated by Django 6.0.6 on 2026-06-25 21:25

import carga.models
import django.db.models.deletion
import secretariador.functions
import simple_history.models
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0019_remove_fojademedicion_foja_periodo_unico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplandetrabajosrubro',
            name='rubro_documento_digital',
            field=models.TextField(blank=True, max_length=500, null=True, validators=[secretariador.functions.FileValidator(content_types='application/pdf', max_size=14680064, min_size=None)], verbose_name='Documento Digital'),
        ),
        migrations.AddField(
            model_name='plandetrabajosrubro',
            name='rubro_documento_digital',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=carga.models.generate_name_rubro_documento, validators=[secretariador.functions.FileValidator(content_types='application/pdf', max_size=14680064, min_size=None)], verbose_name='Documento Digital'),
        ),
        migrations.CreateModel(
            name='FojaDeMedicionFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotofoja_uuid', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False)),
                ('fotofoja_archivo', models.FileField(max_length=500, upload_to=carga.models.generate_name_foja_foto, validators=[secretariador.functions.FileValidator(content_types=('image/jpeg', 'image/png'), max_size=14680064, min_size=None)], verbose_name='Foto')),
                ('fotofoja_foja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='carga.fojademedicion', verbose_name='Foja de Medición')),
            ],
            options={
                'verbose_name': 'Foto de Foja de Medición',
                'verbose_name_plural': 'Fotos de Foja de Medición',
            },
        ),
        migrations.CreateModel(
            name='HistoricalFojaDeMedicionFoto',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fotofoja_uuid', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False)),
                ('fotofoja_archivo', models.TextField(max_length=500, validators=[secretariador.functions.FileValidator(content_types=('image/jpeg', 'image/png'), max_size=14680064, min_size=None)], verbose_name='Foto')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('fotofoja_foja', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.fojademedicion', verbose_name='Foja de Medición')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Foto de Foja de Medición',
                'verbose_name_plural': 'historical Fotos de Foja de Medición',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
