# Generated by Django 4.1.2 on 2023-02-01 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0020_alter_programa_options_agente_agente_nombre_completo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoRubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificadorubro_nombre', models.CharField(max_length=100, verbose_name='Rubro')),
                ('certificadorubro_nombre_corto', models.CharField(max_length=1, verbose_name='Rubro Corto')),
            ],
            options={
                'verbose_name_plural': 'Rubros',
            },
        ),
        migrations.AddField(
            model_name='certificado',
            name='certificado_rubro_db',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carga.certificadorubro'),
        ),
    ]
