# Generated by Django 6.0.6 on 2026-06-26 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0021_reconciliar_montos_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratosdigitales',
            name='contratodigital_contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_contrato', to='carga.contrato', verbose_name='Contrato'),
        ),
        migrations.AddField(
            model_name='historicalcontratosdigitales',
            name='contratodigital_contrato',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.contrato', verbose_name='Contrato'),
        ),
        migrations.AddField(
            model_name='historicalresolucionesdigitales',
            name='resoluciondigital_contrato',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.contrato', verbose_name='Contrato'),
        ),
        migrations.AddField(
            model_name='resolucionesdigitales',
            name='resoluciondigital_contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_resolucion', to='carga.contrato', verbose_name='Contrato'),
        ),
    ]
