# Generated by Django 4.1.2 on 2023-02-03 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0021_certificadorubro_certificado_certificado_rubro_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='certificado_rubro_db',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='carga.certificadorubro'),
        ),
    ]
