# Generated by Django 4.1.2 on 2023-03-09 10:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0022_alter_certificado_certificado_rubro_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoFinanciamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificadofinanciamiento_nombre', models.CharField(max_length=100, verbose_name='Financiamiento')),
                ('certificadofinanciamiento_nombre_corto', models.CharField(max_length=1, verbose_name='Financiamiento Corto')),
            ],
            options={
                'verbose_name_plural': 'Financiamiento',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato_fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('contrato_descripcion', models.CharField(default='', max_length=600, verbose_name='Descripción')),
                ('contrato_resolucion', models.CharField(blank=True, max_length=15, null=True, verbose_name='Resolución Aprobatoria')),
                ('contrato_autocarga', models.BooleanField(default=False, editable=False, verbose_name='Contrato importado de formato anterior')),
                ('contrato_decreto', models.CharField(blank=True, max_length=15, null=True, verbose_name='Decreto Aprobatorio(Si Tuviera)')),
                ('contrato_obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.obra')),
            ],
            options={
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.AlterField(
            model_name='certificado',
            name='certificado_rubro_db',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='carga.certificadorubro', verbose_name='Rubro'),
        ),
        migrations.CreateModel(
            name='PlanDeTrabajos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabajos_obra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carga.obra')),
            ],
            options={
                'verbose_name_plural': 'Plan de Trabajos',
            },
        ),
        migrations.CreateModel(
            name='ContratoMonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contratomonto_pesos', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Monto Pesos')),
                ('contratomonto_uvi', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Monto UVI')),
                ('contratomonto_uvi_fecha', models.DateField(blank=True, null=True, verbose_name='Fecha UVI:')),
                ('contratomonto_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.contrato')),
                ('contratomonto_financiamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.certificadofinanciamiento')),
                ('contratomonto_rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.certificadorubro')),
            ],
            options={
                'verbose_name_plural': 'Montos de Contrato',
            },
        ),
    ]
