# Generated by Django 4.1.2 on 2023-04-05 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carga', '0023_certificadofinanciamiento_contrato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='certificado_creador',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificado',
            name='certificado_editor',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificado_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificado',
            name='certificado_fecha_carga',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de carga'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='certificado_fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
    ]
