# Generated by Django 6.0.6 on 2026-06-26 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0023_vincular_documentos_digitales_a_contrato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratosdigitales',
            name='contratodigital_obra',
        ),
        migrations.RemoveField(
            model_name='resolucionesdigitales',
            name='resoluciondigital_obra',
        ),
        migrations.AlterField(
            model_name='contratosdigitales',
            name='contratodigital_contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_contrato', to='carga.contrato', verbose_name='Contrato'),
        ),
        migrations.AlterField(
            model_name='resolucionesdigitales',
            name='resoluciondigital_contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_resolucion', to='carga.contrato', verbose_name='Contrato'),
        ),
    ]
