# Generated by Django 4.1.2 on 2023-04-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0024_certificado_certificado_creador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='certificado_fecha_carga_legacy',
            field=models.BooleanField(default=False, verbose_name='Es Certificado Viejo'),
        ),
    ]
