# Generated by Django 6.0.6 on 2026-06-29 16:26

import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0025_actualizar_verbose_resoluciondigital_numero'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplandetrabajosrubro',
            name='rubro_contratomonto',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.contratomonto', verbose_name='Monto de Contrato'),
        ),
        migrations.AddField(
            model_name='plandetrabajosrubro',
            name='rubro_contratomonto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rubros_plan', to='carga.contratomonto', verbose_name='Monto de Contrato'),
        ),
        migrations.CreateModel(
            name='HistoricalPlanDeTrabajosEtapa',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('etapa_uuid', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False)),
                ('etapa_numero', models.PositiveIntegerField(default=1, editable=False, verbose_name='Número de Etapa')),
                ('etapa_fecha', models.DateField(editable=False, verbose_name='Mes Proyectado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('etapa_rubro', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.plandetrabajosrubro', verbose_name='Rubro de Plan de Trabajos')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Etapa Proyectada de Plan de Trabajos',
                'verbose_name_plural': 'historical Etapas Proyectadas de Plan de Trabajos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PlanDeTrabajosEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa_uuid', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False)),
                ('etapa_numero', models.PositiveIntegerField(default=1, editable=False, verbose_name='Número de Etapa')),
                ('etapa_fecha', models.DateField(editable=False, verbose_name='Mes Proyectado')),
                ('etapa_rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='carga.plandetrabajosrubro', verbose_name='Rubro de Plan de Trabajos')),
            ],
            options={
                'verbose_name': 'Etapa Proyectada de Plan de Trabajos',
                'verbose_name_plural': 'Etapas Proyectadas de Plan de Trabajos',
                'ordering': ['etapa_rubro', 'etapa_numero'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPlanDeTrabajosEtapaItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('etapaitem_uuid', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False)),
                ('etapaitem_pct_proyectado_mes', models.DecimalField(decimal_places=3, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Proyectado del Mes %')),
                ('etapaitem_pct_proyectado_acumulado', models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Acumulado Proyectado %')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('etapaitem_planitem', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.plandetrabajositem', verbose_name='Item del Plan')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('etapaitem_etapa', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.plandetrabajosetapa', verbose_name='Etapa Proyectada')),
            ],
            options={
                'verbose_name': 'historical Item de Etapa Proyectada',
                'verbose_name_plural': 'historical Items de Etapa Proyectada',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PlanDeTrabajosEtapaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapaitem_uuid', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False)),
                ('etapaitem_pct_proyectado_mes', models.DecimalField(decimal_places=3, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Proyectado del Mes %')),
                ('etapaitem_pct_proyectado_acumulado', models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Acumulado Proyectado %')),
                ('etapaitem_etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='carga.plandetrabajosetapa', verbose_name='Etapa Proyectada')),
                ('etapaitem_planitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.plandetrabajositem', verbose_name='Item del Plan')),
            ],
            options={
                'verbose_name': 'Item de Etapa Proyectada',
                'verbose_name_plural': 'Items de Etapa Proyectada',
                'ordering': ['etapaitem_planitem__planitem_orden'],
            },
        ),
        migrations.AddConstraint(
            model_name='plandetrabajosetapa',
            constraint=models.UniqueConstraint(fields=('etapa_rubro', 'etapa_numero'), name='etapa-numero-unico'),
        ),
        migrations.AddConstraint(
            model_name='plandetrabajosetapaitem',
            constraint=models.UniqueConstraint(fields=('etapaitem_etapa', 'etapaitem_planitem'), name='etapaitem-planitem-unico'),
        ),
    ]
