# Generated by Django 4.1.2 on 2023-04-25 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0025_certificado_certificado_fecha_carga_legacy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificado',
            options={'get_latest_by': 'certificado_fecha', 'verbose_name': 'Certificado', 'verbose_name_plural': 'Certificados'},
        ),
    ]
