# Generated by Django 4.2.1 on 2023-05-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0026_alter_certificado_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uvi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uvi_fecha', models.DateField(verbose_name='Fecha UVI:')),
                ('uvi_valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
            ],
            options={
                'verbose_name_plural': 'UVI',
            },
        ),
    ]
