# Generated by Django 6.0.6 on 2026-06-29 21:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0026_agregar_etapas_proyectadas_plan_de_trabajos'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplandetrabajos',
            name='trabajos_meses',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duración (meses)'),
        ),
        migrations.AddField(
            model_name='plandetrabajos',
            name='trabajos_meses',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duración (meses)'),
        ),
    ]
