# Generated by Django 6.0.6 on 2026-06-30 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0027_historicalplandetrabajos_trabajos_meses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplandetrabajos',
            name='trabajos_contrato',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.contrato', verbose_name='Contrato Vinculado'),
        ),
        migrations.AddField(
            model_name='plandetrabajos',
            name='trabajos_contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_trabajo', to='carga.contrato', verbose_name='Contrato Vinculado'),
        ),
    ]
