# Generated by Django 4.2.1 on 2023-08-31 09:52

import carga.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carga', '0027_uvi'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoRubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contratorubro_tipo', models.CharField(max_length=100, verbose_name='Rubro:')),
            ],
            options={
                'verbose_name_plural': 'Rubros de Contrato',
            },
        ),
        migrations.CreateModel(
            name='ResolucionesDigitales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resoluciondigital_numero', models.CharField(max_length=15, verbose_name='Resolución')),
                ('resoluciondigital_archivo', models.FileField(max_length=500, upload_to=carga.models.generate_name_resoluciones)),
                ('resoluciondigital_creador', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('resoluciondigital_editor', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resoluciondigital_editor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Resoluciones Digitales',
            },
        ),
        migrations.CreateModel(
            name='ContratosDigitales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contratodigital_descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('contratodigital_archivo', models.FileField(max_length=500, upload_to=carga.models.generate_name_contratos)),
                ('contratodigital_creador', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('contratodigital_editor', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contratodigital_editor', to=settings.AUTH_USER_MODEL)),
                ('contratodigital_obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.obra')),
                ('contratodigital_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.contratorubro')),
            ],
            options={
                'verbose_name_plural': 'Contratos Digitales',
            },
        ),
    ]
