# Generated by Django 4.2.1 on 2023-11-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0028_contratorubro_resolucionesdigitales_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='INDEC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(verbose_name='Fecha de Medición')),
                ('indec_manodeobra', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Mano de Obra')),
                ('indec_albanileria', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Albañilería')),
                ('indec_carpinterías', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Carpinterías')),
                ('indec_andamios', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Andamios')),
                ('indec_iluminación', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Artefactos de iluminación y cableado')),
                ('indec_pvc', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Caños de PVC para instalaciones varias')),
                ('indec_gastos', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Gastos Generales')),
                ('indec_artefactos', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Artefactos para baño y grifería')),
                ('indec_hormigon', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Hormigón')),
                ('indec_valvulas', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Válvulas de bronce')),
                ('indec_electrobombas', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Electrobombas')),
                ('indec_quimicos', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Productos Químicos')),
                ('indec_motores', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Motores eléctricos y equipos de aire acondicionado')),
                ('indec_asfaltos', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Asfaltos, combustibles y lubricantes')),
                ('indec_medidores', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Medidores de caudal')),
                ('indec_membrana', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Membrana impermeabilizante')),
                ('indec_equipo', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Equipo - Amortización de equipo')),
                ('indec_pisos', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Pisos y revestimientos')),
                ('indec_aceros', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Aceros - Hierro aletado')),
                ('indec_cemento', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Cemento')),
                ('indec_arena', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Arena')),
                ('indec_costo_financiero', models.DecimalField(decimal_places=10, default=18.85, max_digits=20, verbose_name='Costo Financiero')),
                ('indec_transporte', models.DecimalField(decimal_places=10, default=134.98, max_digits=20, verbose_name='Transporte')),
            ],
            options={
                'verbose_name_plural': 'INDEC',
            },
        ),
        migrations.AddField(
            model_name='resolucionesdigitales',
            name='resoluciondigital_descripcion',
            field=models.TextField(default='Resolucion Adjudicacion', verbose_name='Descripción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resolucionesdigitales',
            name='resoluciondigital_obra',
            field=models.ManyToManyField(blank=True, related_name='obra_resoluciones', to='carga.obra', verbose_name='Obras'),
        ),
        migrations.AlterField(
            model_name='contratosdigitales',
            name='contratodigital_descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.RemoveField(
            model_name='contratosdigitales',
            name='contratodigital_obra',
        ),
        migrations.AddField(
            model_name='contratosdigitales',
            name='contratodigital_obra',
            field=models.ManyToManyField(blank=True, related_name='obra_contratos', to='carga.obra', verbose_name='Obras'),
        ),
    ]
