# Generated by Django 6.0.6 on 2026-06-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0028_historicalplandetrabajos_trabajos_contrato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplandetrabajos',
            name='trabajos_fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio de Obra'),
        ),
        migrations.AddField(
            model_name='plandetrabajos',
            name='trabajos_fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio de Obra'),
        ),
    ]
