# Generated by Django 4.2.1 on 2023-12-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0029_indec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratosdigitales',
            name='contratodigital_nombre_archivo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Archivo'),
        ),
    ]
