# Generated by Django 6.0.6 on 2026-07-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0029_plandetrabajos_fecha_inicio'),
        ('personalizador', '0015_historicalrepresentantetecnico_representantetecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='obra_representantetecnico',
            field=models.ManyToManyField(related_name='obra_representantetecnico', to='personalizador.representantetecnico', verbose_name='Representante Técnico'),
        ),
    ]
