# Generated by Django 5.0.3 on 2024-05-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0030_contratosdigitales_contratodigital_nombre_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('provincia_nombre', models.CharField(max_length=33, verbose_name='Nombre Provincia')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'ordering': ['provincia_nombre'],
            },
        ),
    ]
