# Generated by Django 6.0.6 on 2026-07-01 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0030_obra_obra_representantetecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='fojademedicion',
            name='foja_legacy',
            field=models.BooleanField(default=False, verbose_name='Es Foja Vieja'),
        ),
        migrations.AddField(
            model_name='historicalfojademedicion',
            name='foja_legacy',
            field=models.BooleanField(default=False, verbose_name='Es Foja Vieja'),
        ),
        migrations.AddField(
            model_name='historicalplandetrabajosrubro',
            name='rubro_foja_numero_inicial',
            field=models.PositiveIntegerField(default=1, help_text='Número de la primera Foja de Medición real de este rubro. Permite continuar la numeración cuando hubo fojas anteriores cargadas fuera del sistema.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Foja Inicial'),
        ),
        migrations.AddField(
            model_name='plandetrabajosrubro',
            name='rubro_foja_numero_inicial',
            field=models.PositiveIntegerField(default=1, help_text='Número de la primera Foja de Medición real de este rubro. Permite continuar la numeración cuando hubo fojas anteriores cargadas fuera del sistema.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Foja Inicial'),
        ),
    ]
