# Generated by Django 6.0.6 on 2026-07-01 21:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0031_fojademedicion_foja_legacy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='certificado_acum_pct',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Acumulado %'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='certificado_ante_pct',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Anterior %'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='certificado_mes_pct',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Mes %'),
        ),
        migrations.AlterField(
            model_name='historicalcertificado',
            name='certificado_acum_pct',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Acumulado %'),
        ),
        migrations.AlterField(
            model_name='historicalcertificado',
            name='certificado_ante_pct',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Anterior %'),
        ),
        migrations.AlterField(
            model_name='historicalcertificado',
            name='certificado_mes_pct',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Mes %'),
        ),
    ]
