# Generated by Django 5.0.3 on 2025-05-27 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0031_provincia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aseguradora',
            options={'ordering': ['aseguradora_nombre'], 'verbose_name': 'Aseguradora', 'verbose_name_plural': 'Aseguradoras'},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['empresa_nombre'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
    ]
