# Generated by Django 6.0.6 on 2026-07-02 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0032_fix_certificado_pct_decimal_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='certificado_tipo',
            field=models.CharField(choices=[('PARCIAL', 'Certificado Parcial de Obra'), ('ANTICIPO', 'Certificado de Anticipo'), ('HECHO_CONSUMADO', 'Hecho Consumado'), ('LEGACY', 'Legacy / Sin Clasificar')], default='LEGACY', max_length=15, verbose_name='Tipo de Certificado'),
        ),
        migrations.AddField(
            model_name='historicalcertificado',
            name='certificado_tipo',
            field=models.CharField(choices=[('PARCIAL', 'Certificado Parcial de Obra'), ('ANTICIPO', 'Certificado de Anticipo'), ('HECHO_CONSUMADO', 'Hecho Consumado'), ('LEGACY', 'Legacy / Sin Clasificar')], default='LEGACY', max_length=15, verbose_name='Tipo de Certificado'),
        ),
        migrations.AddField(
            model_name='historicalplandetrabajosrubro',
            name='rubro_certificado_rubro',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Rubro normalizado usado para ubicar los montos por financiamiento (ContratoMonto) al generar certificados desde una Foja.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.certificadorubro', verbose_name='Rubro de Certificado'),
        ),
        migrations.AddField(
            model_name='plandetrabajosrubro',
            name='rubro_certificado_rubro',
            field=models.ForeignKey(blank=True, help_text='Rubro normalizado usado para ubicar los montos por financiamiento (ContratoMonto) al generar certificados desde una Foja.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='carga.certificadorubro', verbose_name='Rubro de Certificado'),
        ),
    ]
