# Generated by Django 5.2.4 on 2025-07-23 13:51

import carga.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0032_alter_aseguradora_options_alter_empresa_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agente',
            options={'ordering': ['agente_nombre', 'agente_apellido'], 'verbose_name_plural': 'Agentes'},
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['area_nombre'], 'verbose_name': 'Area', 'verbose_name_plural': 'Areas'},
        ),
        migrations.AlterModelOptions(
            name='certificado',
            options={'get_latest_by': 'certificado_fecha', 'ordering': ['certificado_fecha', 'certificado_expediente'], 'verbose_name': 'Certificado', 'verbose_name_plural': 'Certificados'},
        ),
        migrations.AlterModelOptions(
            name='certificadofinanciamiento',
            options={'ordering': ['certificadofinanciamiento_nombre'], 'verbose_name_plural': 'Financiamiento'},
        ),
        migrations.AlterModelOptions(
            name='certificadorubro',
            options={'ordering': ['certificadorubro_nombre'], 'verbose_name_plural': 'Rubros'},
        ),
        migrations.AlterModelOptions(
            name='conjuntolicitado',
            options={'ordering': ['conjunto_nombre'], 'verbose_name_plural': 'Conjuntos Licitados'},
        ),
        migrations.AlterModelOptions(
            name='contrato',
            options={'ordering': ['contrato_fecha'], 'verbose_name_plural': 'Contratos'},
        ),
        migrations.AlterModelOptions(
            name='contratomonto',
            options={'ordering': ['contratomonto_contrato'], 'verbose_name_plural': 'Montos de Contrato'},
        ),
        migrations.AlterModelOptions(
            name='contratorubro',
            options={'ordering': ['contratorubro_tipo'], 'verbose_name_plural': 'Rubros de Contrato'},
        ),
        migrations.AlterModelOptions(
            name='contratosdigitales',
            options={'ordering': ['id'], 'verbose_name_plural': 'Contratos Digitales'},
        ),
        migrations.AlterModelOptions(
            name='indec',
            options={'ordering': ['mes'], 'verbose_name_plural': 'INDEC'},
        ),
        migrations.AlterModelOptions(
            name='legacypoliza',
            options={'ordering': ['legacy_poliza_fecha'], 'verbose_name': 'Legacy_Póliza', 'verbose_name_plural': 'Legacy_Pólizas'},
        ),
        migrations.AlterModelOptions(
            name='obra',
            options={'ordering': ['obra_programa', 'obra_convenio', 'obra_nombre'], 'verbose_name': 'Obra', 'verbose_name_plural': 'Obras'},
        ),
        migrations.AlterModelOptions(
            name='poliza',
            options={'ordering': ['poliza_fecha'], 'verbose_name': 'Póliza', 'verbose_name_plural': 'Pólizas'},
        ),
        migrations.AlterModelOptions(
            name='poliza_movimiento',
            options={'ordering': ['poliza_movimiento_fecha'], 'verbose_name': 'Poliza_Movimiento', 'verbose_name_plural': 'Polizas_Movimiento'},
        ),
        migrations.AlterModelOptions(
            name='programa',
            options={'ordering': ['programa_nombre'], 'verbose_name': 'Programa', 'verbose_name_plural': 'Programas'},
        ),
        migrations.AlterModelOptions(
            name='receptor',
            options={'ordering': ['receptor_nombre'], 'verbose_name': 'Receptor', 'verbose_name_plural': 'Receptores'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['id'], 'verbose_name_plural': 'Region'},
        ),
        migrations.AlterModelOptions(
            name='resolucionesdigitales',
            options={'ordering': ['resoluciondigital_numero'], 'verbose_name_plural': 'Resoluciones Digitales'},
        ),
        migrations.AlterModelOptions(
            name='uvi',
            options={'ordering': ['uvi_fecha'], 'verbose_name_plural': 'UVI'},
        ),
        migrations.AlterField(
            model_name='agente',
            name='agente_apellido',
            field=models.CharField(max_length=60, verbose_name='Apellido/s'),
        ),
        migrations.AlterField(
            model_name='agente',
            name='agente_dni',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='agente',
            name='agente_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='agente',
            name='agente_nombre',
            field=models.CharField(max_length=60, verbose_name='Nombre/s'),
        ),
        migrations.AlterField(
            model_name='agente',
            name='agente_telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='aseguradora',
            name='aseguradora_nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre Compañía Aseguradora'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='certificado_obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.obra', verbose_name='Obra'),
        ),
        migrations.AlterField(
            model_name='conjuntolicitado',
            name='conjunto_subconjunto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carga.conjuntolicitado', verbose_name='Conjunto Licitado'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='contrato_obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.obra', verbose_name='Obra'),
        ),
        migrations.AlterField(
            model_name='contratomonto',
            name='contratomonto_contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.contrato', verbose_name='Contrato'),
        ),
        migrations.AlterField(
            model_name='contratomonto',
            name='contratomonto_financiamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.certificadofinanciamiento', verbose_name='Financiamiento'),
        ),
        migrations.AlterField(
            model_name='contratomonto',
            name='contratomonto_rubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.certificadorubro', verbose_name='Rubro Certificado'),
        ),
        migrations.AlterField(
            model_name='contratosdigitales',
            name='contratodigital_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.contratorubro', verbose_name='Rubro Contrato'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='empresa_correo_p',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Dirección de Correo Primaria'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='empresa_correo_s',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Dirección de Correo Alternativa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='empresa_cuit',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='CUIT'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='empresa_inscripcion',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Inscripción'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='empresa_nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre Empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='empresa_titular_dni',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='empresa_titular_titulo',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Titulo Representante'),
        ),
        migrations.AlterField(
            model_name='legacypoliza',
            name='legacy_poliza_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.area', verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='legacypoliza',
            name='legacy_poliza_aseguradora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.aseguradora', verbose_name='Aseguradora'),
        ),
        migrations.AlterField(
            model_name='legacypoliza',
            name='legacy_poliza_receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.receptor', verbose_name='Receptor'),
        ),
        migrations.AlterField(
            model_name='legacypoliza',
            name='legacy_poliza_tomador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.empresa', verbose_name='Tomador'),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='localidad_centroide_lat',
            field=models.DecimalField(blank=True, decimal_places=13, max_digits=15, null=True, verbose_name='Latitud Centroide'),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='localidad_centroide_lon',
            field=models.DecimalField(blank=True, decimal_places=13, max_digits=15, null=True, verbose_name='Longitud Centroide'),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='localidad_departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='carga.departamento', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='localidad_funcion',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Función'),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='localidad_municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.municipio', verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='municipio_departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.departamento', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='municipio_nombre',
            field=models.CharField(max_length=40, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='municipio_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carga.region', verbose_name='Región'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='obra_conjunto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carga.conjuntolicitado', verbose_name='Conjunto Licitado'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='obra_contrato_nacion_pesos',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Nación en Pesos'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='obra_contrato_nacion_uvi',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Nación en UVI'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='obra_contrato_nacion_uvi_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha UVI Nación'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='obra_contrato_provincia_pesos',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Provincia en Pesos'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='obra_contrato_provincia_uvi',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Provincia en UVI'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='obra_contrato_provincia_uvi_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha UVI Provicia'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='obra_contrato_terceros_pesos',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Terceros en Pesos'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='obra_contrato_terceros_uvi',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Terceros en UVI'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='obra_contrato_terceros_uvi_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha UVI Terceros'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='obra_nombre',
            field=models.TextField(help_text='Nombre de la Obra tal como figura en el contrato', verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='obra_observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='obra_programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.programa', verbose_name='Programa'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='poliza_aseguradora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.aseguradora', verbose_name='Aseguradora'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='poliza_digital',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=carga.models.generate_name_poliza, verbose_name='Póliza Digital'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='poliza_obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.obra', verbose_name='Obra'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='poliza_tomador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.empresa', verbose_name='Tomador'),
        ),
        migrations.AlterField(
            model_name='poliza_movimiento',
            name='poliza_movimiento_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.area', verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='poliza_movimiento',
            name='poliza_movimiento_numero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.poliza', verbose_name='Póliza'),
        ),
        migrations.AlterField(
            model_name='poliza_movimiento',
            name='poliza_movimiento_receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.receptor', verbose_name='Receptor'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='programa_nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='prototipo',
            name='prototipo_cantidad',
            field=models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Cantidad del Prototipo'),
        ),
        migrations.AlterField(
            model_name='prototipo',
            name='prototipo_discapacitado',
            field=models.BooleanField(default=False, verbose_name='Es Prototipo para Discapacitado'),
        ),
        migrations.AlterField(
            model_name='prototipo',
            name='prototipo_incremento',
            field=models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Incremento Porcentual por Infraestructura'),
        ),
        migrations.AlterField(
            model_name='prototipo',
            name='prototipo_obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carga.obra', verbose_name='Obra'),
        ),
        migrations.AlterField(
            model_name='prototipo',
            name='prototipo_superficie',
            field=models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Superficie del Prototipo'),
        ),
        migrations.AlterField(
            model_name='prototipo',
            name='prototipo_tipo',
            field=models.CharField(choices=[('1', '1 Dormitorio'), ('2', '2 Dormitorios'), ('3', '3 Dormitorios'), ('4', '4 Dormitorios'), ('o', 'Otro')], max_length=1, verbose_name='Tipo de Prototipo'),
        ),
        migrations.AlterField(
            model_name='prototipo',
            name='prototipo_uvi',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='UVIs x M2'),
        ),
    ]
