# Generated by Django 6.0.6 on 2026-07-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0033_agregar_certificado_tipo_y_rubro_certificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='certificado_ley27397_detalle',
            field=models.JSONField(blank=True, editable=False, help_text='Snapshot de auditoría de los tramos (%, cotización UVI y fecha) usados para convertir este certificado a pesos. No es fuente de verdad: certificados futuros siempre recalculan recorriendo el historial real.', null=True, verbose_name='Detalle de tramos Ley 27397'),
        ),
        migrations.AddField(
            model_name='historicalcertificado',
            name='certificado_ley27397_detalle',
            field=models.JSONField(blank=True, editable=False, help_text='Snapshot de auditoría de los tramos (%, cotización UVI y fecha) usados para convertir este certificado a pesos. No es fuente de verdad: certificados futuros siempre recalculan recorriendo el historial real.', null=True, verbose_name='Detalle de tramos Ley 27397'),
        ),
    ]
