# Generated by Django 5.2.10 on 2026-06-02 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0033_alter_agente_options_alter_area_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conjuntolicitado',
            options={'ordering': ['id', 'conjunto_nombre'], 'verbose_name_plural': 'Conjuntos Licitados'},
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='certificado_creador',
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='certificado_editor',
        ),
        migrations.RemoveField(
            model_name='contratosdigitales',
            name='contratodigital_creador',
        ),
        migrations.RemoveField(
            model_name='contratosdigitales',
            name='contratodigital_editor',
        ),
        migrations.RemoveField(
            model_name='poliza',
            name='poliza_creador',
        ),
        migrations.RemoveField(
            model_name='poliza',
            name='poliza_editor',
        ),
        migrations.RemoveField(
            model_name='resolucionesdigitales',
            name='resoluciondigital_creador',
        ),
        migrations.RemoveField(
            model_name='resolucionesdigitales',
            name='resoluciondigital_editor',
        ),
    ]
