# Generated by Django 6.0.6 on 2026-07-02 22:44

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0034_agregar_ley27397_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='certificado_descuento_anticipo_pesos',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Descuento de Anticipo en Pesos'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='certificado_descuento_anticipo_uvi',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Descuento de Anticipo en UVI'),
        ),
        migrations.AddField(
            model_name='historicalcertificado',
            name='certificado_descuento_anticipo_pesos',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Descuento de Anticipo en Pesos'),
        ),
        migrations.AddField(
            model_name='historicalcertificado',
            name='certificado_descuento_anticipo_uvi',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Descuento de Anticipo en UVI'),
        ),
        # GeneratedFields no admiten AlterField in-place (Django exige remove + re-add
        # cuando cambia la expresión).
        migrations.RemoveField(
            model_name='certificado',
            name='certificado_monto_cobrar',
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='certificado_monto_cobrar_uvi',
        ),
        migrations.AddField(
            model_name='certificado',
            name='certificado_monto_cobrar',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('certificado_monto_pesos'), '-', models.F('certificado_devolucion_monto')), '-', models.F('certificado_descuento_anticipo_pesos')), output_field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Monto a Cobrar Pesos')),
        ),
        migrations.AddField(
            model_name='certificado',
            name='certificado_monto_cobrar_uvi',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('certificado_monto_uvi'), '-', models.F('certificado_devolucion_monto_uvi')), '-', models.F('certificado_descuento_anticipo_uvi')), output_field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Monto a Cobrar UVI')),
        ),
    ]
