# Generated by Django 6.0.6 on 2026-07-02 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0035_agregar_descuento_anticipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='certificado_contrato_origen',
            field=models.ForeignKey(blank=True, help_text='Obligatorio para certificados de Hecho Consumado: el Contrato cuya Resolución/Decreto ampara el certificado sin Foja.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carga.contrato', verbose_name='Contrato/Resolución de Origen'),
        ),
        migrations.AddField(
            model_name='historicalcertificado',
            name='certificado_contrato_origen',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Obligatorio para certificados de Hecho Consumado: el Contrato cuya Resolución/Decreto ampara el certificado sin Foja.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.contrato', verbose_name='Contrato/Resolución de Origen'),
        ),
    ]
