# Generated by Django 6.0.6 on 2026-07-03 12:37

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0036_agregar_contrato_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='certificado_fondoreparo_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('5'), help_text='Retención sobre el importe total del certificado, sin descontar el anticipo financiero. No aplica a certificados de Anticipo.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Fondo de Reparo %'),
        ),
        migrations.AddField(
            model_name='historicalcertificado',
            name='certificado_fondoreparo_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('5'), help_text='Retención sobre el importe total del certificado, sin descontar el anticipo financiero. No aplica a certificados de Anticipo.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Fondo de Reparo %'),
        ),
    ]
