# Generated by Django 6.0.6 on 2026-07-03 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0037_certificado_certificado_fondoreparo_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='certificado_anticipo_pct',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, help_text='Sólo aplica a certificados de Anticipo: % cargado a mano sobre el monto de contrato del financiamiento (todos los rubros/contratos de la obra para ese financiamiento, no un rubro puntual).', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% de Anticipo'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='certificado_descuento_anticipo_pct',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, help_text='% efectivo del monto bruto de este certificado retenido para amortizar anticipos (calculado automáticamente, ver certificacion.aplicar_descuento_anticipo).', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Descuento de Anticipo %'),
        ),
        migrations.AddField(
            model_name='historicalcertificado',
            name='certificado_anticipo_pct',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, help_text='Sólo aplica a certificados de Anticipo: % cargado a mano sobre el monto de contrato del financiamiento (todos los rubros/contratos de la obra para ese financiamiento, no un rubro puntual).', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% de Anticipo'),
        ),
        migrations.AddField(
            model_name='historicalcertificado',
            name='certificado_descuento_anticipo_pct',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, help_text='% efectivo del monto bruto de este certificado retenido para amortizar anticipos (calculado automáticamente, ver certificacion.aplicar_descuento_anticipo).', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Descuento de Anticipo %'),
        ),
    ]
