# Generated by Django 6.0.6 on 2026-07-04 12:15

import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0039_backfill_certificado_anticipo_pct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='certificado_etapa_pct',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, help_text='Sólo aplica a certificados de Etapa: snapshot del % fijo del tramo (certificado_contrato_tramo.tramo_pct_pago) usado para calcular el monto.', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% de Etapa'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='contrato_certificacion_por_etapas',
            field=models.BooleanField(default=False, help_text='Si está tildado, este Contrato no genera certificados Parciales (%mes de la Foja): en su lugar se certifica en tramos fijos de %, disparados cuando el avance acumulado de la Foja alcanza el umbral de cada tramo (ver ContratoTramoPago).', verbose_name='Certificación por Etapas'),
        ),
        migrations.AddField(
            model_name='historicalcertificado',
            name='certificado_etapa_pct',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, help_text='Sólo aplica a certificados de Etapa: snapshot del % fijo del tramo (certificado_contrato_tramo.tramo_pct_pago) usado para calcular el monto.', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% de Etapa'),
        ),
        migrations.AddField(
            model_name='historicalcontrato',
            name='contrato_certificacion_por_etapas',
            field=models.BooleanField(default=False, help_text='Si está tildado, este Contrato no genera certificados Parciales (%mes de la Foja): en su lugar se certifica en tramos fijos de %, disparados cuando el avance acumulado de la Foja alcanza el umbral de cada tramo (ver ContratoTramoPago).', verbose_name='Certificación por Etapas'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='certificado_tipo',
            field=models.CharField(choices=[('PARCIAL', 'Certificado Parcial de Obra'), ('ANTICIPO', 'Certificado de Anticipo'), ('HECHO_CONSUMADO', 'Hecho Consumado'), ('ETAPA', 'Certificado de Etapa de Contrato'), ('LEGACY', 'Legacy / Sin Clasificar')], default='LEGACY', max_length=15, verbose_name='Tipo de Certificado'),
        ),
        migrations.AlterField(
            model_name='historicalcertificado',
            name='certificado_tipo',
            field=models.CharField(choices=[('PARCIAL', 'Certificado Parcial de Obra'), ('ANTICIPO', 'Certificado de Anticipo'), ('HECHO_CONSUMADO', 'Hecho Consumado'), ('ETAPA', 'Certificado de Etapa de Contrato'), ('LEGACY', 'Legacy / Sin Clasificar')], default='LEGACY', max_length=15, verbose_name='Tipo de Certificado'),
        ),
        migrations.CreateModel(
            name='ContratoTramoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tramo_uuid', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False)),
                ('tramo_numero', models.PositiveIntegerField(default=1, editable=False, verbose_name='Número de Tramo')),
                ('tramo_pct_pago', models.DecimalField(decimal_places=2, help_text='% fijo del monto total del Contrato (todos los rubros/financiamiento) que se certifica cuando este tramo se dispara.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% del Contrato a certificar')),
                ('tramo_pct_disparador', models.DecimalField(decimal_places=2, help_text='Umbral de % de avance acumulado (Foja de Medición) a partir del cual este tramo queda habilitado para certificarse.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% de Avance Acumulado que dispara el tramo')),
                ('tramo_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramos_pago', to='carga.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Tramo de Pago de Contrato',
                'verbose_name_plural': 'Tramos de Pago de Contrato',
                'ordering': ['tramo_contrato', 'tramo_numero'],
            },
        ),
        migrations.AddField(
            model_name='certificado',
            name='certificado_contrato_tramo',
            field=models.OneToOneField(blank=True, help_text='Obligatorio para certificados de Etapa: el Tramo de Pago de Contrato que este certificado salda.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificado_etapa', to='carga.contratotramopago', verbose_name='Tramo de Contrato'),
        ),
        migrations.AddField(
            model_name='historicalcertificado',
            name='certificado_contrato_tramo',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Obligatorio para certificados de Etapa: el Tramo de Pago de Contrato que este certificado salda.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.contratotramopago', verbose_name='Tramo de Contrato'),
        ),
        migrations.CreateModel(
            name='HistoricalContratoTramoPago',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tramo_uuid', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False)),
                ('tramo_numero', models.PositiveIntegerField(default=1, editable=False, verbose_name='Número de Tramo')),
                ('tramo_pct_pago', models.DecimalField(decimal_places=2, help_text='% fijo del monto total del Contrato (todos los rubros/financiamiento) que se certifica cuando este tramo se dispara.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% del Contrato a certificar')),
                ('tramo_pct_disparador', models.DecimalField(decimal_places=2, help_text='Umbral de % de avance acumulado (Foja de Medición) a partir del cual este tramo queda habilitado para certificarse.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% de Avance Acumulado que dispara el tramo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tramo_contrato', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'historical Tramo de Pago de Contrato',
                'verbose_name_plural': 'historical Tramos de Pago de Contrato',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name='contratotramopago',
            constraint=models.UniqueConstraint(fields=('tramo_contrato', 'tramo_numero'), name='tramo-numero-unico'),
        ),
    ]
