# Generated by Django 6.0.6 on 2026-07-06 22:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0040_certificado_certificado_etapa_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='certificado_anticipo_acumulado',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, help_text='Sólo aplica a certificados de Anticipo: certificado_anticipo_anterior + certificado_anticipo_pct (calculado automáticamente, ver certificacion.calcular_monto_anticipo).', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% de Anticipo Acumulado'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='certificado_anticipo_anterior',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, help_text='Sólo aplica a certificados de Anticipo: snapshot de la suma de certificado_anticipo_pct de los Anticipos previos de esta obra+financiamiento (calculado automáticamente, ver certificacion.calcular_monto_anticipo).', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% de Anticipo Anterior'),
        ),
        migrations.AddField(
            model_name='historicalcertificado',
            name='certificado_anticipo_acumulado',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, help_text='Sólo aplica a certificados de Anticipo: certificado_anticipo_anterior + certificado_anticipo_pct (calculado automáticamente, ver certificacion.calcular_monto_anticipo).', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% de Anticipo Acumulado'),
        ),
        migrations.AddField(
            model_name='historicalcertificado',
            name='certificado_anticipo_anterior',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, help_text='Sólo aplica a certificados de Anticipo: snapshot de la suma de certificado_anticipo_pct de los Anticipos previos de esta obra+financiamiento (calculado automáticamente, ver certificacion.calcular_monto_anticipo).', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% de Anticipo Anterior'),
        ),
    ]
