# Generated by Django 6.0.6 on 2026-07-06 23:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0041_certificado_certificado_anticipo_acumulado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='certificado_anticipo_saldo_pct',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, help_text='Aplica a certificados de Anticipo, Parcial y Hecho Consumado: snapshot del % (sobre el monto de contrato del financiamiento) de anticipo otorgado y aún no recuperado, justo después de este certificado — sube al otorgarse un Anticipo, baja cuando un Parcial/Hecho Consumado le aplica descuento de anticipo. A diferencia de certificado_anticipo_acumulado (bruto otorgado, nunca baja), este campo neteado sirve para verificar/reportar que el anticipo llegue a 0% cuando la obra termina de certificarse (ver certificacion.calcular_monto_anticipo, certificacion.aplicar_descuento_anticipo).', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% Saldo Pendiente de Anticipo'),
        ),
        migrations.AddField(
            model_name='historicalcertificado',
            name='certificado_anticipo_saldo_pct',
            field=models.DecimalField(decimal_places=3, default=0, editable=False, help_text='Aplica a certificados de Anticipo, Parcial y Hecho Consumado: snapshot del % (sobre el monto de contrato del financiamiento) de anticipo otorgado y aún no recuperado, justo después de este certificado — sube al otorgarse un Anticipo, baja cuando un Parcial/Hecho Consumado le aplica descuento de anticipo. A diferencia de certificado_anticipo_acumulado (bruto otorgado, nunca baja), este campo neteado sirve para verificar/reportar que el anticipo llegue a 0% cuando la obra termina de certificarse (ver certificacion.calcular_monto_anticipo, certificacion.aplicar_descuento_anticipo).', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% Saldo Pendiente de Anticipo'),
        ),
    ]
