# Generated by Django 6.0.6 on 2026-07-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0042_certificado_certificado_anticipo_saldo_pct_and_more'),
        ('personalizador', '0015_historicalrepresentantetecnico_representantetecnico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='obra_inspector',
            field=models.ManyToManyField(blank=True, related_name='obra_inspector', to='personalizador.agente', verbose_name='Inspector'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='obra_representantetecnico',
            field=models.ManyToManyField(blank=True, related_name='obra_representantetecnico', to='personalizador.representantetecnico', verbose_name='Representante Técnico'),
        ),
    ]
