# Generated by Django 6.0.6 on 2026-07-14 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0044_eliminar_representantetecnico_placeholder'),
        ('secretariador', '0009_historicalinstrumentoslegalesresoluciones_instrumentolegalresoluciones_accion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resolucionesdigitales',
            name='resoluciondigital_contrato',
        ),
        migrations.AddField(
            model_name='conjuntolicitado',
            name='conjunto_resolucion_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secretariador.instrumentoslegalesresoluciones', verbose_name='Resolución de Adjudicación'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='contrato_resolucion_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secretariador.instrumentoslegalesresoluciones', verbose_name='Resolución de Adjudicación'),
        ),
        migrations.AddField(
            model_name='historicalconjuntolicitado',
            name='conjunto_resolucion_fk',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='secretariador.instrumentoslegalesresoluciones', verbose_name='Resolución de Adjudicación'),
        ),
        migrations.AddField(
            model_name='historicalcontrato',
            name='contrato_resolucion_fk',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='secretariador.instrumentoslegalesresoluciones', verbose_name='Resolución de Adjudicación'),
        ),
        migrations.AddField(
            model_name='historicalobra',
            name='obra_resolucion_fk',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='secretariador.instrumentoslegalesresoluciones', verbose_name='Resolución de Adjudicación'),
        ),
        migrations.AddField(
            model_name='obra',
            name='obra_resolucion_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secretariador.instrumentoslegalesresoluciones', verbose_name='Resolución de Adjudicación'),
        ),
        migrations.DeleteModel(
            name='HistoricalResolucionesDigitales',
        ),
        migrations.DeleteModel(
            name='ResolucionesDigitales',
        ),
    ]
