# Generated by Django 6.0.6 on 2026-07-15 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0045_eliminar_resoluciones_digitales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='certificado_contrato_origen',
            field=models.ForeignKey(blank=True, help_text='Obligatorio para certificados de Hecho Consumado: el Contrato cuya Resolución/Decreto ampara el certificado sin Foja.', null=True, on_delete=django.db.models.deletion.PROTECT, to='carga.contrato', verbose_name='Contrato/Resolución de Origen'),
        ),
    ]
