# Generated by Django 6.0.6 on 2026-07-15 17:00

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0046_protect_certificado_contrato_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalobra',
            name='obra_georeferencia',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Georeferencia'),
        ),
        migrations.AddField(
            model_name='obra',
            name='obra_georeferencia',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Georeferencia'),
        ),
    ]
