# Generated by Django 6.0.6 on 2026-07-16 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0047_historicalobra_obra_georeferencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='certificado_rubro_db',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='carga.certificadorubro', verbose_name='Rubro'),
        ),
        migrations.AlterField(
            model_name='conjuntolicitado',
            name='conjunto_subconjunto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carga.conjuntolicitado', verbose_name='Conjunto Licitado'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='municipio_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carga.region', verbose_name='Región'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='obra_conjunto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carga.conjuntolicitado', verbose_name='Conjunto Licitado'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='obra_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carga.region', verbose_name='Región'),
        ),
        migrations.AlterField(
            model_name='plandetrabajos',
            name='trabajos_obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.obra'),
        ),
        migrations.AlterField(
            model_name='prototipo',
            name='prototipo_obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.obra', verbose_name='Obra'),
        ),
    ]
