# Generated by Django 6.0.6 on 2026-07-27 12:42

import carga.models
import core.validators
import django.db.models.deletion
import simple_history.models
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0048_alter_certificado_certificado_rubro_db_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalObraDocumento',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('obradocumento_uuid', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False)),
                ('obradocumento_descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('obradocumento_archivo', models.TextField(max_length=500, validators=[core.validators.FileValidator(content_types=('application/pdf',), max_size=14680064, min_size=None)], verbose_name='Archivo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('obradocumento_obra', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.obra', verbose_name='Obra')),
            ],
            options={
                'verbose_name': 'historical Documento de Obra',
                'verbose_name_plural': 'historical Documentos de Obra',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ObraDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obradocumento_uuid', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False)),
                ('obradocumento_descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('obradocumento_archivo', models.FileField(max_length=500, upload_to=carga.models.generate_name_obra_documento, validators=[core.validators.FileValidator(content_types=('application/pdf',), max_size=14680064, min_size=None)], verbose_name='Archivo')),
                ('obradocumento_obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_obra', to='carga.obra', verbose_name='Obra')),
            ],
            options={
                'verbose_name': 'Documento de Obra',
                'verbose_name_plural': 'Documentos de Obra',
                'ordering': ['id'],
            },
        ),
    ]
