# Generated by Django 6.0.6 on 2026-07-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0049_historicalobradocumento_obradocumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='conjuntolicitado',
            name='conjunto_resolucion_acta',
            field=models.CharField(blank=True, default='1', max_length=3, verbose_name='Acta'),
        ),
        migrations.AddField(
            model_name='conjuntolicitado',
            name='conjunto_resolucion_ano',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='conjuntolicitado',
            name='conjunto_resolucion_jurisdiccion',
            field=models.CharField(blank=True, default='10', max_length=3, verbose_name='Jurisdicción'),
        ),
        migrations.AddField(
            model_name='conjuntolicitado',
            name='conjunto_resolucion_numero',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='conjuntolicitado',
            name='conjunto_resolucion_tipo',
            field=models.CharField(blank=True, choices=[('P', 'Resolución de Presidencia'), ('D', 'Resolución de Directorio')], default='P', max_length=1, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='contrato_resolucion_acta',
            field=models.CharField(blank=True, default='1', max_length=3, verbose_name='Acta'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='contrato_resolucion_ano',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='contrato_resolucion_jurisdiccion',
            field=models.CharField(blank=True, default='10', max_length=3, verbose_name='Jurisdicción'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='contrato_resolucion_numero',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='contrato_resolucion_tipo',
            field=models.CharField(blank=True, choices=[('P', 'Resolución de Presidencia'), ('D', 'Resolución de Directorio')], default='P', max_length=1, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='historicalconjuntolicitado',
            name='conjunto_resolucion_acta',
            field=models.CharField(blank=True, default='1', max_length=3, verbose_name='Acta'),
        ),
        migrations.AddField(
            model_name='historicalconjuntolicitado',
            name='conjunto_resolucion_ano',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='historicalconjuntolicitado',
            name='conjunto_resolucion_jurisdiccion',
            field=models.CharField(blank=True, default='10', max_length=3, verbose_name='Jurisdicción'),
        ),
        migrations.AddField(
            model_name='historicalconjuntolicitado',
            name='conjunto_resolucion_numero',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='historicalconjuntolicitado',
            name='conjunto_resolucion_tipo',
            field=models.CharField(blank=True, choices=[('P', 'Resolución de Presidencia'), ('D', 'Resolución de Directorio')], default='P', max_length=1, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='historicalcontrato',
            name='contrato_resolucion_acta',
            field=models.CharField(blank=True, default='1', max_length=3, verbose_name='Acta'),
        ),
        migrations.AddField(
            model_name='historicalcontrato',
            name='contrato_resolucion_ano',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='historicalcontrato',
            name='contrato_resolucion_jurisdiccion',
            field=models.CharField(blank=True, default='10', max_length=3, verbose_name='Jurisdicción'),
        ),
        migrations.AddField(
            model_name='historicalcontrato',
            name='contrato_resolucion_numero',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='historicalcontrato',
            name='contrato_resolucion_tipo',
            field=models.CharField(blank=True, choices=[('P', 'Resolución de Presidencia'), ('D', 'Resolución de Directorio')], default='P', max_length=1, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='historicalobra',
            name='obra_resolucion_acta',
            field=models.CharField(blank=True, default='1', max_length=3, verbose_name='Acta'),
        ),
        migrations.AddField(
            model_name='historicalobra',
            name='obra_resolucion_ano',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='historicalobra',
            name='obra_resolucion_jurisdiccion',
            field=models.CharField(blank=True, default='10', max_length=3, verbose_name='Jurisdicción'),
        ),
        migrations.AddField(
            model_name='historicalobra',
            name='obra_resolucion_numero',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='historicalobra',
            name='obra_resolucion_tipo',
            field=models.CharField(blank=True, choices=[('P', 'Resolución de Presidencia'), ('D', 'Resolución de Directorio')], default='P', max_length=1, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='obra',
            name='obra_resolucion_acta',
            field=models.CharField(blank=True, default='1', max_length=3, verbose_name='Acta'),
        ),
        migrations.AddField(
            model_name='obra',
            name='obra_resolucion_ano',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='obra',
            name='obra_resolucion_jurisdiccion',
            field=models.CharField(blank=True, default='10', max_length=3, verbose_name='Jurisdicción'),
        ),
        migrations.AddField(
            model_name='obra',
            name='obra_resolucion_numero',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='obra',
            name='obra_resolucion_tipo',
            field=models.CharField(blank=True, choices=[('P', 'Resolución de Presidencia'), ('D', 'Resolución de Directorio')], default='P', max_length=1, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='conjuntolicitado',
            name='conjunto_resolucion',
            field=models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='Resolucion (legado)'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='contrato_resolucion',
            field=models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='Resolución Aprobatoria (legado)'),
        ),
        migrations.AlterField(
            model_name='historicalconjuntolicitado',
            name='conjunto_resolucion',
            field=models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='Resolucion (legado)'),
        ),
        migrations.AlterField(
            model_name='historicalcontrato',
            name='contrato_resolucion',
            field=models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='Resolución Aprobatoria (legado)'),
        ),
        migrations.AlterField(
            model_name='historicalobra',
            name='obra_resolucion',
            field=models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='Resolución de Adjudicación (legado)'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='obra_resolucion',
            field=models.CharField(blank=True, editable=False, max_length=15, null=True, verbose_name='Resolución de Adjudicación (legado)'),
        ),
    ]
