# Generated by Django 6.0.8 on 2026-08-21 13:43

import carga.models
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0050_conjuntolicitado_conjunto_resolucion_acta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='certificado_digital',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=carga.models.generate_name_certificados, validators=[core.validators.FileValidator(content_types=('application/pdf',), max_size=14680064, min_size=None)]),
        ),
        migrations.AlterField(
            model_name='contratosdigitales',
            name='contratodigital_archivo',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=carga.models.generate_name_contratos, validators=[core.validators.FileValidator(content_types=('application/pdf',), max_size=14680064, min_size=None)]),
        ),
        migrations.AlterField(
            model_name='historicalcertificado',
            name='certificado_digital',
            field=models.TextField(blank=True, max_length=500, null=True, validators=[core.validators.FileValidator(content_types=('application/pdf',), max_size=14680064, min_size=None)]),
        ),
        migrations.AlterField(
            model_name='historicalcontratosdigitales',
            name='contratodigital_archivo',
            field=models.TextField(blank=True, max_length=500, null=True, validators=[core.validators.FileValidator(content_types=('application/pdf',), max_size=14680064, min_size=None)]),
        ),
        migrations.AlterField(
            model_name='historicalplandetrabajosrubro',
            name='rubro_documento_digital',
            field=models.TextField(blank=True, max_length=500, null=True, validators=[core.validators.FileValidator(content_types=('application/pdf',), max_size=14680064, min_size=None)], verbose_name='Documento Digital'),
        ),
        migrations.AlterField(
            model_name='historicalpoliza',
            name='poliza_digital',
            field=models.TextField(blank=True, max_length=500, null=True, validators=[core.validators.FileValidator(content_types=('application/pdf',), max_size=14680064, min_size=None)], verbose_name='Póliza Digital'),
        ),
        migrations.AlterField(
            model_name='plandetrabajosrubro',
            name='rubro_documento_digital',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=carga.models.generate_name_rubro_documento, validators=[core.validators.FileValidator(content_types=('application/pdf',), max_size=14680064, min_size=None)], verbose_name='Documento Digital'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='poliza_digital',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=carga.models.generate_name_polizas, validators=[core.validators.FileValidator(content_types=('application/pdf',), max_size=14680064, min_size=None)], verbose_name='Póliza Digital'),
        ),
    ]
