# Generated by Django 6.0.8 on 2026-09-05 12:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0051_alter_certificado_certificado_digital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplandetrabajos',
            name='trabajos_meses',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad de columnas (meses) que va a ofrecer la matriz de Etapas Proyectadas de cada Rubro de este plan. Si un Rubro viene de una reprogramación (tiene Rubro Anterior), NO es la duración total de la obra: las Etapas nuevas continúan numerando desde la última Etapa del rubro anterior, así que hay que restar la cantidad de Etapas que ya tenía el plan anterior (no la cantidad de Fojas medidas, que puede ser mayor) del plazo total. Los meses ya medidos por Foja que quedaron sin Etapa en el plan anterior se completan solos al abrir la matriz y también cuentan dentro de este número.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duración (meses)'),
        ),
        migrations.AlterField(
            model_name='plandetrabajos',
            name='trabajos_meses',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad de columnas (meses) que va a ofrecer la matriz de Etapas Proyectadas de cada Rubro de este plan. Si un Rubro viene de una reprogramación (tiene Rubro Anterior), NO es la duración total de la obra: las Etapas nuevas continúan numerando desde la última Etapa del rubro anterior, así que hay que restar la cantidad de Etapas que ya tenía el plan anterior (no la cantidad de Fojas medidas, que puede ser mayor) del plazo total. Los meses ya medidos por Foja que quedaron sin Etapa en el plan anterior se completan solos al abrir la matriz y también cuentan dentro de este número.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duración (meses)'),
        ),
    ]
