# Generated by Django 6.0.8 on 2026-09-19 12:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0052_alter_historicalplandetrabajos_trabajos_meses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpoliza',
            name='poliza_anticipo_pct',
            field=models.DecimalField(blank=True, decimal_places=3, help_text="Sólo aplica al concepto 'Garantía de Anticipo Financiero' (A): % de anticipo que va a tener el certificado, usado para sugerir el monto a cubrir.", max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% de Anticipo'),
        ),
        migrations.AddField(
            model_name='historicalpoliza',
            name='poliza_contrato',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Contrato de la Obra sobre el que se calcula el monto de garantía sugerido.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.contrato', verbose_name='Contrato'),
        ),
        migrations.AddField(
            model_name='historicalpoliza',
            name='poliza_financiamiento',
            field=models.CharField(blank=True, choices=[('N', 'Nación'), ('P', 'Provincia'), ('T', 'Terceros')], max_length=1, null=True, verbose_name='Financiamiento'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='poliza_anticipo_pct',
            field=models.DecimalField(blank=True, decimal_places=3, help_text="Sólo aplica al concepto 'Garantía de Anticipo Financiero' (A): % de anticipo que va a tener el certificado, usado para sugerir el monto a cubrir.", max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% de Anticipo'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='poliza_contrato',
            field=models.ForeignKey(blank=True, help_text='Contrato de la Obra sobre el que se calcula el monto de garantía sugerido.', null=True, on_delete=django.db.models.deletion.PROTECT, to='carga.contrato', verbose_name='Contrato'),
        ),
        migrations.AddField(
            model_name='poliza',
            name='poliza_financiamiento',
            field=models.CharField(blank=True, choices=[('N', 'Nación'), ('P', 'Provincia'), ('T', 'Terceros')], max_length=1, null=True, verbose_name='Financiamiento'),
        ),
    ]
