# Generated by Django 6.0.8 on 2026-09-20 16:33

import django.db.models.deletion
import simple_history.models
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0054_historicalpolizadocumento_polizadocumento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='certificado_texto_resolucion',
            field=models.JSONField(blank=True, editable=False, help_text='Snapshot del texto de la resolución YA RENDERIDO a partir de la plantilla de TextoResolucionCertificado y retocado a mano desde la web. Si está vacío, se vuelve a resolver desde la plantilla. Guarda además de qué plantilla (y de qué versión de esa plantilla) salió, para poder auditarlo después.', null=True, verbose_name='Texto de la Resolución'),
        ),
        migrations.AddField(
            model_name='historicalcertificado',
            name='certificado_texto_resolucion',
            field=models.JSONField(blank=True, editable=False, help_text='Snapshot del texto de la resolución YA RENDERIDO a partir de la plantilla de TextoResolucionCertificado y retocado a mano desde la web. Si está vacío, se vuelve a resolver desde la plantilla. Guarda además de qué plantilla (y de qué versión de esa plantilla) salió, para poder auditarlo después.', null=True, verbose_name='Texto de la Resolución'),
        ),
        migrations.CreateModel(
            name='HistoricalTextoResolucionCertificado',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('textoresolucion_uuid', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False)),
                ('textoresolucion_nombre', models.CharField(help_text="Cómo identificar este texto en el listado. Ej. 'Techo Digno - Nación - Parcial'.", max_length=200, verbose_name='Nombre')),
                ('textoresolucion_financiamiento', models.CharField(choices=[('N', 'Nación'), ('P', 'Provincia'), ('T', 'Terceros')], max_length=1, verbose_name='Financiamiento')),
                ('textoresolucion_tipo', models.CharField(blank=True, choices=[('PARCIAL', 'Certificado Parcial de Obra'), ('ANTICIPO', 'Certificado de Anticipo'), ('HECHO_CONSUMADO', 'Hecho Consumado'), ('ETAPA', 'Certificado de Etapa de Contrato')], default='', help_text='Vacío = sirve para cualquier tipo de certificado de este programa y financiamiento.', max_length=15, verbose_name='Tipo de Certificado')),
                ('textoresolucion_bloques', models.JSONField(blank=True, default=list, help_text='Lista de bloques {clase, label, texto}, donde `texto` es una plantilla Jinja.', verbose_name='Bloques')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('textoresolucion_programa', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.programa', verbose_name='Programa')),
            ],
            options={
                'verbose_name': 'historical Texto de Resolución de Certificado',
                'verbose_name_plural': 'historical Textos de Resolución de Certificados',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TextoResolucionCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textoresolucion_uuid', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False)),
                ('textoresolucion_nombre', models.CharField(help_text="Cómo identificar este texto en el listado. Ej. 'Techo Digno - Nación - Parcial'.", max_length=200, verbose_name='Nombre')),
                ('textoresolucion_financiamiento', models.CharField(choices=[('N', 'Nación'), ('P', 'Provincia'), ('T', 'Terceros')], max_length=1, verbose_name='Financiamiento')),
                ('textoresolucion_tipo', models.CharField(blank=True, choices=[('PARCIAL', 'Certificado Parcial de Obra'), ('ANTICIPO', 'Certificado de Anticipo'), ('HECHO_CONSUMADO', 'Hecho Consumado'), ('ETAPA', 'Certificado de Etapa de Contrato')], default='', help_text='Vacío = sirve para cualquier tipo de certificado de este programa y financiamiento.', max_length=15, verbose_name='Tipo de Certificado')),
                ('textoresolucion_bloques', models.JSONField(blank=True, default=list, help_text='Lista de bloques {clase, label, texto}, donde `texto` es una plantilla Jinja.', verbose_name='Bloques')),
                ('textoresolucion_programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carga.programa', verbose_name='Programa')),
            ],
            options={
                'verbose_name': 'Texto de Resolución de Certificado',
                'verbose_name_plural': 'Textos de Resolución de Certificados',
                'ordering': ['textoresolucion_programa', 'textoresolucion_financiamiento', 'textoresolucion_tipo'],
                'constraints': [models.UniqueConstraint(fields=('textoresolucion_programa', 'textoresolucion_financiamiento', 'textoresolucion_tipo'), name='textoresolucion-alcance-unico')],
            },
        ),
    ]
