# Generated by Django 6.0.8 on 2026-10-01 16:36

from django.db import migrations, models


def mover_fecha_inicio_a_obra(apps, schema_editor):
    """La fecha de inicio vivía en el Plan de Trabajos. La de los planes originales (sin
    rubros reprogramados) pasa a la obra; la de los reprogramados queda como reinicio."""
    Obra = apps.get_model("carga", "Obra")
    PlanDeTrabajos = apps.get_model("carga", "PlanDeTrabajos")
    planes = (
        PlanDeTrabajos.objects
        .filter(trabajos_fecha_inicio__isnull=False)
        .exclude(rubros__rubro_anterior__isnull=False)
        .order_by("trabajos_fecha_inicio")
    )
    vistas = set()
    for plan in planes:
        if plan.trabajos_obra_id not in vistas:
            vistas.add(plan.trabajos_obra_id)
            Obra.objects.filter(pk=plan.trabajos_obra_id).update(obra_fecha_inicio=plan.trabajos_fecha_inicio)
    PlanDeTrabajos.objects.filter(pk__in=[plan.pk for plan in planes]).update(trabajos_fecha_inicio=None)


def devolver_fecha_inicio_al_plan(apps, schema_editor):
    Obra = apps.get_model("carga", "Obra")
    PlanDeTrabajos = apps.get_model("carga", "PlanDeTrabajos")
    for obra in Obra.objects.filter(obra_fecha_inicio__isnull=False):
        (
            PlanDeTrabajos.objects
            .filter(trabajos_obra=obra, trabajos_fecha_inicio__isnull=True)
            .exclude(rubros__rubro_anterior__isnull=False)
            .update(trabajos_fecha_inicio=obra.obra_fecha_inicio)
        )


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0056_historicalfojademedicion_foja_inspector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalobra',
            name='obra_fecha_inicio',
            field=models.DateField(blank=True, help_text='Fecha de firma del Acta de Inicio. Es única por obra: los reinicios por reprogramación se registran en cada Plan de Trabajos.', null=True, verbose_name='Fecha de Inicio de Obra'),
        ),
        migrations.AddField(
            model_name='obra',
            name='obra_fecha_inicio',
            field=models.DateField(blank=True, help_text='Fecha de firma del Acta de Inicio. Es única por obra: los reinicios por reprogramación se registran en cada Plan de Trabajos.', null=True, verbose_name='Fecha de Inicio de Obra'),
        ),
        migrations.AlterField(
            model_name='historicalplandetrabajos',
            name='trabajos_fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Reinicio de Obra'),
        ),
        migrations.AlterField(
            model_name='plandetrabajos',
            name='trabajos_fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Reinicio de Obra'),
        ),
        migrations.RunPython(mover_fecha_inicio_a_obra, devolver_fecha_inicio_al_plan),
    ]
