# Generated by Django 6.0.8 on 2026-10-06 12:35

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def anticipos_con_fondo_de_reparo(apps, schema_editor):
    """Los Anticipos se cargaban con Fondo de Reparo forzado a 0%, pero en la práctica se
    pagan con la retención (Resolución 427/2026). Se pasan al 5% y se anula el texto de
    resolución guardado, igual que haría la señal invalidar_texto_resolucion_por_cambio_de_datos."""
    Certificado = apps.get_model("carga", "Certificado")
    Certificado.objects.filter(certificado_tipo="ANTICIPO", certificado_fondoreparo_pct=0).update(
        certificado_fondoreparo_pct=Decimal("5"), certificado_texto_resolucion=None
    )


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0058_backfill_certificado_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='certificado_fondoreparo_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('5'), help_text='Retención sobre el certificado neto del descuento de anticipo. El Anticipo lleva su propia retención al pagarse (ver Resolución 427/2026), así que la parte ya anticipada no vuelve a retenerse al devolverse.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Fondo de Reparo %'),
        ),
        migrations.AlterField(
            model_name='historicalcertificado',
            name='certificado_fondoreparo_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('5'), help_text='Retención sobre el certificado neto del descuento de anticipo. El Anticipo lleva su propia retención al pagarse (ver Resolución 427/2026), así que la parte ya anticipada no vuelve a retenerse al devolverse.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Fondo de Reparo %'),
        ),
        migrations.RunPython(anticipos_con_fondo_de_reparo, migrations.RunPython.noop),
    ]
