# Generated by Django 5.0.3 on 2024-09-03 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargotipo', models.CharField(max_length=120, verbose_name='Tipo de Cargo')),
            ],
            options={
                'verbose_name': 'Tipo de Cargo',
                'verbose_name_plural': 'Tipos de Cargos',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento_nombre', models.CharField(max_length=200, verbose_name='Departamento')),
                ('departamento_cuof', models.CharField(max_length=10, verbose_name='CUOF')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_nombre', models.CharField(max_length=200, verbose_name='Direccion')),
                ('direccion_cuof', models.CharField(max_length=10, verbose_name='CUOF')),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
            },
        ),
        migrations.CreateModel(
            name='Gerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gerencia_nombre', models.CharField(max_length=200, verbose_name='Gerencia')),
                ('gerencia_cuof', models.CharField(max_length=10, verbose_name='CUOF')),
            ],
            options={
                'verbose_name': 'Gerencia',
                'verbose_name_plural': 'Gerencias',
            },
        ),
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalizador.cargotipo')),
                ('cargo_departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personalizador.departamento')),
                ('cargo_direccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personalizador.direccion')),
                ('cargo_gerencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personalizador.gerencia')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
    ]
