# Generated by Django 5.2.10 on 2026-06-06 13:04

import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizador', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargos',
            name='cargos_uuid',
            field=models.UUIDField(default=uuid_utils.compat.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='cargotipo',
            name='cargotipo_uuid',
            field=models.UUIDField(default=uuid_utils.compat.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='departamento',
            name='departamento_uuid',
            field=models.UUIDField(default=uuid_utils.compat.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='direccion',
            name='direccion_uuid',
            field=models.UUIDField(default=uuid_utils.compat.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='gerencia',
            name='gerencia_uuid',
            field=models.UUIDField(default=uuid_utils.compat.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='historicalcargos',
            name='cargos_uuid',
            field=models.UUIDField(default=uuid_utils.compat.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='historicalcargotipo',
            name='cargotipo_uuid',
            field=models.UUIDField(default=uuid_utils.compat.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='historicaldepartamento',
            name='departamento_uuid',
            field=models.UUIDField(default=uuid_utils.compat.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='historicaldireccion',
            name='direccion_uuid',
            field=models.UUIDField(default=uuid_utils.compat.uuid7, editable=False),
        ),
        migrations.AddField(
            model_name='historicalgerencia',
            name='gerencia_uuid',
            field=models.UUIDField(default=uuid_utils.compat.uuid7, editable=False),
        ),
    ]
