# Generated by Django 6.0.6 on 2026-06-19 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizador', '0007_actividadespecifica_apartadocargo_categoria_ceic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='departamento_autoridad_a_cargo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Autoridad a Cargo'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='departamento_gerencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personalizador.gerencia'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='departamento_responsabilidadprimaria',
            field=models.TextField(blank=True, null=True, verbose_name='Responsabilidad Primaria'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='departamento_ungi',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='UNGI'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='direccion_autoridad_a_cargo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Autoridad a Cargo'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='direccion_responsabilidadprimaria',
            field=models.TextField(blank=True, null=True, verbose_name='Responsabilidad Primaria'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='direccion_ungi',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='UNGI'),
        ),
        migrations.AddField(
            model_name='directorio',
            name='directorio_autoridad_a_cargo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Autoridad a Cargo'),
        ),
        migrations.AddField(
            model_name='directorio',
            name='directorio_ungi',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='UNGI'),
        ),
        migrations.AddField(
            model_name='gerencia',
            name='gerencia_autoridad_a_cargo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Autoridad a Cargo'),
        ),
        migrations.AddField(
            model_name='gerencia',
            name='gerencia_responsabilidadprimaria',
            field=models.TextField(blank=True, null=True, verbose_name='Responsabilidad Primaria'),
        ),
        migrations.AddField(
            model_name='gerencia',
            name='gerencia_ungi',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='UNGI'),
        ),
        migrations.AddField(
            model_name='historicaldepartamento',
            name='departamento_autoridad_a_cargo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Autoridad a Cargo'),
        ),
        migrations.AddField(
            model_name='historicaldepartamento',
            name='departamento_gerencia',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personalizador.gerencia'),
        ),
        migrations.AddField(
            model_name='historicaldepartamento',
            name='departamento_responsabilidadprimaria',
            field=models.TextField(blank=True, null=True, verbose_name='Responsabilidad Primaria'),
        ),
        migrations.AddField(
            model_name='historicaldepartamento',
            name='departamento_ungi',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='UNGI'),
        ),
        migrations.AddField(
            model_name='historicaldireccion',
            name='direccion_autoridad_a_cargo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Autoridad a Cargo'),
        ),
        migrations.AddField(
            model_name='historicaldireccion',
            name='direccion_responsabilidadprimaria',
            field=models.TextField(blank=True, null=True, verbose_name='Responsabilidad Primaria'),
        ),
        migrations.AddField(
            model_name='historicaldireccion',
            name='direccion_ungi',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='UNGI'),
        ),
        migrations.AddField(
            model_name='historicaldirectorio',
            name='directorio_autoridad_a_cargo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Autoridad a Cargo'),
        ),
        migrations.AddField(
            model_name='historicaldirectorio',
            name='directorio_ungi',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='UNGI'),
        ),
        migrations.AddField(
            model_name='historicalgerencia',
            name='gerencia_autoridad_a_cargo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Autoridad a Cargo'),
        ),
        migrations.AddField(
            model_name='historicalgerencia',
            name='gerencia_responsabilidadprimaria',
            field=models.TextField(blank=True, null=True, verbose_name='Responsabilidad Primaria'),
        ),
        migrations.AddField(
            model_name='historicalgerencia',
            name='gerencia_ungi',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='UNGI'),
        ),
    ]
