# Generated by Django 6.0.6 on 2026-06-19 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizador', '0008_departamento_departamento_autoridad_a_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='abreviatura',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Abreviatura'),
        ),
        migrations.AddField(
            model_name='historicalagente',
            name='abreviatura',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Abreviatura'),
        ),
        migrations.AlterField(
            model_name='agente',
            name='dni',
            field=models.DecimalField(decimal_places=0, max_digits=9, unique=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='DNI:'),
        ),
        migrations.AlterField(
            model_name='agente',
            name='n_legajo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero de legajo'),
        ),
        migrations.AlterField(
            model_name='historicalagente',
            name='dni',
            field=models.DecimalField(db_index=True, decimal_places=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0)], verbose_name='DNI:'),
        ),
        migrations.AlterField(
            model_name='historicalagente',
            name='n_legajo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero de legajo'),
        ),
    ]
