# Generated by Django 6.0.6 on 2026-06-19 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizador', '0009_agente_merge_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente',
            name='apartado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personalizador.apartadocargo'),
        ),
    ]
