# Generated by Django 6.0.6 on 2026-06-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizador', '0010_agente_apartado_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='agente_es_inpector_obra',
            field=models.BooleanField(default=False, verbose_name='Inspector de Obra'),
        ),
        migrations.AddField(
            model_name='historicalagente',
            name='agente_es_inpector_obra',
            field=models.BooleanField(default=False, verbose_name='Inspector de Obra'),
        ),
    ]
