# Generated by Django 6.0.6 on 2026-06-22 11:14

import django.db.models.deletion
import personalizador.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizador', '0012_agente_merge_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='departamento_autoridad_a_cargo_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personalizador.agente'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='direccion_autoridad_a_cargo_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personalizador.agente'),
        ),
        migrations.AddField(
            model_name='directorio',
            name='directorio_autoridad_a_cargo_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personalizador.agente'),
        ),
        migrations.AddField(
            model_name='gerencia',
            name='gerencia_autoridad_a_cargo_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personalizador.agente'),
        ),
        migrations.AddField(
            model_name='historicaldepartamento',
            name='departamento_autoridad_a_cargo_fk',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personalizador.agente'),
        ),
        migrations.AddField(
            model_name='historicaldireccion',
            name='direccion_autoridad_a_cargo_fk',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personalizador.agente'),
        ),
        migrations.AddField(
            model_name='historicaldirectorio',
            name='directorio_autoridad_a_cargo_fk',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personalizador.agente'),
        ),
        migrations.AddField(
            model_name='historicalgerencia',
            name='gerencia_autoridad_a_cargo_fk',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personalizador.agente'),
        ),
        migrations.AddField(
            model_name='agente',
            name='agente_apellidoynombre_coma',
            field=models.GeneratedField(db_persist=True, expression=personalizador.models.ConcatOp(models.F('agente_apellidos'), models.Value(', '), models.F('agente_nombres')), output_field=models.CharField(editable=False, max_length=256, verbose_name='Apellido y Nombres')),
        ),
        migrations.AddField(
            model_name='historicalagente',
            name='agente_apellidoynombre_coma',
            field=models.GeneratedField(db_persist=True, expression=personalizador.models.ConcatOp(models.F('agente_apellidos'), models.Value(', '), models.F('agente_nombres')), output_field=models.CharField(editable=False, max_length=256, verbose_name='Apellido y Nombres')),
        ),
    ]
