# Generated by Django 6.0.6 on 2026-06-22 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizador', '0013_departamento_departamento_autoridad_a_cargo_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente',
            name='agente_usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
