# Generated by Django 6.0.6 on 2026-07-01 13:27

import django.core.validators
import django.db.models.deletion
import core.validators
import simple_history.models
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizador', '0014_alter_agente_agente_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRepresentanteTecnico',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('representantetecnico_nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('representantetecnico_apellido', models.CharField(max_length=200, verbose_name='Apellido')),
                ('representantetecnico_dni', models.DecimalField(db_index=True, decimal_places=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0)], verbose_name='DNI:')),
                ('representantetecnico_cuil', models.CharField(max_length=13, validators=[core.validators.CuitValidator()], verbose_name='CUIT')),
                ('representantetecnico_email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('representantetecnico_telefono', models.CharField(blank=True, max_length=200, null=True, verbose_name='Telefono')),
                ('representantetecnico_matricula', models.CharField(max_length=10, verbose_name='Matricula')),
                ('representantetecnico_uuid', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('representantetecnico_profesion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personalizador.tituloprofesional')),
            ],
            options={
                'verbose_name': 'historical Representante Técnico',
                'verbose_name_plural': 'historical Representantes Técnicos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RepresentanteTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representantetecnico_nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('representantetecnico_apellido', models.CharField(max_length=200, verbose_name='Apellido')),
                ('representantetecnico_dni', models.DecimalField(decimal_places=0, max_digits=9, unique=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='DNI:')),
                ('representantetecnico_cuil', models.CharField(max_length=13, validators=[core.validators.CuitValidator()], verbose_name='CUIT')),
                ('representantetecnico_email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('representantetecnico_telefono', models.CharField(blank=True, max_length=200, null=True, verbose_name='Telefono')),
                ('representantetecnico_matricula', models.CharField(max_length=10, verbose_name='Matricula')),
                ('representantetecnico_uuid', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False)),
                ('representantetecnico_profesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalizador.tituloprofesional')),
            ],
            options={
                'verbose_name': 'Representante Técnico',
                'verbose_name_plural': 'Representantes Técnicos',
            },
        ),
        migrations.AlterModelOptions(
            name='representantetecnico',
            options={'ordering': ('representantetecnico_apellido', 'representantetecnico_nombre'), 'verbose_name': 'Representante Técnico', 'verbose_name_plural': 'Representantes Técnicos'},
        ),
        migrations.AddField(
            model_name='historicaltituloprofesional',
            name='tituloprofesional_abreviatura',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tituloprofesional',
            name='tituloprofesional_abreviatura',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
