# Generated by Django 6.0.6 on 2026-07-18 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalizador', '0015_historicalrepresentantetecnico_representantetecnico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaloficina',
            name='cargo_tipo',
        ),
        migrations.RemoveField(
            model_name='oficina',
            name='cargo_tipo',
        ),
    ]
