# Generated by Django 6.0.6 on 2026-07-18 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizador', '0017_completar_jerarquia_oficinas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente',
            name='cargo_interno',
            field=models.ForeignKey(blank=True, help_text='Oficina a la que el agente esta designado transitoriamente, distinta de su oficina habitual.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agente_designacion_temporal', to='personalizador.oficina', verbose_name='Designación Temporal'),
        ),
        migrations.AlterField(
            model_name='historicalagente',
            name='cargo_interno',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Oficina a la que el agente esta designado transitoriamente, distinta de su oficina habitual.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personalizador.oficina', verbose_name='Designación Temporal'),
        ),
    ]
