# Generated by Django 6.0.6 on 2026-08-05 12:45

import core.validators
import django.db.models.deletion
import django.utils.timezone
import personalizador.models
import simple_history.models
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizador', '0019_cargar_datos_iniciales'),
        ('secretariador', '0015_alter_historicalinstrumentoslegalesdecretos_instrumentolegaldecretos_numero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTipoLicenciaPermiso',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipolicenciapermiso_categoria', models.CharField(choices=[('LOR', 'Licencia Ordinaria'), ('LEX', 'Licencia Extraordinaria'), ('PER', 'Permiso')], max_length=3, verbose_name='Categoría')),
                ('tipolicenciapermiso_nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('tipolicenciapermiso_articulo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Artículo (Ley 645-A)')),
                ('tipolicenciapermiso_unidad', models.CharField(choices=[('DC', 'Días corridos'), ('DH', 'Días hábiles'), ('HS', 'Horas')], default='DC', max_length=2, verbose_name='Unidad')),
                ('tipolicenciapermiso_tope_cantidad', models.PositiveIntegerField(blank=True, help_text='Vacío cuando el tope no es un número fijo (ej. depende de la antigüedad o de junta médica).', null=True, verbose_name='Tope')),
                ('tipolicenciapermiso_tope_periodo', models.CharField(choices=[('ANI', 'Por año calendario'), ('VEZ', 'Por vez/evento'), ('TOT', 'Total del beneficio'), ('VAR', 'Variable')], default='ANI', max_length=3, verbose_name='Período del tope')),
                ('tipolicenciapermiso_remunerada', models.CharField(choices=[('SI', 'Con goce de haberes'), ('NO', 'Sin goce de haberes'), ('PA', 'Parcial')], default='SI', max_length=2, verbose_name='Remunerada')),
                ('tipolicenciapermiso_antiguedad_meses', models.PositiveIntegerField(default=0, verbose_name='Antigüedad mínima (meses)')),
                ('tipolicenciapermiso_requiere_certificado', models.BooleanField(default=False, verbose_name='Requiere certificado')),
                ('tipolicenciapermiso_compensacion_horaria', models.BooleanField(default=False, help_text='Permisos que la ley obliga a devolver con horas de trabajo (ej. razones particulares, lactancia).', verbose_name='Requiere compensación de horario')),
                ('tipolicenciapermiso_observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('tipolicenciapermiso_activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('tipolicenciapermiso_uuid', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Tipo de Licencia/Permiso',
                'verbose_name_plural': 'historical Tipos de Licencias/Permisos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LicenciaPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licenciapermiso_fecha_otorgamiento', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Otorgamiento')),
                ('licenciapermiso_fecha_desde', models.DateField(verbose_name='Fecha Desde')),
                ('licenciapermiso_fecha_hasta', models.DateField(blank=True, null=True, verbose_name='Fecha Hasta')),
                ('licenciapermiso_cantidad', models.PositiveIntegerField(help_text='En la unidad indicada por el tipo (días u horas).', verbose_name='Cantidad')),
                ('licenciapermiso_motivo', models.TextField(blank=True, null=True, verbose_name='Motivo')),
                ('licenciapermiso_anulada', models.BooleanField(default=False, help_text='Si el registro se encuentra anulado, no se computa en los balances ni reportes.', verbose_name='Anulada')),
                ('licenciapermiso_adjunto', models.FileField(blank=True, max_length=500, null=True, upload_to=personalizador.models.generate_name_licenciapermiso, validators=[core.validators.FileValidator(content_types=('application/pdf',), max_size=14680064, min_size=None)], verbose_name='Adjunto (certificado/comunicación)')),
                ('licenciapermiso_uuid', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False)),
                ('licenciapermiso_agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalizador.agente', verbose_name='Agente')),
                ('licenciapermiso_instrumento_decreto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secretariador.instrumentoslegalesdecretos', verbose_name='Decreto')),
                ('licenciapermiso_instrumento_memorandum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secretariador.instrumentoslegalesmemorandum', verbose_name='Memorandum')),
                ('licenciapermiso_instrumento_resolucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secretariador.instrumentoslegalesresoluciones', verbose_name='Resolución')),
            ],
            options={
                'verbose_name': 'Licencia/Permiso',
                'verbose_name_plural': 'Licencias/Permisos',
                'ordering': ('-licenciapermiso_fecha_desde',),
            },
        ),
        migrations.CreateModel(
            name='HistoricalDevolucionHorasPermiso',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('devolucionhoras_fecha', models.DateField(verbose_name='Fecha')),
                ('devolucionhoras_cantidad', models.PositiveIntegerField(verbose_name='Horas Devueltas')),
                ('devolucionhoras_observaciones', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observaciones')),
                ('devolucionhoras_uuid', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('devolucionhoras_licencia', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personalizador.licenciapermiso', verbose_name='Licencia/Permiso')),
            ],
            options={
                'verbose_name': 'historical Devolución de Horas',
                'verbose_name_plural': 'historical Devoluciones de Horas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DevolucionHorasPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devolucionhoras_fecha', models.DateField(verbose_name='Fecha')),
                ('devolucionhoras_cantidad', models.PositiveIntegerField(verbose_name='Horas Devueltas')),
                ('devolucionhoras_observaciones', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observaciones')),
                ('devolucionhoras_uuid', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False)),
                ('devolucionhoras_licencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devolucionhoras_set', to='personalizador.licenciapermiso', verbose_name='Licencia/Permiso')),
            ],
            options={
                'verbose_name': 'Devolución de Horas',
                'verbose_name_plural': 'Devoluciones de Horas',
                'ordering': ('devolucionhoras_fecha',),
            },
        ),
        migrations.CreateModel(
            name='TipoLicenciaPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipolicenciapermiso_categoria', models.CharField(choices=[('LOR', 'Licencia Ordinaria'), ('LEX', 'Licencia Extraordinaria'), ('PER', 'Permiso')], max_length=3, verbose_name='Categoría')),
                ('tipolicenciapermiso_nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('tipolicenciapermiso_articulo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Artículo (Ley 645-A)')),
                ('tipolicenciapermiso_unidad', models.CharField(choices=[('DC', 'Días corridos'), ('DH', 'Días hábiles'), ('HS', 'Horas')], default='DC', max_length=2, verbose_name='Unidad')),
                ('tipolicenciapermiso_tope_cantidad', models.PositiveIntegerField(blank=True, help_text='Vacío cuando el tope no es un número fijo (ej. depende de la antigüedad o de junta médica).', null=True, verbose_name='Tope')),
                ('tipolicenciapermiso_tope_periodo', models.CharField(choices=[('ANI', 'Por año calendario'), ('VEZ', 'Por vez/evento'), ('TOT', 'Total del beneficio'), ('VAR', 'Variable')], default='ANI', max_length=3, verbose_name='Período del tope')),
                ('tipolicenciapermiso_remunerada', models.CharField(choices=[('SI', 'Con goce de haberes'), ('NO', 'Sin goce de haberes'), ('PA', 'Parcial')], default='SI', max_length=2, verbose_name='Remunerada')),
                ('tipolicenciapermiso_antiguedad_meses', models.PositiveIntegerField(default=0, verbose_name='Antigüedad mínima (meses)')),
                ('tipolicenciapermiso_requiere_certificado', models.BooleanField(default=False, verbose_name='Requiere certificado')),
                ('tipolicenciapermiso_compensacion_horaria', models.BooleanField(default=False, help_text='Permisos que la ley obliga a devolver con horas de trabajo (ej. razones particulares, lactancia).', verbose_name='Requiere compensación de horario')),
                ('tipolicenciapermiso_observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('tipolicenciapermiso_activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('tipolicenciapermiso_uuid', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False)),
            ],
            options={
                'verbose_name': 'Tipo de Licencia/Permiso',
                'verbose_name_plural': 'Tipos de Licencias/Permisos',
                'ordering': ('tipolicenciapermiso_categoria', 'tipolicenciapermiso_nombre'),
                'constraints': [models.UniqueConstraint(fields=('tipolicenciapermiso_categoria', 'tipolicenciapermiso_nombre'), name='unique_tipolicenciapermiso_1')],
            },
        ),
        migrations.AddField(
            model_name='licenciapermiso',
            name='licenciapermiso_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalizador.tipolicenciapermiso', verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='HistoricalLicenciaPermiso',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('licenciapermiso_fecha_otorgamiento', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Otorgamiento')),
                ('licenciapermiso_fecha_desde', models.DateField(verbose_name='Fecha Desde')),
                ('licenciapermiso_fecha_hasta', models.DateField(blank=True, null=True, verbose_name='Fecha Hasta')),
                ('licenciapermiso_cantidad', models.PositiveIntegerField(help_text='En la unidad indicada por el tipo (días u horas).', verbose_name='Cantidad')),
                ('licenciapermiso_motivo', models.TextField(blank=True, null=True, verbose_name='Motivo')),
                ('licenciapermiso_anulada', models.BooleanField(default=False, help_text='Si el registro se encuentra anulado, no se computa en los balances ni reportes.', verbose_name='Anulada')),
                ('licenciapermiso_adjunto', models.TextField(blank=True, max_length=500, null=True, validators=[core.validators.FileValidator(content_types=('application/pdf',), max_size=14680064, min_size=None)], verbose_name='Adjunto (certificado/comunicación)')),
                ('licenciapermiso_uuid', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('licenciapermiso_agente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personalizador.agente', verbose_name='Agente')),
                ('licenciapermiso_instrumento_decreto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='secretariador.instrumentoslegalesdecretos', verbose_name='Decreto')),
                ('licenciapermiso_instrumento_memorandum', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='secretariador.instrumentoslegalesmemorandum', verbose_name='Memorandum')),
                ('licenciapermiso_instrumento_resolucion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='secretariador.instrumentoslegalesresoluciones', verbose_name='Resolución')),
                ('licenciapermiso_tipo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personalizador.tipolicenciapermiso', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'historical Licencia/Permiso',
                'verbose_name_plural': 'historical Licencias/Permisos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
