# Generated by Django 6.0.6 on 2026-08-06 21:28

import core.validators
import django.core.validators
import django.db.models.deletion
import personalizador.models
import simple_history.models
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizador', '0020_historicaltipolicenciapermiso_licenciapermiso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorteLicencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cortelicencia_fecha_reintegro', models.DateField(verbose_name='Fecha de Reintegro')),
                ('cortelicencia_dias_gozados', models.PositiveIntegerField(help_text='Días efectivamente usados antes del reintegro.', verbose_name='Días Gozados')),
                ('cortelicencia_dias_pendientes', models.PositiveIntegerField(help_text='Saldo a utilizar más adelante (total o fraccionado).', verbose_name='Días Pendientes')),
                ('cortelicencia_fecha_vencimiento', models.DateField(help_text='Fecha límite para usar el saldo pendiente.', verbose_name='Vence el')),
                ('cortelicencia_motivo', models.TextField(blank=True, help_text='Ej. "Necesidades del organismo".', null=True, verbose_name='Motivo')),
                ('cortelicencia_nota_jurisdiccion', models.CharField(default='E10', max_length=3, verbose_name='Jurisdicción')),
                ('cortelicencia_nota_numero', models.DecimalField(decimal_places=0, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='N° Actuación')),
                ('cortelicencia_nota_ano', models.DecimalField(decimal_places=0, default=2026, max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Año Actuación')),
                ('cortelicencia_nota_actuacion', models.GeneratedField(db_persist=True, expression=personalizador.models.ConcatOp('cortelicencia_nota_jurisdiccion', models.Value('-'), 'cortelicencia_nota_numero', models.Value('-'), 'cortelicencia_nota_ano'), output_field=models.CharField(editable=False, max_length=20, verbose_name='N° Actuación'))),
                ('cortelicencia_adjunto', models.FileField(blank=True, max_length=500, null=True, upload_to=personalizador.models.generate_name_cortelicencia, validators=[core.validators.FileValidator(content_types=('application/pdf',), max_size=14680064, min_size=None)], verbose_name='Adjunto (nota)')),
                ('cortelicencia_uuid', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False)),
                ('cortelicencia_licencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='corte', to='personalizador.licenciapermiso', verbose_name='Licencia interrumpida')),
            ],
            options={
                'verbose_name': 'Corte de Licencia',
                'verbose_name_plural': 'Cortes de Licencia',
            },
        ),
        migrations.AddField(
            model_name='historicallicenciapermiso',
            name='licenciapermiso_saldo_de_corte',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Completar si esta licencia consume el saldo pendiente de un corte anterior, en vez de ser un otorgamiento nuevo.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personalizador.cortelicencia', verbose_name='Usa saldo de corte'),
        ),
        migrations.AddField(
            model_name='licenciapermiso',
            name='licenciapermiso_saldo_de_corte',
            field=models.ForeignKey(blank=True, help_text='Completar si esta licencia consume el saldo pendiente de un corte anterior, en vez de ser un otorgamiento nuevo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usos_saldo', to='personalizador.cortelicencia', verbose_name='Usa saldo de corte'),
        ),
        migrations.CreateModel(
            name='HistoricalCorteLicencia',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cortelicencia_fecha_reintegro', models.DateField(verbose_name='Fecha de Reintegro')),
                ('cortelicencia_dias_gozados', models.PositiveIntegerField(help_text='Días efectivamente usados antes del reintegro.', verbose_name='Días Gozados')),
                ('cortelicencia_dias_pendientes', models.PositiveIntegerField(help_text='Saldo a utilizar más adelante (total o fraccionado).', verbose_name='Días Pendientes')),
                ('cortelicencia_fecha_vencimiento', models.DateField(help_text='Fecha límite para usar el saldo pendiente.', verbose_name='Vence el')),
                ('cortelicencia_motivo', models.TextField(blank=True, help_text='Ej. "Necesidades del organismo".', null=True, verbose_name='Motivo')),
                ('cortelicencia_nota_jurisdiccion', models.CharField(default='E10', max_length=3, verbose_name='Jurisdicción')),
                ('cortelicencia_nota_numero', models.DecimalField(decimal_places=0, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='N° Actuación')),
                ('cortelicencia_nota_ano', models.DecimalField(decimal_places=0, default=2026, max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Año Actuación')),
                ('cortelicencia_nota_actuacion', models.GeneratedField(db_persist=True, expression=personalizador.models.ConcatOp('cortelicencia_nota_jurisdiccion', models.Value('-'), 'cortelicencia_nota_numero', models.Value('-'), 'cortelicencia_nota_ano'), output_field=models.CharField(editable=False, max_length=20, verbose_name='N° Actuación'))),
                ('cortelicencia_adjunto', models.TextField(blank=True, max_length=500, null=True, validators=[core.validators.FileValidator(content_types=('application/pdf',), max_size=14680064, min_size=None)], verbose_name='Adjunto (nota)')),
                ('cortelicencia_uuid', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cortelicencia_licencia', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personalizador.licenciapermiso', verbose_name='Licencia interrumpida')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Corte de Licencia',
                'verbose_name_plural': 'historical Cortes de Licencia',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
