# Generated by Django 6.0.6 on 2026-08-07 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0050_conjuntolicitado_conjunto_resolucion_acta_and_more'),
        ('personalizador', '0021_cortelicencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='aportes_anses',
            field=models.CharField(blank=True, help_text='Instrumento que establece los aportes', max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='agente',
            name='aportes_anses_anios',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Años reconocidos (ANSES)'),
        ),
        migrations.AddField(
            model_name='agente',
            name='aportes_anses_dias',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Días reconocidos (ANSES)'),
        ),
        migrations.AddField(
            model_name='agente',
            name='aportes_anses_meses',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Meses reconocidos (ANSES)'),
        ),
        migrations.AddField(
            model_name='agente',
            name='aportes_ley_resolucion_anios',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Años reconocidos (Resolución)'),
        ),
        migrations.AddField(
            model_name='agente',
            name='aportes_ley_resolucion_dias',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Días reconocidos (Resolución)'),
        ),
        migrations.AddField(
            model_name='agente',
            name='aportes_ley_resolucion_meses',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Meses reconocidos (Resolución)'),
        ),
        migrations.AddField(
            model_name='historicalagente',
            name='aportes_anses',
            field=models.CharField(blank=True, help_text='Instrumento que establece los aportes', max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='historicalagente',
            name='aportes_anses_anios',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Años reconocidos (ANSES)'),
        ),
        migrations.AddField(
            model_name='historicalagente',
            name='aportes_anses_dias',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Días reconocidos (ANSES)'),
        ),
        migrations.AddField(
            model_name='historicalagente',
            name='aportes_anses_meses',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Meses reconocidos (ANSES)'),
        ),
        migrations.AddField(
            model_name='historicalagente',
            name='aportes_ley_resolucion_anios',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Años reconocidos (Resolución)'),
        ),
        migrations.AddField(
            model_name='historicalagente',
            name='aportes_ley_resolucion_dias',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Días reconocidos (Resolución)'),
        ),
        migrations.AddField(
            model_name='historicalagente',
            name='aportes_ley_resolucion_meses',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Meses reconocidos (Resolución)'),
        ),
        migrations.AddField(
            model_name='agente',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='historicalagente',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.RenameField(
            model_name='agente',
            old_name='n_resolucion_bonificacion',
            new_name='instrumento_bonificacion',
        ),
        migrations.RenameField(
            model_name='historicalagente',
            old_name='n_resolucion_bonificacion',
            new_name='instrumento_bonificacion',
        ),
        migrations.AddField(
            model_name='agente',
            name='aportes_ley_resolucion_tipo',
            field=models.CharField(blank=True, choices=[('DEC', 'Decreto'), ('RES', 'Resolución'), ('DIS', 'Disposición')], max_length=3, null=True, verbose_name='Tipo de instrumento'),
        ),
        migrations.AddField(
            model_name='historicalagente',
            name='aportes_ley_resolucion_tipo',
            field=models.CharField(blank=True, choices=[('DEC', 'Decreto'), ('RES', 'Resolución'), ('DIS', 'Disposición')], max_length=3, null=True, verbose_name='Tipo de instrumento'),
        ),
        migrations.AddField(
            model_name='agente',
            name='instrumento_bonificacion_tipo',
            field=models.CharField(blank=True, choices=[('RES', 'Resolución'), ('DEC', 'Decreto')], max_length=3, null=True, verbose_name='Tipo de instrumento'),
        ),
        migrations.AddField(
            model_name='historicalagente',
            name='instrumento_bonificacion_tipo',
            field=models.CharField(blank=True, choices=[('RES', 'Resolución'), ('DEC', 'Decreto')], max_length=3, null=True, verbose_name='Tipo de instrumento'),
        ),
        migrations.AddField(
            model_name='agente',
            name='instrumento_contrato_de_servicio_tipo',
            field=models.CharField(blank=True, choices=[('RES', 'Resolución'), ('DEC', 'Decreto')], max_length=3, null=True, verbose_name='Tipo de instrumento'),
        ),
        migrations.AddField(
            model_name='historicalagente',
            name='instrumento_contrato_de_servicio_tipo',
            field=models.CharField(blank=True, choices=[('RES', 'Resolución'), ('DEC', 'Decreto')], max_length=3, null=True, verbose_name='Tipo de instrumento'),
        ),
        migrations.AlterField(
            model_name='agente',
            name='abreviatura',
            field=models.CharField(blank=True, help_text='Sr./Sra.', max_length=10, null=True, verbose_name='Abreviatura'),
        ),
        migrations.AlterField(
            model_name='agente',
            name='aportes_ley_resolucion',
            field=models.CharField(blank=True, help_text='Instrumento que establece los aportes - Solo Numero/Año', max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='agente',
            name='instrumento_bonificacion',
            field=models.CharField(blank=True, help_text='Instrumento que aprueba la bonificacion por titulo - Solo Numero/Año', max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='agente',
            name='instrumento_contrato_de_servicio',
            field=models.CharField(blank=True, help_text='Instrumento que aprueba el contrato de servicio - Solo Numero/Año', max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='agente',
            name='n_decreto',
            field=models.CharField(blank=True, help_text='N° de instrumento de pase a planta permanente - Solo Numero/Año', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='agente',
            name='n_decreto_transferencia_definitiva',
            field=models.CharField(blank=True, help_text='Decreto de transferencia definitiva - Solo Numero/Año', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalagente',
            name='abreviatura',
            field=models.CharField(blank=True, help_text='Sr./Sra.', max_length=10, null=True, verbose_name='Abreviatura'),
        ),
        migrations.AlterField(
            model_name='historicalagente',
            name='aportes_ley_resolucion',
            field=models.CharField(blank=True, help_text='Instrumento que establece los aportes - Solo Numero/Año', max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='historicalagente',
            name='instrumento_bonificacion',
            field=models.CharField(blank=True, help_text='Instrumento que aprueba la bonificacion por titulo - Solo Numero/Año', max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='historicalagente',
            name='instrumento_contrato_de_servicio',
            field=models.CharField(blank=True, help_text='Instrumento que aprueba el contrato de servicio - Solo Numero/Año', max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='historicalagente',
            name='n_decreto',
            field=models.CharField(blank=True, help_text='N° de instrumento de pase a planta permanente - Solo Numero/Año', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalagente',
            name='n_decreto_transferencia_definitiva',
            field=models.CharField(blank=True, help_text='Decreto de transferencia definitiva - Solo Numero/Año', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltituloprofesional',
            name='tituloprofesional_nombre',
            field=models.CharField(help_text='Nombre del título profesional sin abreviaturas. Ej. Técnico Superior en Administración, NO Tec. Sup. en Adm.', max_length=200),
        ),
        migrations.AlterField(
            model_name='tituloprofesional',
            name='tituloprofesional_nombre',
            field=models.CharField(help_text='Nombre del título profesional sin abreviaturas. Ej. Técnico Superior en Administración, NO Tec. Sup. en Adm.', max_length=200),
        ),
        migrations.AddField(
            model_name='agente',
            name='con_errores',
            field=models.BooleanField(default=False, help_text='Se marca automaticamente al importar personal_gral.xlsx si la fila tuvo algun aviso.', verbose_name='Con errores de carga'),
        ),
        migrations.AddField(
            model_name='historicalagente',
            name='con_errores',
            field=models.BooleanField(default=False, help_text='Se marca automaticamente al importar personal_gral.xlsx si la fila tuvo algun aviso.', verbose_name='Con errores de carga'),
        ),
        migrations.RenameField(
            model_name='agente',
            old_name='n_resolucion_cargo_interno',
            new_name='instrumento_cargo_interno',
        ),
        migrations.RenameField(
            model_name='historicalagente',
            old_name='n_resolucion_cargo_interno',
            new_name='instrumento_cargo_interno',
        ),
        migrations.AddField(
            model_name='agente',
            name='instrumento_cargo_interno_tipo',
            field=models.CharField(blank=True, choices=[('RES', 'Resolución'), ('DEC', 'Decreto')], max_length=3, null=True, verbose_name='Tipo de instrumento'),
        ),
        migrations.AddField(
            model_name='historicalagente',
            name='instrumento_cargo_interno_tipo',
            field=models.CharField(blank=True, choices=[('RES', 'Resolución'), ('DEC', 'Decreto')], max_length=3, null=True, verbose_name='Tipo de instrumento'),
        ),
        migrations.AddField(
            model_name='agente',
            name='domicilio_provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carga.provincia'),
        ),
        migrations.AddField(
            model_name='historicalagente',
            name='domicilio_provincia',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='carga.provincia'),
        ),
    ]
