# Generated by Django 6.0.6 on 2026-08-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizador', '0022_squash_agente_instrumentos_aportes_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente',
            name='agente_es_inpector_obra',
            field=models.BooleanField(default=False, help_text='El agente es inspector de obra', verbose_name='Inspector de Obra'),
        ),
        migrations.AlterField(
            model_name='agente',
            name='agente_personal_de_gabinete',
            field=models.BooleanField(default=False, help_text='Tildar si el agente es personal de gabinete', verbose_name='Personal de Gabinete'),
        ),
        migrations.AlterField(
            model_name='agente',
            name='agente_personal_transitorio',
            field=models.BooleanField(default=False, help_text='Tildar si el agente es personal transitorio', verbose_name='Personal Transitorio'),
        ),
        migrations.AlterField(
            model_name='agente',
            name='agente_verificado_contra_padron',
            field=models.BooleanField(default=False, help_text='Los datos fueron verificados contra el padrón electoral', verbose_name='Chequeado'),
        ),
        migrations.AlterField(
            model_name='agente',
            name='domicilio_barrio',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Barrio'),
        ),
        migrations.AlterField(
            model_name='agente',
            name='domicilio_direccion',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='agente',
            name='instrumento_cargo_interno',
            field=models.CharField(blank=True, help_text='Número de instrumento de designación temporal - Solo Numero/Año', max_length=13, null=True, verbose_name='Instrumento de designación temporal'),
        ),
        migrations.AlterField(
            model_name='historicalagente',
            name='agente_es_inpector_obra',
            field=models.BooleanField(default=False, help_text='El agente es inspector de obra', verbose_name='Inspector de Obra'),
        ),
        migrations.AlterField(
            model_name='historicalagente',
            name='agente_personal_de_gabinete',
            field=models.BooleanField(default=False, help_text='Tildar si el agente es personal de gabinete', verbose_name='Personal de Gabinete'),
        ),
        migrations.AlterField(
            model_name='historicalagente',
            name='agente_personal_transitorio',
            field=models.BooleanField(default=False, help_text='Tildar si el agente es personal transitorio', verbose_name='Personal Transitorio'),
        ),
        migrations.AlterField(
            model_name='historicalagente',
            name='agente_verificado_contra_padron',
            field=models.BooleanField(default=False, help_text='Los datos fueron verificados contra el padrón electoral', verbose_name='Chequeado'),
        ),
        migrations.AlterField(
            model_name='historicalagente',
            name='domicilio_barrio',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Barrio'),
        ),
        migrations.AlterField(
            model_name='historicalagente',
            name='domicilio_direccion',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='historicalagente',
            name='instrumento_cargo_interno',
            field=models.CharField(blank=True, help_text='Número de instrumento de designación temporal - Solo Numero/Año', max_length=13, null=True, verbose_name='Instrumento de designación temporal'),
        ),
    ]
