# Generated by Django 6.0.6 on 2026-08-14 16:09

import core.validators
import django.core.validators
import django.db.models.deletion
import personalizador.models
import simple_history.models
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizador', '0023_alter_agente_agente_es_inpector_obra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComisionadoExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agente_nombres', models.CharField(max_length=120, verbose_name='Nombres')),
                ('agente_apellidos', models.CharField(max_length=120, verbose_name='Apellidos')),
                ('agente_nombreyapellido', models.GeneratedField(db_persist=True, expression=personalizador.models.ConcatOp(models.F('agente_nombres'), models.Value(' '), models.F('agente_apellidos')), output_field=models.CharField(editable=False, max_length=256, verbose_name='Nombre y Apellido'))),
                ('abreviatura', models.CharField(blank=True, help_text='Sr./Sra.', max_length=10, null=True, verbose_name='Abreviatura')),
                ('dni', models.DecimalField(decimal_places=0, max_digits=9, unique=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='DNI:')),
                ('cuil', models.CharField(max_length=13, validators=[core.validators.CuitValidator()], verbose_name='CUIT')),
                ('institucion_origen', models.CharField(blank=True, help_text='Organismo/empresa al que pertenece.', max_length=200, null=True, verbose_name='Institución de origen')),
                ('comisionadoexterno_uuid', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False)),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalizador.generoagente')),
            ],
            options={
                'verbose_name': 'Comisionado Externo',
                'verbose_name_plural': 'Comisionados Externos',
                'ordering': ('agente_apellidos', 'agente_nombres'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalComisionadoExterno',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('agente_nombres', models.CharField(max_length=120, verbose_name='Nombres')),
                ('agente_apellidos', models.CharField(max_length=120, verbose_name='Apellidos')),
                ('agente_nombreyapellido', models.GeneratedField(db_persist=True, expression=personalizador.models.ConcatOp(models.F('agente_nombres'), models.Value(' '), models.F('agente_apellidos')), output_field=models.CharField(editable=False, max_length=256, verbose_name='Nombre y Apellido'))),
                ('abreviatura', models.CharField(blank=True, help_text='Sr./Sra.', max_length=10, null=True, verbose_name='Abreviatura')),
                ('dni', models.DecimalField(db_index=True, decimal_places=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0)], verbose_name='DNI:')),
                ('cuil', models.CharField(max_length=13, validators=[core.validators.CuitValidator()], verbose_name='CUIT')),
                ('institucion_origen', models.CharField(blank=True, help_text='Organismo/empresa al que pertenece.', max_length=200, null=True, verbose_name='Institución de origen')),
                ('comisionadoexterno_uuid', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sexo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personalizador.generoagente')),
            ],
            options={
                'verbose_name': 'historical Comisionado Externo',
                'verbose_name_plural': 'historical Comisionados Externos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
