# Generated by Django 6.0.8 on 2026-08-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizador', '0025_backfill_abreviatura_por_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='agente_escalafon',
            field=models.PositiveSmallIntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV')], default=2, help_text='Escalafón (I-IV) usado para calcular el viático diario. Las autoridades del Directorio usan el escalafón configurado en Reglas de Cálculo de Viáticos, independientemente de este valor.', verbose_name='Escalafón'),
        ),
        migrations.AddField(
            model_name='historicalagente',
            name='agente_escalafon',
            field=models.PositiveSmallIntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV')], default=2, help_text='Escalafón (I-IV) usado para calcular el viático diario. Las autoridades del Directorio usan el escalafón configurado en Reglas de Cálculo de Viáticos, independientemente de este valor.', verbose_name='Escalafón'),
        ),
    ]
