# Generated by Django 6.0.8 on 2026-08-21 15:15

import django.db.models.deletion
import simple_history.models
import uuid_utils.compat
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizador', '0026_agente_agente_escalafon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPeriodoLicencia',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('periodolicencia_categoria', models.CharField(choices=[('LOR_ANUAL', 'Anual / Anual Proporcional'), ('LOR_INVIERNO', 'Anual de Invierno')], max_length=15, verbose_name='Categoría')),
                ('periodolicencia_anio', models.PositiveIntegerField(verbose_name='Año')),
                ('periodolicencia_apertura', models.DateField(blank=True, help_text='Por ley: 15/12 del propio año.', null=True, verbose_name='Apertura')),
                ('periodolicencia_fecha_limite_solicitud', models.DateField(blank=True, help_text='Por ley: 31/03 del año siguiente inclusive. Dato de referencia, no bloquea la carga de licencias fuera de esta ventana.', null=True, verbose_name='Fecha límite de solicitud')),
                ('periodolicencia_turno1_desde', models.DateField(blank=True, null=True, verbose_name='Turno 1 - Desde')),
                ('periodolicencia_turno1_hasta', models.DateField(blank=True, null=True, verbose_name='Turno 1 - Hasta')),
                ('periodolicencia_turno2_desde', models.DateField(blank=True, null=True, verbose_name='Turno 2 - Desde')),
                ('periodolicencia_turno2_hasta', models.DateField(blank=True, null=True, verbose_name='Turno 2 - Hasta')),
                ('periodolicencia_uuid', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Período de Licencia',
                'verbose_name_plural': 'historical Períodos de Licencia',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PeriodoLicencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodolicencia_categoria', models.CharField(choices=[('LOR_ANUAL', 'Anual / Anual Proporcional'), ('LOR_INVIERNO', 'Anual de Invierno')], max_length=15, verbose_name='Categoría')),
                ('periodolicencia_anio', models.PositiveIntegerField(verbose_name='Año')),
                ('periodolicencia_apertura', models.DateField(blank=True, help_text='Por ley: 15/12 del propio año.', null=True, verbose_name='Apertura')),
                ('periodolicencia_fecha_limite_solicitud', models.DateField(blank=True, help_text='Por ley: 31/03 del año siguiente inclusive. Dato de referencia, no bloquea la carga de licencias fuera de esta ventana.', null=True, verbose_name='Fecha límite de solicitud')),
                ('periodolicencia_turno1_desde', models.DateField(blank=True, null=True, verbose_name='Turno 1 - Desde')),
                ('periodolicencia_turno1_hasta', models.DateField(blank=True, null=True, verbose_name='Turno 1 - Hasta')),
                ('periodolicencia_turno2_desde', models.DateField(blank=True, null=True, verbose_name='Turno 2 - Desde')),
                ('periodolicencia_turno2_hasta', models.DateField(blank=True, null=True, verbose_name='Turno 2 - Hasta')),
                ('periodolicencia_uuid', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False)),
            ],
            options={
                'verbose_name': 'Período de Licencia',
                'verbose_name_plural': 'Períodos de Licencia',
                'ordering': ('-periodolicencia_anio', 'periodolicencia_categoria'),
                'constraints': [models.UniqueConstraint(fields=('periodolicencia_categoria', 'periodolicencia_anio'), name='unique_periodolicencia_1')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPeriodoLicenciaAgente',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('periodolicenciaagente_dias_correspondientes', models.PositiveIntegerField(help_text='Cupo congelado por antigüedad al momento en que se usó por primera vez este período. No se recalcula.', verbose_name='Días correspondientes')),
                ('periodolicenciaagente_uuid', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('periodolicenciaagente_agente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personalizador.agente', verbose_name='Agente')),
                ('periodolicenciaagente_periodo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personalizador.periodolicencia', verbose_name='Período')),
            ],
            options={
                'verbose_name': 'historical Período de Licencia por Agente',
                'verbose_name_plural': 'historical Períodos de Licencia por Agente',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='historicallicenciapermiso',
            name='licenciapermiso_periodo',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Se completa automáticamente para Anual / Anual Proporcional / Anual de Invierno.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personalizador.periodolicencia', verbose_name='Período de Licencia'),
        ),
        migrations.AddField(
            model_name='licenciapermiso',
            name='licenciapermiso_periodo',
            field=models.ForeignKey(blank=True, help_text='Se completa automáticamente para Anual / Anual Proporcional / Anual de Invierno.', null=True, on_delete=django.db.models.deletion.PROTECT, to='personalizador.periodolicencia', verbose_name='Período de Licencia'),
        ),
        migrations.CreateModel(
            name='PeriodoLicenciaAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodolicenciaagente_dias_correspondientes', models.PositiveIntegerField(help_text='Cupo congelado por antigüedad al momento en que se usó por primera vez este período. No se recalcula.', verbose_name='Días correspondientes')),
                ('periodolicenciaagente_uuid', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False)),
                ('periodolicenciaagente_agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalizador.agente', verbose_name='Agente')),
                ('periodolicenciaagente_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalizador.periodolicencia', verbose_name='Período')),
            ],
            options={
                'verbose_name': 'Período de Licencia por Agente',
                'verbose_name_plural': 'Períodos de Licencia por Agente',
                'constraints': [models.UniqueConstraint(fields=('periodolicenciaagente_agente', 'periodolicenciaagente_periodo'), name='unique_periodolicenciaagente_1')],
            },
        ),
    ]
