# Generated by Django 6.0.8 on 2026-09-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalizador', '0027_historicalperiodolicencia_periodolicencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ad_sin_cuenta_red',
            field=models.BooleanField(default=False, verbose_name='Declara no tener cuenta de red'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ad_username',
            field=models.CharField(blank=True, help_text='sAMAccountName confirmado contra el Active Directory del IPDUV.', max_length=150, null=True, unique=True, verbose_name='Usuario de red (AD)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ad_vinculado_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vinculado el'),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='ad_sin_cuenta_red',
            field=models.BooleanField(default=False, verbose_name='Declara no tener cuenta de red'),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='ad_username',
            field=models.CharField(blank=True, db_index=True, help_text='sAMAccountName confirmado contra el Active Directory del IPDUV.', max_length=150, null=True, verbose_name='Usuario de red (AD)'),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='ad_vinculado_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vinculado el'),
        ),
    ]
