from django import forms
from personalizador import models
from personalizador.views.ajaxviews import (
	generoagentewidget, tituloprofesionalmultiplewidget, categoriawidget,
	denominacioncargowidget, apartadocargowidget, ceicwidget, grupocargowidget,
	actividadespecificawidget, oficinawidget,
)
from carga.views.ajaxviews import localidadwidget, provinciawidget
from core.widgets import DateHTMLWidget

class AgenteForm(forms.ModelForm):
	required_css_class = "required"

	class Meta:
		model = models.Agente
		fields = (
			"agente_nombres",
			"agente_apellidos",
			"n_legajo",
			"sexo",
			"abreviatura",
			"telefono",
			"email",
			"titulo_profesional",
			"matricula",
			"dni",
			"cuil",
			"fecha_nacimiento",
			"fecha_ingreso",
			"fecha_pase_a_planta",
			"n_decreto",
			"instrumento_bonificacion_tipo",
			"instrumento_bonificacion",
			"porcentaje_bonificacion",
			"instrumento_contrato_de_servicio_tipo",
			"instrumento_contrato_de_servicio",
			"categoria",
			"denominacion_cargo",
			"cargo_interno",
			"instrumento_cargo_interno_tipo",
			"instrumento_cargo_interno",
			"apartado",
			"ceic",
			"grupo",
			"activdad_central",
			"actividad_especifica",
			"oficina",
			"n_decreto_transferencia_definitiva",
			"domicilio_direccion",
			"domicilio_barrio",
			"domicilio_localidad",
			"domicilio_provincia",
			"aportes_ley_resolucion_tipo",
			"aportes_ley_resolucion",
			"aportes_ley_resolucion_anios",
			"aportes_ley_resolucion_meses",
			"aportes_ley_resolucion_dias",
			"aportes_anses",
			"aportes_anses_anios",
			"aportes_anses_meses",
			"aportes_anses_dias",
			"agente_verificado_contra_padron",
			"agente_es_inpector_obra",
			"agente_personal_transitorio",
			"agente_personal_de_gabinete",
			"activo",
			"con_errores",
		)
		widgets = {
			"agente_nombres": forms.TextInput(attrs={"class": "form-control"}),
			"agente_apellidos": forms.TextInput(attrs={"class": "form-control"}),
			"n_legajo": forms.NumberInput(attrs={"class": "form-control"}),
			"sexo": generoagentewidget(attrs={"class": "form-control customSelect2"}),
			"abreviatura": forms.TextInput(attrs={"class": "form-control"}),
			"telefono": forms.TextInput(attrs={"class": "form-control"}),
			"email": forms.EmailInput(attrs={"class": "form-control"}),
			"titulo_profesional": tituloprofesionalmultiplewidget(attrs={"class": "form-control customSelect2"}),
			"matricula": forms.TextInput(attrs={"class": "form-control"}),
			"dni": forms.NumberInput(attrs={"class": "form-control"}),
			"cuil": forms.TextInput(attrs={"class": "form-control"}),
			"fecha_nacimiento": DateHTMLWidget(attrs={"class": "form-control", "type": "date"}),
			"fecha_ingreso": DateHTMLWidget(attrs={"class": "form-control", "type": "date"}),
			"fecha_pase_a_planta": DateHTMLWidget(attrs={"class": "form-control", "type": "date"}),
			"n_decreto": forms.TextInput(attrs={"class": "form-control"}),
			"instrumento_bonificacion_tipo": forms.Select(attrs={"class": "form-control customSelect2"}),
			"instrumento_bonificacion": forms.TextInput(attrs={"class": "form-control"}),
			"porcentaje_bonificacion": forms.NumberInput(attrs={"class": "form-control"}),
			"instrumento_contrato_de_servicio_tipo": forms.Select(attrs={"class": "form-control customSelect2"}),
			"instrumento_contrato_de_servicio": forms.TextInput(attrs={"class": "form-control"}),
			"categoria": categoriawidget(attrs={"class": "form-control customSelect2"}),
			"denominacion_cargo": denominacioncargowidget(attrs={"class": "form-control customSelect2"}),
			"cargo_interno": oficinawidget(attrs={"class": "form-control customSelect2"}),
			"instrumento_cargo_interno_tipo": forms.Select(attrs={"class": "form-control customSelect2"}),
			"instrumento_cargo_interno": forms.TextInput(attrs={"class": "form-control"}),
			"apartado": apartadocargowidget(attrs={"class": "form-control customSelect2"}),
			"ceic": ceicwidget(attrs={"class": "form-control customSelect2"}),
			"grupo": grupocargowidget(attrs={"class": "form-control customSelect2"}),
			"activdad_central": forms.TextInput(attrs={"class": "form-control"}),
			"actividad_especifica": actividadespecificawidget(attrs={"class": "form-control customSelect2"}),
			"oficina": oficinawidget(attrs={"class": "form-control customSelect2"}),
			"n_decreto_transferencia_definitiva": forms.TextInput(attrs={"class": "form-control"}),
			"domicilio_direccion": forms.TextInput(attrs={"class": "form-control"}),
			"domicilio_barrio": forms.TextInput(attrs={"class": "form-control"}),
			"domicilio_localidad": localidadwidget(attrs={"class": "form-control customSelect2"}),
			"domicilio_provincia": provinciawidget(attrs={"class": "form-control customSelect2"}),
			"aportes_ley_resolucion_tipo": forms.Select(attrs={"class": "form-control customSelect2"}),
			"aportes_ley_resolucion": forms.TextInput(attrs={"class": "form-control"}),
			"aportes_ley_resolucion_anios": forms.NumberInput(attrs={"class": "form-control"}),
			"aportes_ley_resolucion_meses": forms.NumberInput(attrs={"class": "form-control"}),
			"aportes_ley_resolucion_dias": forms.NumberInput(attrs={"class": "form-control"}),
			"aportes_anses": forms.TextInput(attrs={"class": "form-control"}),
			"aportes_anses_anios": forms.NumberInput(attrs={"class": "form-control"}),
			"aportes_anses_meses": forms.NumberInput(attrs={"class": "form-control"}),
			"aportes_anses_dias": forms.NumberInput(attrs={"class": "form-control"}),
			"agente_verificado_contra_padron": forms.CheckboxInput(attrs={"class": "form-check-input"}),
			"agente_es_inpector_obra": forms.CheckboxInput(attrs={"class": "form-check-input"}),
			"agente_personal_transitorio": forms.CheckboxInput(attrs={"class": "form-check-input"}),
			"agente_personal_de_gabinete": forms.CheckboxInput(attrs={"class": "form-check-input"}),
			"activo": forms.CheckboxInput(attrs={"class": "form-check-input"}),
			"con_errores": forms.CheckboxInput(attrs={"class": "form-check-input"}),
		}
