from django.core.management.base import BaseCommand, CommandError
from secretariador.models import InstrumentosLegalesResoluciones, InstrumentosLegalesResolucionesDirectorio

# class Style:
#     def ERROR(self, text: str) -> str: ...
#     def SUCCESS(self, text: str) -> str: ...
#     def WARNING(self, text: str) -> str: ...
#     def NOTICE(self, text: str) -> str: ...
#     def SQL_FIELD(self, text: str) -> str: ...
#     def SQL_COLTYPE(self, text: str) -> str: ...
#     def SQL_KEYWORD(self, text: str) -> str: ...
#     def SQL_TABLE(self, text: str) -> str: ...
#     def HTTP_INFO(self, text: str) -> str: ...
#     def HTTP_SUCCESS(self, text: str) -> str: ...
#     def HTTP_REDIRECT(self, text: str) -> str: ...
#     def HTTP_NOT_MODIFIED(self, text: str) -> str: ...
#     def HTTP_BAD_REQUEST(self, text: str) -> str: ...
#     def HTTP_NOT_FOUND(self, text: str) -> str: ...
#     def HTTP_SERVER_ERROR(self, text: str) -> str: ...
#     def MIGRATE_HEADING(self, text: str) -> str: ...
#     def MIGRATE_LABEL(self, text: str) -> str: ...
#     def ERROR_OUTPUT(self, text: str) -> str: ...

class Command(BaseCommand):
    def handle(self, *args, **kwargs):
        """
        Collects all InstrumentosLegalesResoluciones of type "D" and creates a new InstrumentosLegalesResolucionesDirectorio with the same data. Then removes the original record.
        """
        resoluciones = InstrumentosLegalesResoluciones.objects.filter(instrumentolegalresoluciones_tipo="D")
        print(f"Resoluciones de Directorio encontradas: {resoluciones.count()}")
        for resolucion in resoluciones:
            if resolucion.instrumentolegalresoluciones_tipo == "D":
                object = InstrumentosLegalesResolucionesDirectorio(
                instrumentolegalresolucionesdirectorio_tipo = resolucion.instrumentolegalresoluciones_tipo,
                instrumentolegalresolucionesdirectorio_numero = resolucion.instrumentolegalresoluciones_numero,
                instrumentolegalresolucionesdirectorio_acta = resolucion.instrumentolegalresoluciones_acta,
                instrumentolegalresolucionesdirectorio_ano = resolucion.instrumentolegalresoluciones_ano,
                instrumentolegalresolucionesdirectorio_fecha_aprobacion = resolucion.instrumentolegalresoluciones_fecha_aprobacion,
                instrumentolegalresolucionesdirectorio_descripcion = resolucion.instrumentolegalresoluciones_descripcion,
                instrumentolegalresolucionesdirectorio = resolucion.instrumentolegalresoluciones,
                )
                try:
                    object.save()
                    print(f"Resolución de Directorio creada: {object.instrumentolegalresolucionesdirectorio_str}")
                    created = object.id
                    if created:
                        resolucion.delete()
                    else:
                        raise Exception("Error al crear la resolución de Directorio")
                except Exception as e:
                    print(f"Error al crear la resolución de Directorio: {e}")
                    print(f"Resolución de Directorio: {resolucion.instrumentolegalresoluciones_numero}")
                