from django.core.management.base import BaseCommand, CommandError
from secretariador.models import Solicitud

# class Style:
#     def ERROR(self, text: str) -> str: ...
#     def SUCCESS(self, text: str) -> str: ...
#     def WARNING(self, text: str) -> str: ...
#     def NOTICE(self, text: str) -> str: ...
#     def SQL_FIELD(self, text: str) -> str: ...
#     def SQL_COLTYPE(self, text: str) -> str: ...
#     def SQL_KEYWORD(self, text: str) -> str: ...
#     def SQL_TABLE(self, text: str) -> str: ...
#     def HTTP_INFO(self, text: str) -> str: ...
#     def HTTP_SUCCESS(self, text: str) -> str: ...
#     def HTTP_REDIRECT(self, text: str) -> str: ...
#     def HTTP_NOT_MODIFIED(self, text: str) -> str: ...
#     def HTTP_BAD_REQUEST(self, text: str) -> str: ...
#     def HTTP_NOT_FOUND(self, text: str) -> str: ...
#     def HTTP_SERVER_ERROR(self, text: str) -> str: ...
#     def MIGRATE_HEADING(self, text: str) -> str: ...
#     def MIGRATE_LABEL(self, text: str) -> str: ...
#     def ERROR_OUTPUT(self, text: str) -> str: ...

class Command(BaseCommand):
    def handle(self, *args, **kwargs):
        """
        Checks if solicitud.solicitud_actuacion is correct.
        """
        actuaciones = Solicitud.objects.all()
        for actuacion in actuaciones:
            # self.stdout.write(self.style.SUCCESS(actuacion.solicitud_actuacion))
            assert actuacion.solicitud_actuacion == "E10-"+str(actuacion.solicitud_actuacion_ano)+"-"+str(actuacion.solicitud_actuacion_numero)+"-AE", f"{self.style.ERROR(actuacion.solicitud_actuacion)} != E10-{actuacion.solicitud_actuacion_ano}-{actuacion.solicitud_actuacion_numero}-AE"
            # self.stdout.write(f"{self.style.SUCCESS(actuacion.solicitud_actuacion_ano)}-{self.style.SUCCESS(actuacion.solicitud_actuacion_numero)} // {self.style.WARNING(actuacion.solicitud_actuacion)}")