from django.core.management.base import BaseCommand, CommandError
from secretariador.models import InstrumentosLegalesResoluciones, InstrumentosLegalesDecretos

# class Style:
#     def ERROR(self, text: str) -> str: ...
#     def SUCCESS(self, text: str) -> str: ...
#     def WARNING(self, text: str) -> str: ...
#     def NOTICE(self, text: str) -> str: ...
#     def SQL_FIELD(self, text: str) -> str: ...
#     def SQL_COLTYPE(self, text: str) -> str: ...
#     def SQL_KEYWORD(self, text: str) -> str: ...
#     def SQL_TABLE(self, text: str) -> str: ...
#     def HTTP_INFO(self, text: str) -> str: ...
#     def HTTP_SUCCESS(self, text: str) -> str: ...
#     def HTTP_REDIRECT(self, text: str) -> str: ...
#     def HTTP_NOT_MODIFIED(self, text: str) -> str: ...
#     def HTTP_BAD_REQUEST(self, text: str) -> str: ...
#     def HTTP_NOT_FOUND(self, text: str) -> str: ...
#     def HTTP_SERVER_ERROR(self, text: str) -> str: ...
#     def MIGRATE_HEADING(self, text: str) -> str: ...
#     def MIGRATE_LABEL(self, text: str) -> str: ...
#     def ERROR_OUTPUT(self, text: str) -> str: ...

class Command(BaseCommand):
    def handle(self, *args, **kwargs):
        """
        Checks if solicitud.solicitud_actuacion is correct.
        """
        decretos = InstrumentosLegalesDecretos.objects.all()
        for decreto in decretos:
            # self.stdout.write(self.style.SUCCESS(actuacion.solicitud_actuacion))
            decreto.instrumentolegaldecretos_numero = str(decreto.instrumentolegaldecretos_numero).zfill(5)
            decreto.save()
            print(f"Decreto = {decreto.instrumentolegaldecretos_numero} -> {str(decreto.instrumentolegaldecretos_numero).zfill(5)}")

        resoluciones = InstrumentosLegalesResoluciones.objects.all()
        for resolucion in resoluciones:
            resolucion.instrumentolegalresoluciones_numero = str(resolucion.instrumentolegalresoluciones_numero).zfill(5)
            resolucion.save()
            print(f"Resolución = {resolucion.instrumentolegalresoluciones_numero} -> {str(resolucion.instrumentolegalresoluciones_numero).zfill(5)}")
