# Generated by Django 6.0.6 on 2026-07-31 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0050_conjuntolicitado_conjunto_resolucion_acta_and_more'),
        ('gdu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObraContratacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vinculado_manualmente', models.BooleanField(default=False, help_text='True si el vínculo vino de una corrección manual (--csv-correcciones) en vez de un match automático único.')),
                ('vinculado_en', models.DateTimeField(auto_now_add=True)),
                ('contratacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obras_vinculadas', to='gdu.contratacion')),
                ('obra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gdu_contratacion', to='carga.obra')),
            ],
        ),
    ]
