# Generated by Django 6.0.8 on 2026-09-26 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gdu', '0003_calle_ejecutor_inspector_intervencionejecutor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioMigrado',
        ),
    ]
