# Generated by Django 6.0.6 on 2026-08-04 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementCommandRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=100)),
                ('argv', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('running', 'En ejecución'), ('success', 'Éxito'), ('failed', 'Falló'), ('killed', 'Detenido')], default='running', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('return_code', models.IntegerField(blank=True, null=True)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('log', models.TextField(blank=True, default='')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='management_command_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ejecución de comando',
                'verbose_name_plural': 'Ejecuciones de comandos',
                'ordering': ('-started_at',),
            },
        ),
    ]
