# Generated by Django 6.0.6 on 2026-08-07 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_managementcommandrun'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcialmente implementado'), ('resuelto', 'Resuelto')], default='pendiente', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todos_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarea pendiente',
                'verbose_name_plural': 'Tareas pendientes',
                'ordering': ('status', '-updated_at'),
            },
        ),
    ]
