# Generated by Django 6.0.8 on 2026-08-26 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_todo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormValidationError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('view_name', models.CharField(max_length=255)),
                ('form_class_path', models.CharField(blank=True, default='', max_length=255)),
                ('form_errors', models.JSONField(blank=True, default=dict)),
                ('formsets', models.JSONField(blank=True, default=list)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_validation_errors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Error de validación de formulario',
                'verbose_name_plural': 'Errores de validación de formularios',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['created_at'], name='core_formva_created_f7dd95_idx'), models.Index(fields=['view_name'], name='core_formva_view_na_67dfe3_idx')],
            },
        ),
    ]
