# Generated by Django 6.0.8 on 2026-09-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_borrar_grupos_invitados_vacios'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginevent',
            name='backend',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Backend de autenticación'),
        ),
    ]
